### PR TITLE
fix: Changed `ScheduledTaskEntity` to enable automatic recovery for tasks stuck in state `running`.

### PR DESCRIPTION
**Pull request by DrauzJu**
### 1. Why is this change necessary?

Currently, a scheduled task may be stuck in the `running` state forever.

### 2. What does this change do, exactly?

This change modifies the behavior of the ScheduledTaskHandler to allow handling messags of scheduled tasks which are in state `running`. At first sight, this introduces the risk that a message is handled twice in parallel, but it must be ensured by the messenger transport that this does not happen.

### 3. Describe each step to reproduce the issue or behaviour.

In the following scenario, a scheduled task would be stuck in the `running` state forever:

1. A queue message, which belongs to a scheduled task, is picked up by a worker. Its handler is called, which inherits from the ScheduledTaskHandler, which updates the state of the scheduled task to `running`.
2. A fatal error occurs while handling the message (e.g. a PHP segmentation fault), which leads to an instant crash of the PHP process.
3. When the queue message will be retried, the ScheduledTaskHandler early returns due to the scheduled task still being in state `running`. The message will be acked and therefore removed from the message queue.
4. The scheduled task will never be scheduled again by the TaskScheduler.

### 4. Please link to the relevant issues (if any).

None

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by AydinHassan** [comment]
thanks @DrauzJu 

> but it must be ensured by the messenger transport that this does not happen. 

What exactly does that mean?

**Comment by DrauzJu** [comment]
@AydinHassan Thanks for looking into it! This means that this change relies on the messenger transport ensuring that it does not deliver a message to multiple receivers concurrently. For example, the `DoctrineTransport`, which is used by default by Shopware, does this by marking the message as delivered. Even if some other transport type might not always guarantee this, it is better to consume a message twice in these edge cases than blocking the scheduled task forever.

**Comment by AydinHassan** [comment]
@DrauzJu thanks ! Is there a list somewhere with which transports guarantee that? If many of them don't I think it would be good if we updated the docs to state that when you need this guarantee you should use this transport and show how to route scheduled tasks to that transport?

Edit: In general we are a bit concerned that this is a BC break and not really expected behaviour, eg we should be able to guarantee a particular behaviour across all handlers. With this change the message queue could begin to explode when for example a task is set to run every minute, and it runs longer than 1 minute, maybe an API is down or the system is under load.

We considered another approach where possibly with a large configurable timelimit - eg 1 day, we could switch the status to failed of any tasks which are still in progress after that limit, in `\Shopware\Core\Framework\MessageQueue\ScheduledTask\Scheduler\TaskScheduler::queueScheduledTasks` perhaps. What do you think?

**Comment by DrauzJu** [comment]
@AydinHassan Thanks for the input!

> Is there a list somewhere with which transports guarantee that?

Unfortunately not. There is only this [list](https://symfony.com/doc/current/messenger.html#transport-configuration) of officially supported transports. All the common messaging systems (Rabbit MQ, Amazon SQS, Google Pub/Sub, Redis, ..) can guarantee the discussed behavior, if configured correctly.

> With this change the message queue could begin to explode when for example a task is set to run every minute, and it runs longer than 1 minute, maybe an API is down or the system is under load.

As far as I understand the system, I think this cannot happen. `TaskScheduler::queueScheduledTasks` would not queue new messages for a scheduled task in state `running`, so the queue would not explode.

> We considered another approach where possibly with a large configurable timelimit - eg 1 day, we could switch the status to failed of any tasks which are still in progress after that limit

Nice fallback ideas as well! Still, I don't like switching to `failed` state, because this would require manual intervention as well, similar to the current behavior. We would prefer a self-healing solution, which would be the case with this PR.

**Comment by AydinHassan** [comment]
@DrauzJu if that's the case then how does your task run again for it to checked? Does the queue retry the message because it failed and then when it comes in to the handler it returns early because it has an in progress status?

**Comment by DrauzJu** [comment]
> Does the queue retry the message because it failed

Yes, exactly! The transport re-delivers messages which were not acknowledged (see for example [here](https://github.com/symfony/doctrine-messenger/blob/533e664a37b4208c5a26f1f7894f212690e806f5/Transport/Connection.php#L369) how doctrine-transport does it).

> then when it comes in to the handler it returns early because it has an in progress status?

Yes, that is the problem at the moment. It returns early and acknowledges the messages, even though it was never processed succesfully.

**Comment by AydinHassan** [comment]
Nice, thanks for bearing with me. I would say this should be fine then!

**Review by AydinHassan — APPROVED** [review]

**Review by mkraeml — APPROVED** [review]

**Comment by AydinHassan** [comment]
@DrauzJu can you maybe try rebase to fix the pipeline?

**Comment by DrauzJu** [comment]
@AydinHassan Done, thanks for the ping

**Review by keulinho — APPROVED** [review]

**Comment by AydinHassan** [comment]
Thanks for your contribution @DrauzJu !

**Pull request merged**
