### PR TITLE
NEXT-20237 slider dots aligned center in mobile device

### PR DESCRIPTION
**Pull request by bavarva-dhruv**
### 1. Why is this change necessary?
Fix make slider dots aligned center in mobile device

### 2. What does this change do, exactly?
Fix slider dots aligned center in mobile device 

### 3. Describe each step to reproduce the issue or behaviour.
1. Navigate to product detail page in mobile device
2. check the slider dots of the slider

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Hey @bavarva-dhruv ,

can you approve the CLA?

**Comment by bavarva-dhruv** [comment]
@shyim Is it now okay?

**Comment by MalteJanz** [comment]
Hi, thank you very much for your contribution. I would like to import / accept this PR but it would be nice if you could check the checklist in your PR description before that.

Even for such a small change it could be useful to at least add a changelog 🙂 . The other points are not really applicable here I think.

**Comment by bavarva-dhruv** [comment]
@MalteJanz Where should I add changelog? In `platform/changelog/_unreleased` folder with new file?

**Comment by MalteJanz** [comment]
@bavarva-dhruv Yes, `platform/changelog/_unreleased` is the right folder. You can use the `bin/console changelog:create` command. The ticket can be left empty for now (I will add one later).

**Comment by bavarva-dhruv** [comment]
@MalteJanz  I've added change log file.

**Comment by MalteJanz** [comment]
@bavarva-dhruv This PR is now in our internal code review 🎉. Thanks again for your work!
Just a little heads up for future PRs:
Please don't merge trunk into your local development branch. If you really want to have the latest changes it is way better to rebase (like `git pull --rebase upstream trunk`). Because merge commits can cause some minor issues on our side.

**Comment by bavarva-dhruv** [comment]
@MalteJanz Okay. Thank you for updating. This is the first PR for me. So I have no idea how should I do.

**Comment by keulinho** [comment]
Hey @bavarva-dhruv we've merged your changes with 38e90c2cea5498751ce9a56970498391b921aed1
thanks for your contribution! :blue_heart: :tada:

**Pull request closed without merging**
