### PR TITLE
To get the [CartFacadeHookFactory and PriceFactoryFactory object] in the [api-storefront hook and api-storeapiresponse hook]

### PR DESCRIPTION
**Pull request by codixio**
... and to be able to read and manipulate the shopping cart

### 1. Why is this change necessary?

[form request object] not available in [cart hook], so we make the cart and price hook available in the [api-storefront and api-storeapiresponse hooks]

### 2. What does this change do, exactly?

# Core
* Changed `src\Storefront\Framework\Script\Api\StorefrontHook.php` added CartFacadeHookFactory::class and PriceFactoryFactory::class, to getServiceIds function.
___
# Storefront
* Changed `src/Core/Checkout/Cart/Hook/CartHook.php` added CartFacadeHookFactory::class and PriceFactoryFactory::class, to getServiceIds function.

### 3. Describe each step to reproduce the issue or behaviour.

services.request.query is not available in the cart hook, so we add the cart and price hook to the StoreApiResponseHook and StorefrontHook

{% if services.request.query.foo === 'bar' %}
    {# clear the cart #}
{% endif %}

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at de5b40a</samp>

This pull request adds new dependencies to the `StoreApiResponseHook` and `StorefrontHook` classes to enable cart and price manipulation in the API and storefront. It also updates the changelog file to document the change.

### <samp>🤖 Generated by Copilot at de5b40a</samp>

*  Add new dependencies to hook classes ([link](https://github.com/shopware/platform/pull/3270/files?diff=unified&w=0#diff-3852542223bbc2d13da2449e18ba4018c8866c8841d5ea3dfd48dadaf4ebbe02R89-R90), [link](https://github.com/shopware/platform/pull/3270/files?diff=unified&w=0#diff-df9f3dcdf6c56ba634d4bbccc02037fc4e1abb2271e9ff50e0b2906f7995f098R90-R91))
* Document the change and the issue in the changelog ([link](https://github.com/shopware/platform/pull/3270/files?diff=unified&w=0#diff-d73487437caec0a4c1e6201e839da094bf53a3de0d03e9fca597c7bc0116d502R1-R12))

### CODE REVIEW

**Comment by codixio** [comment]
@shyim I did what you suggested me on yesterday, not to use the request object within the cart hook, but to make the cart and price dependencies available in the StoreApiResponseHook and StorefrontHook.

**Comment by dneustadt** [comment]
This won't work as the hook needs to implement `CartAware` for `CartFacadeHookFactory::factory` to return an instance of `CartFacade`.  An then the hook needs to be instantiated with the cart. However the hook is dispatched after the cart has already been persisted. So even if you instantiated the hook with the cart, any changes to it would not be persisted. In theory, `CartRuleLoader::loadByCart` would then have to be called again, to go through all the rule invalidation iterations once more after the possible changes, and finally persist the cart for the second time within the process. This is all way too much to handle imho.

I still feel like adding `RequestFacadeFactory` to the services of `CartHook` is viable. Just allow it to return `null` instead of an instance of `Request`. It's non-breaking for everyone that already uses it and from then on  it should just be noted that `services.request` may yield `null`.

**Comment by codixio** [comment]
> It's non-breaking for everyone that already uses it and from then on it should just be noted that `services.request` may yield `null`.

Allright, I will revert the changes and open a new pull request like the one before. Thank you David.

**Comment by dneustadt** [comment]
Suggestions to get around master request being `null`:

Remove the `assert` in `RequestFacadeFactory`.

In `RequestFacade`

```php
public function __construct(private readonly ?Request $request)
{
}
```

Change all the methods to return nullable.

```php
public function scheme(): ?string
{
    return $this->request?->getScheme();
}
```

Or alternatively only in `RequestFacade`:
```php
use Symfony\Component\HttpFoundation\Request;

// ...

$request = $this->requestStack->getMainRequest() ?? new Request();
```

**Comment by codixio** [comment]
> Change all the methods to return nullable.

Could it come to an issue if I return null here?

In `RequestFacade`

```
    /**
     * The method `headers` returns all request headers as an array.
     * It is possible to access only the following headers: content-type, content-length, accept, accept-language, user-agent, referer
     *
     * @return array<string, array<int, string|null>|string|null> request headers
     */
    public function headers(): array
    {
        $headers = array_change_key_case($this->request?->headers->all());

        return array_intersect_key($headers, array_flip(self::ALLOWED_PARAMETERS));
    }
```

**Pull request closed without merging**
