### PR TITLE
allow min length 1;

### PR DESCRIPTION
**Pull request by pietzschke**
### 1. Why is this change necessary?

Minimum length of search text can be 1: [https://issues.shopware.com/issues/NEXT-19255](https://issues.shopware.com/issues/NEXT-19255)

### 2. What does this change do, exactly?

Allow text in SearchWidget to be minimum length 1.

### 3. Describe each step to reproduce the issue or behaviour.

Configure minimum search length to 1 or 2 and try to search from SearchWidget for these products. You cannot find them, because the search only triggers after 3 characters.

### 4. Please link to the relevant issues (if any).

[https://issues.shopware.com/issues/NEXT-19255
](https://issues.shopware.com/issues/NEXT-19255
)
[https://issues.shopware.com/issues/NEXT-18824](https://issues.shopware.com/issues/NEXT-18824
)
### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by MelvinAchterhuis** [comment]
Shouldn't this be configurable instead of hardcoding it to 1? I don't think every merchant needs search suggestions when 1 character is filled in, which can result in unnecessary database queries / load on the server. When configurable the merchant can adapt it to own needs.

**Comment by keulinho** [comment]
i completely agree with @MelvinAchterhuis, there is already a `minSearchLength` field in the `ProductSearchConfig` IMHO we should use the configuration from there also in the storefront search widget.

**Comment by pietzschke** [comment]
Well that could be a possible solution, but i'm lacking experience with the codebase to achieve that. I would also say, that every change in the backend would make a new compiling for the SearchWidget necessary + the client should't have cached the bundled files. Maybe it's better to fire at every character and handle the validation on the backend side.

**Comment by MelvinAchterhuis** [comment]
I've created a configurable solution, see https://github.com/shopware/platform/pull/2372

**Pull request closed without merging**
