### PR TITLE
NEXT-31913 - Add avif image support

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?

This change adds support for the [avif image format](https://aomediacodec.github.io/av1-avif/), which brings numerous improvements over old image formats such as PNG, JPEG or GIF.

Every [modern web browser](https://caniuse.com/?search=avif) supports the avif format for a wide range of users.

This change would allow all shop owners & maintainers to use this optimized image format.

### 2. What does this change do, exactly?
- Adds support for avif image files (static & animated)
- Adds test images of the existing files in the avif format
- Adds tests for all changed and added avif parts of the code

### 3. Describe each step to reproduce the issue or behaviour.
- Create a new Shopware 6 project
- Try to upload an avif image to the shop (in the administration)

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 11a4e1f</samp>

This pull request adds support for the avif image format in the media library. It enables detecting avif images and their properties, generating thumbnails, and uploading and downloading avif files. It also adds test cases and fixtures for the avif detection and thumbnail functions, and updates the changelog and the configuration file.

### <samp>🤖 Generated by Copilot at 11a4e1f</samp>

*  Add support for avif image files in the media library ([link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-b84dafd468b9ffd1630adcc09eed60922d1781adc6886d1a0cabcd3c92a43ea5R1-R11))
*  Enable thumbnail generation for avif images using the imageavif function or throw an exception if not available ([link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-dc9b706d3b673749da3b5cbf57780078ae9fbc0e42d39435eedaf4457d28159cR431-R438))
*  Detect avif files as image types with the TRANSPARENT flag and optionally the ANIMATED flag if they contain the 'avis' container ([link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-a90c68aba5218eb256948f40094b689b6d7bec665c45011afb8c2d6a8db44675R19), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-a90c68aba5218eb256948f40094b689b6d7bec665c45011afb8c2d6a8db44675R55-R58), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-a90c68aba5218eb256948f40094b689b6d7bec665c45011afb8c2d6a8db44675R121-R154))
*  Add two avif files to the fixtures folder for testing purposes: `animated.avif` and `shopware-logo.vp8x.avif` ([link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-a1e4e54be2f013beb7fcdb31a19b5e0b2afa0351194a1687ddbb75512ad3e694L1-R68), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-890a572cf271400a4b5367442c6caf784618f7dbb7a15e8eba9c10b3275719c4L1-R20))
*  Add test cases to various TypeDetector classes to assert that avif files are correctly detected as image types and not as other types ([link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-ae7f385031490d3ce67bba01930bd7ec3899ffca1592a1e269229b6893e10320R39-R48), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-abbad5a8f42b3049bedd10095b7d785643ba594240597a8c3661438741700c67R51-R60), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-bd8bba4449798e02a8760407314d644fa57d151fc1d615bb20600522ed5e58a3R39-R48), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-d2d08e70f89dd5eecdc0895c9e713adeaac91575baa22da16c3137571d03f00aR150-R208), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-9f001c29a7ef30c76d6ad06e10329d49aafd254a6704d2ce5f3e582fb3aa1be1R68-R90), [link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-1df79ec0068ef6f627848519bac08fe0223ae36fb3606beecc186b76f34e2a53R39-R48))
*  Add the 'avif' extension to the allowed_extensions and private_allowed_extensions lists in the `shopware.yaml` configuration file ([link](https://github.com/shopware/platform/pull/3178/files?diff=unified&w=0#diff-e0d53f5ab2b7f5d42fc04e96e051e0c60c80e77a63fcb806ea4b83b13163912eL26-R27))

### CODE REVIEW

**Comment by akf-bw** [comment]
Rebased the commit to the latest trunk branch changes. @shyim this PR can now get reviewed.

**Comment by akf-bw** [comment]
@shyim I just rebased my changes to the latest trunk changes to stay up to date for you. Now the "Danger" PR-check fails. Can you see the reason for this? I didn't change anything in my code as with the rebase no changes were required to work with the latest media path changes.

**Comment by ghost** [comment]
I just rebased to the latest trunk changes, no changes were made to my changes from this PR.

**Comment by bschulzebaek** [comment]
Hey @akf-bw , we just merged your changes. Thanks for the contribution 💙

**Pull request closed without merging**
