### PR TITLE
NEXT-00000 - Fix action selection in flow builder

### PR DESCRIPTION
**Pull request by Ceddy610**
### 1. Why is this change necessary?
If a trigger is aware of more than one entity, then the custom field action might not be displayed properly in the administration. By selecting the `Change custom field content` action and selecting the `order` entity, the Flow Builder displays an unknown action, even though the action shouldn't be unknown.

### 2. What does this change do, exactly?
It removes an unnecessary filter and adds a preselected entity selection in the corresponding modals. Moreover, it restructures the grouping of the actions that can be selected, as the filter is removed.

#### Before
Bildschirmfoto 2024-10-15 um 09 42 26

#### After
Bildschirmfoto 2024-10-15 um 09 45 48

### 3. Describe each step to reproduce the issue or behaviour.
1. Create a new flow
2. Add `Checkout / Order / Placed` trigger
3. Add a new THEN action
4. Select “Change custom field content” and select the order entity
5. Select any custom field
6. Add action

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by jozsefdamokos** [comment]
@Ceddy610 thanks for your contribution!

**Comment by Ceddy610** [comment]
It seems that my changes got overwritten by some kind of merge conflict:
https://github.com/shopware/shopware/blob/2d97375bdc99936fadbf1d2b85f601790bdc2227/src/Administration/Resources/app/administration/src/module/sw-flow/state/flow.state.js#L227-L237

Is it possible to add the changes made by this PR again?

**Comment by mitelg** [comment]
@Ceddy610 would you mind creating a fixing PR again? :see_no_evil:

**Comment by Ceddy610** [comment]
> @Ceddy610 would you mind creating a fixing PR again? 🙈

@mitelg I opened another PR [here](https://github.com/shopware/shopware/pull/5813)

**Pull request closed without merging**
