### PR TITLE
Fix hot proxy server for shared instances

### PR DESCRIPTION
**Pull request by element-code**
### 1. Why is this change necessary?
Currently, the hot-proxy fails to work in shared instances e.g. when using on an internal development server where multiple web application get built at the same time with different domains.
This allows the hot-proxy to get used in a way more widespread environment since many people are not used to local-machine development environments or restricted by company rules to internal development servers.

### 2. What does this change do, exactly?
This change fixes multiple things
1. errors inside the lifecycle of a request are now handled properly instead of crashing the whole hot-proxy
1. port-binds are now bound to the host which eliminates unforeseen binding behavior (e.g. binding to the default `::` host [may result in only a IPv6 bind](https://nodejs.org/docs/latest-v15.x/api/net.html#net_server_listen_port_host_backlog_callback))
1. the request is now piped to a specific host instead of the internal loopback address, which allows any domain-based routers to work properly (e.g. apache/nginx)
1. reject requests from the wrong host to prevent domain specific content to be served on another domain

### 3. Describe each step to reproduce the issue or behaviour.
* Accessing the Hot-Proxy won't work when using IPv4 because of the IPv6-only bind
```
$ lsof -i :9998
COMMAND TYPE NODE NAME
node    IPv6 TCP :9998 (LISTEN)
```
* When able to access the Hot-Proxy the pipe won't work due an error: `connect ECONNREFUSED 127.0.0.1:80`

### 4. Please link to the relevant issues (if any).
n/a

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
I have also an internal PR which fixes a similar issue. Maybe this fixes this too? It works also on a single port instead of two

```
From 2b0509fb48085df30cffdc7f431203375311eacd Mon Sep 17 00:00:00 2001
From: Soner Sayakci <s.sayakci@shopware.com>
Date: Sat, 13 Feb 2021 10:02:11 +0000
Subject: [PATCH] NEXT-10838 - Improve storefront watcher

---
 .../2021-02-13-improve-storefront-watcher.md  |  7 +++++
 .../build/proxy-server-hot/index.js           | 29 ++++++++++++++-----
 .../app/storefront/build/start-hot-reload.js  |  5 ++--
 .../app/storefront/webpack.config.js          | 13 ++++++---
 .../Resources/views/storefront/base.html.twig | 12 ++++----
 5 files changed, 46 insertions(+), 20 deletions(-)
 create mode 100644 changelog/_unreleased/2021-02-13-improve-storefront-watcher.md

diff --git a/changelog/_unreleased/2021-02-13-improve-storefront-watcher.md b/changelog/_unreleased/2021-02-13-improve-storefront-watcher.md
new file mode 100644
index 0000000000..8b75120279
--- /dev/null
+++ b/changelog/_unreleased/2021-02-13-improve-storefront-watcher.md
@@ -0,0 +1,7 @@
+---
+title: Improve storefront watcher
+issue: NEXT-10838
+---
+# Storefront
+* Removed port suffix in hot module server when the port is `80` or `443`
+* Changed hot module server to support setups with external ip
diff --git a/src/Storefront/Resources/app/storefront/build/proxy-server-hot/index.js b/src/Storefront/Resources/app/storefront/build/proxy-server-hot/index.js
index d9146d30c7..ac56e30a7c 100644
--- a/src/Storefront/Resources/app/storefront/build/proxy-server-hot/index.js
+++ b/src/Storefront/Resources/app/storefront/build/proxy-server-hot/index.js
@@ -8,13 +8,13 @@ const { createServer, request } = require('http');
 const { spawn } = require('child_process');
 
 module.exports = function createProxyServer({ appPort, originalHost, proxyHost, proxyPort }) {
-    const proxyUrl = `${proxyHost}:${proxyPort}`;
-
+    const proxyUrl = proxyPort !== 80 && proxyPort !== 443 ? `${proxyHost}:${proxyPort}`: proxyHost;
     const originalUrl = appPort !== 80 && appPort !== 443 ? `${originalHost}:${appPort}` : originalHost;
 
     // Create the HTTP proxy
     const server = createServer((client_req, client_res) => {
         const requestOptions = {
+            host: originalHost,
             port: appPort,
             path: client_req.url,
             method: client_req.method,
@@ -22,11 +22,23 @@ module.exports = function createProxyServer({ appPort, originalHost, proxyHost,
                 ...client_req.headers,
                 host: originalUrl,
                 'hot-reload-mode': true,
-                'hot-reload-port': process.env.STOREFRONT_ASSETS_PORT || 9999,
-                'accept-encoding': 'identity'
-            }
+                'accept-encoding': 'identity',
+            },
         };
 
+        // Assets
+        if (client_req.url.indexOf('/_webpack_hot_proxy_/') === 0) {
+            requestOptions.host = '127.0.0.1';
+            requestOptions.port = process.env.STOREFRONT_ASSETS_PORT || 9999;
+            requestOptions.path = requestOptions.path.substr(20);
+        }
+
+        // Hot reload updates
+        if (client_req.url.indexOf('/sockjs-node/') === 0 || client_req.url.indexOf('hot-update.json') !== -1 || client_req.url.indexOf('hot-update.js') !== -1) {
+            requestOptions.host = '127.0.0.1';
+            requestOptions.port = process.env.STOREFRONT_ASSETS_PORT || 9999;
+        }
+
         // pipe a new request to the client request
         client_req.pipe(
             // request the data
@@ -56,7 +68,7 @@ module.exports = function createProxyServer({ appPort, originalHost, proxyHost,
 function openBrowserWithUrl(url) {
     const childProcessOptions = {
         stdio: 'ignore',
-        detached: true
+        detached: true,
     };
 
     try {
@@ -82,7 +94,10 @@ function replaceOriginalUrl(response, clientResponse, originalUrl, proxyUrl) {
     // when request is finished
     response.on('end', () => {
         // replace original url with proxy url
-        const responseBody = responseData.replace(new RegExp(`${originalUrl}/`, 'g'), `${proxyUrl}/`);
+        const responseBody = responseData
+            .replace(new RegExp(`${originalUrl}/`, 'g'), `${proxyUrl}/`)
+            // Replace Symfony Profiler URL to relative url @see: https://regex101.com/r/HMQd2n/2
+            .replace(/http[s]?\\u003A\\\/\\\/[\w\.]*(\:\d*|\\u003A\d*)?\\\/_wdt/gm, `/_wdt`);
 
         // end the client response with sufficient headers
         clientResponse.writeHead(response.statusCode, response.headers);
diff --git a/src/Storefront/Resources/app/storefront/build/start-hot-reload.js b/src/Storefront/Resources/app/storefront/build/start-hot-reload.js
index a7973b6ab2..89e1b8e76d 100644
--- a/src/Storefront/Resources/app/storefront/build/start-hot-reload.js
+++ b/src/Storefront/Resources/app/storefront/build/start-hot-reload.js
@@ -6,6 +6,7 @@ const server = createLiveReloadServer();
 
 server.then(() => {
     const fullUrl = process.env.APP_URL;
+    const proxyUrl = new URL(process.env.PROXY_URL || process.env.APP_URL);
     const proxyPort = process.env.STOREFRONT_PROXY_PORT;
 
     // first value of array is the http protocol
@@ -15,8 +16,8 @@ server.then(() => {
     const proxyServerOptions = {
         originalHost: domain,
         appPort: port || 80,
-        proxyHost: domain,
-        proxyPort: proxyPort || 9998,
+        proxyHost: proxyUrl.hostname,
+        proxyPort: parseInt(proxyPort || 9998),
     };
 
     // starting the proxy server
diff --git a/src/Storefront/Resources/app/storefront/webpack.config.js b/src/Storefront/Resources/app/storefront/webpack.config.js
index c95826f517..fc748f1d79 100644
--- a/src/Storefront/Resources/app/storefront/webpack.config.js
+++ b/src/Storefront/Resources/app/storefront/webpack.config.js
@@ -26,10 +26,14 @@ if (isHotMode) {
 }
 
 let hostName;
+const proxyPort = parseInt(process.env.STOREFRONT_PROXY_PORT || 9998);
 
 try {
-    const { protocol, hostname } = new URL(process.env.APP_URL);
+    const { protocol, hostname } = new URL(process.env.PROXY_URL || process.env.APP_URL);
     hostName = `${protocol}//${hostname}`;
+    if (proxyPort !== 80 && proxyPort !== 443) {
+        hostName += `:${proxyPort}`;
+    }
 } catch (e) {
     hostName = undefined;
 }
@@ -40,7 +44,8 @@ let webpackConfig = {
         if (isHotMode) {
             return {
                 contentBase: path.resolve(__dirname, 'dist'),
-                publicPath: `${hostName}${isHotMode ? ':9999' : ''}/`,
+                public: hostName,
+                publicPath: `${hostName}/`,
                 open: false,
                 overlay: {
                     warnings: false,
@@ -54,7 +59,7 @@ let webpackConfig = {
                 compress: false,
                 disableHostCheck: true,
                 port: 9999,
-                host: '0.0.0.0',
+                host: '127.0.0.1',
                 clientLogLevel: 'warning',
                 headers: {
                     'Access-Control-Allow-Origin': '*'
@@ -281,7 +286,7 @@ let webpackConfig = {
     output: {
         path: path.resolve(__dirname, 'dist'),
         filename: './js/[name].js',
-        publicPath: `${hostName}${isHotMode ? ':9999' : ''}/`,
+        publicPath: `${hostName}/`,
         chunkFilename: './js/[name].js'
     },
     performance: {
diff --git a/src/Storefront/Resources/views/storefront/base.html.twig b/src/Storefront/Resources/views/storefront/base.html.twig
index 009c5f95d3..69dc69a495 100644
--- a/src/Storefront/Resources/views/storefront/base.html.twig
+++ b/src/Storefront/Resources/views/storefront/base.html.twig
@@ -160,14 +160,12 @@
 
         {% block base_script_hmr_mode %}
             {% if isHMRMode %}
-                {% set baseUrl = app.request.getScheme() ~ '://' ~ app.request.getHost() %}
-                {% set port = app.request.headers.get('hot-reload-port') %}
-                <script type="text/javascript" src="{{ baseUrl }}:{{ port }}/js/vendor-node.js"></script>
-                <script type="text/javascript" src="{{ baseUrl }}:{{ port }}/js/vendor-shared.js"></script>
-                <script type="text/javascript" src="{{ baseUrl }}:{{ port }}/js/runtime.js"></script>
-                <script type="text/javascript" src="{{ baseUrl }}:{{ port }}/js/app.js"></script>
+                <script type="text/javascript" src="/_webpack_hot_proxy_/js/vendor-node.js"></script>
+                <script type="text/javascript" src="/_webpack_hot_proxy_/js/vendor-shared.js"></script>
+                <script type="text/javascript" src="/_webpack_hot_proxy_/js/runtime.js"></script>
+                <script type="text/javascript" src="/_webpack_hot_proxy_/js/app.js"></script>
                 {# The storefront entry is a combined entry point which contains all plugins & themes #}
-                <script type="text/javascript" src="{{ baseUrl }}:{{ port }}/js/storefront.js"></script>
+                <script type="text/javascript" src="/_webpack_hot_proxy_/js/storefront.js"></script>
             {% else %}
                 {% for file in shopware.theme.assets.js %}
                     <script type="text/javascript" src="{{ asset(file, 'theme') }}" async></script>
-- 
GitLab
```

Example usage: https://github.com/shyim/shopware-docker/commit/161b2d3cb871223d63e9398d4cb3da1f57168b67
APP_URL = Where Shopware is running, PROXY_URL = Where the watcher is running

**Comment by element-code** [comment]
@shyim ill try this on Monday, weekend is calling :)

**Comment by J-Rahe** [comment]
Hey @element-code, could you give me a quick update on monday?

**Comment by element-code** [comment]
@J-Rahe, as far as I can see the changes that @shyim made are looking fine & work as required by this PR. 
1. HMR watcher triggers on plugin SCCS & JS changes
2. storefront reloads properly, 
3. The second port `9999` doesn't need to be open to the public anymore 👏

Something with the web sockets is not working as expected, it did not affect the workflow anyways.*
Unbenannt-1


I still would suggest some changes (references to 2. What does this change do, exactly?):

1. Let the proxy server listen to `proxyPort, proxyHost` instead of only listening to `proxyPort` as done in https://github.com/shopware/platform/pull/1642/commits/cfe62765ce0b7532df9f4511c7d7a73cdc7c2f03 (see reason in 2.2.)
2. Reject hot-proxy request from wrong hosts as done in https://github.com/shopware/platform/pull/1642/commits/c67a63db7b6900084810715dea0da8ea5d2ce4d7 (2.4.)
3. Handle errors in the server request callback "properly" as done in https://github.com/shopware/platform/pull/1642/commits/9979d02a112788bc1d673e34208bcc51ffe856fa (2.1.)

**Comment by shyim** [comment]
Hey @element-code ,

My changes are now merged. The first change could be problematic. The current setup uses as proxyHost localhost. This would make the server listing only to `127.0.0.1` and not more accessible from outside the docker container.

I have no idea how to handle that smooth with only one Env. As we have already a env for the port, we could create there a second one for the listen ip.

The both other changes are fine for me. 

Thanks for your Contribution! 💙

**Comment by element-code** [comment]
I've excluded the first change from this PR :)

**Comment by shyim** [comment]
Can you rebase into one commit?

**Comment by element-code** [comment]
@shyim I tried, but the merge commit seems to create the conflict again and again.
Please tell me how to handle that.
Right now the history is messed up since that merge commit  contains only the conflict resolution and the main commit contains the real merge changes.. 
I'm not proud of this :D

I can revert everything and re-do my changes, but this will not resolve the real problem when a merge-commit is in the way between two to-squash commits.

**Comment by J-Rahe** [comment]
Maybe try git reset --soft? that would set you back to the choosen commit with the changes you did in an "to-be-commited"-state.

**Comment by element-code** [comment]
But there is more.. HTTPS.

I'm not sure about the source, but it seems that Firefox throws an `upgrade-insecure-requests` header in the request when the domain is known to support HTTPS. This is fine but when connecting to `:9998` we get our upgrade as well ... and then we get a `SSL_ERROR_RX_RECORD_TOO_LONG` error.
The question is, do you see any way to support HTTPS on the hot proxy? -- have each developer change his complete browser behavior to be able to develop shopware project seems not like an option.

I had the following ideas..:
1. Implement SSL compatibility -- would consider this as the best way to handle the problem
    1. Introduce two new environment variables for the key file paths -> requires configuration -- not my favorite
    2. Bring self-signed keys with shopware, only for this -> this would allow using HTTPS for the hot proxy in general for all shopware development; after accepting the self-signed cert  -- more likely my favorite
2. Deny upgrading requests on the hot proxy -- i have no idea how to do that / if it is possible

**Comment by J-Rahe** [comment]
Hey @element-code, that does sound more like an problem with the setup to me. If you cant tell your server not to serve https on that port, maybe an TLS termination proxy can help? Having the hot proxy run on an Server is not really that common and adding https to the hot-proxy servers will probably be quite a bit of work.

**Comment by element-code** [comment]
Yeah, I'm not quite sure how the stack is built and who has control over the upgrade process itself.
The main question is if node is involved in that process. 
On the other hand should the hot-proxy support/use HTTPS for security reasons.
Let us move this topic out of this merge request, I'll write an issue for this.

----
This PR should be ready to merge? @J-Rahe

**Comment by J-Rahe** [comment]
@element-code, if you complete the changelog i can put it in our internal review. 
You are missing the mail (you do have an mail from github for the case that you don't want your private mail in the changelog) 
and we do have some keywords( Added, Removed, Changed, Deprecated) that have to be used, you can take a look at the `/changelog/_example.md` if you are unsure.

**Comment by J-Rahe** [comment]
@element-code?

**Comment by element-code** [comment]
@J-Rahe done 👍

**Comment by J-Rahe** [comment]
Hey @element-code, your PR was merged : )

**Pull request closed without merging**
