### PR TITLE
Implement a small performance optimization

### PR DESCRIPTION
**Pull request by fabpot**
As PHP does not care about the case of methods, let's simplify the code :)

### CODE REVIEW

**Review by OliverSkroblin — APPROVED** [review]

**Comment by keulinho** [comment]
@fabpot Could you please sign the [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=2493) otherwise we can't merge your contribution. 

If you have any objections against doing so, just give me hint, then we will do the change internally.

**Comment by fabpot** [comment]
I think there is no need for a CLA for such a trivial change. Feel free to close this PR and do it yourself :)

**Comment by keulinho** [comment]
Ok i'll pick it up and will link/close this PR in the commit.

**Comment by fabpot** [comment]
Thank you.

**Pull request closed without merging**
