### PR TITLE
Add active state icon to payment provider selection

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?

https://github.com/shopware/shopware/pull/2251

image

### 2. What does this change do, exactly?

* Added slot `preview` to `sw-select-result` to have a slot before the text for easier object placement and similar code structure to table cells
* Added slot `result-label-preview` to `sw-entity-multi-select` to expose the `preview` slot from `sw-select-result` like the `result-label-property` slot
* Added active state icon to `sw-sales-channel-defaults-select` as preview for the result item depending on new property `showActiveState` (defaults to false)
* Changed `showActiveState` for payment method, country and shipping method configurations in `sw-sales-channel-detail-base`
* Changed sorting of payment methods in `sw-sales-channel-detail-base` for payment methods selection from `position ASC` to `active DESC, position ASC`

### 3. Describe each step to reproduce the issue or behaviour.

1. Install PayPal app from first run wizard (accidentally)
2. Remove PayPal app
3. Install Mollie app from store
4. Install Klarna app from store
5. Have 50+ payment methods
6. Don't know about the alert that pops up if you select a disabled payment method
7. Be confused where the right PayPal integration is

### 4. Please show me a preview of what it looks like

image

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
I add the issue to the changelog :)

**Comment by JoshuaBehrens** [comment]
As discussed with @NiklasLimberg and @Weltraumakustik I upgraded the icon choice from SW5 to SW6 styling:

image

Looks good 👍 

---

I also changed naming for the prop to match the place that already has these active hints: sw-tree-items. I also rebased. Have fun reviewing :)

**Comment by NiklasLimberg** [comment]
Thank you for your contribution! 💙

**Comment by JoshuaBehrens** [comment]
Thank you for merging :) 
duck dance

**Pull request closed without merging**
