### PR TITLE
Allow to specify custom field types for attributed entities

### LINKED ISSUE #5494: [Github] Allow to specify custom field types for attributed entities
### 1. Why is this change necessary?

Sometimes it's useful to have custom fields, for example when you need accessors.

### 2. What does this change do, exactly?

Instead of making the list of field types longer and longer, I added support for specifying a field class directly. If set, it will use that field type.

### 3. Describe each step to reproduce the issue or behaviour.

Try to use a custom field type for an attributed entity field. It will currently not work.

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

---

Imported from Github. Please see: https://github.com/shopware/shopware/pull/5230

### PR DESCRIPTION
**Pull request by nickygerritsen**
### 1. Why is this change necessary?

Sometimes it's useful to have custom fields, for example when you need accessors.

### 2. What does this change do, exactly?

Instead of making the list of field types longer and longer, I added support for specifying a field class directly. If set, it will use that field type.

### 3. Describe each step to reproduce the issue or behaviour.

Try to use a custom field type for an attributed entity field. It will currently not work.

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by nickygerritsen** [comment]
Where is the documentation? I can update it to show there is support for this now.

**Comment by nickygerritsen** [comment]
Not sure why codecov thinks the lines are not covered, since they are? Maybe because it is a compiler pass?

**Comment by mitelg** [comment]
hey @nickygerritsen 
thanks for your contribution :+1: 
You can find the docs repo here: https://github.com/shopware/docs
codecov is complaining as we generated the line coverage only from unit tests and not from the integration tests, you adjusted :wink:

**Comment by nickygerritsen** [comment]
Docs PR: https://github.com/shopware/docs/pull/1526

And I assume the complain about codecov is fine then.

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @nickygerritsen 👍🎉💙

I will have a look at the docs tomorrow :ok_hand:

**Pull request closed without merging**
