### PR TITLE
Fix Bulk Edit one to many associations length evaluation and infinite requests

### PR DESCRIPTION
**Pull request by LunaDotGit**
### 1. Why is this change necessary?
```
if (mappedExistAssociations.hasOwnProperty(key)) {
  mappedExistAssociations[key].push(association);
 }
```
leads to evaluation errors at  `if (existAssociations.total > Object.keys(mappedExistAssociations).length)` as the mappedExistAssociations will never be === existAssociations.total. Thus the associations must be counted, otherwise there will be infinite requests.

### 2. What does this change do, exactly?
It will count the length of each mappedExistAssociation array as it can be larger than one. It also changes the evaluation for the recursion.

### 3. Describe each step to reproduce the issue or behaviour.
The wrong behaviour can be reproduced like this:
- Bulk Edit a lot of Variants with medias that are associated to multiple products
- Add a new media
- See that the bulk edit will never end, as it will keep sending requests (recursion doesn't stop) -> Bulk Edit add Media is not possible

### 4. Please link to the relevant issues (if any).
-

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 7c7dbef</samp>

This pull request fixes a bug in the bulk edit feature for one to many associations in the administration module. It changes the logic of the `_fetchOneToManyAssociated` method in `bulk-edit-base.handler.js` to correctly count and compare the number of associations. It also adds a changelog entry for the fix.

### <samp>🤖 Generated by Copilot at 7c7dbef</samp>

*  Fix bulk edit feature for one to many associations ([link](https://github.com/shopware/platform/pull/3328/files?diff=unified&w=0#diff-8d796e35a793ff9f76a69aad42dddb2cb7b03809aab9105665c5a3058321047fR1-R10), [link](https://github.com/shopware/platform/pull/3328/files?diff=unified&w=0#diff-5f4db1d5427e42ab3e5d758f48cbd2741e6c9ea1e5c9d727db3aa432da75aa0aL479-R485))
   * Add changelog entry for the fix in `changelog/_unreleased/2023-09-27-fix-one-to-many-bulk-edit` ([link](https://github.com/shopware/platform/pull/3328/files?diff=unified&w=0#diff-8d796e35a793ff9f76a69aad42dddb2cb7b03809aab9105665c5a3058321047fR1-R10))
   * Modify `_fetchOneToManyAssociated` method in `BulkEditBaseHandler` class in `src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-base.handler.js` ([link](https://github.com/shopware/platform/pull/3328/files?diff=unified&w=0#diff-5f4db1d5427e42ab3e5d758f48cbd2741e6c9ea1e5c9d727db3aa432da75aa0aL479-R485))

### CODE REVIEW

**Comment by M-arcus** [comment]
Mentioned in issue https://issues.shopware.com/issues/NEXT-30381

**Comment by vienthuong** [comment]
Hi @TheAnimeGuru 
Sorry for the late response
Thank you for your contribution. The changes looks good to me.
However please rebase the PR to latest and fix the lint admin before we can merge it.

**Review by tamvt — APPROVED** [review]

**Comment by M-arcus** [comment]
> Hello,
> 
> thank you for creating this pull request. I have opened an issue on our Issue Tracker for you. See the issue link: [issues.shopware.com/issues/NEXT-31890](https://issues.shopware.com/issues/NEXT-31890)
> 
> Please use this issue to track the state of your pull request.

An issue for this pull request  existed already: https://issues.shopware.com/issues/NEXT-30381

**Comment by tamvt** [comment]
Your PR has been merged. Thank you for your contribution 💙

**Pull request closed without merging**
