### PR TITLE
NEXT-35502 - Fix migration saleschannel test

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
- Run the `Unit / PHPUnit for migration,migration-tests`, sometimes the tests will fail at the `testItDoesNotBreakIfNoHeadlessSalesChannelIsPresent` function, because the sales channel can be blocked by other tests (e.g. order tests that refer to the saleschannel) running at the same time

### 2. What does this change do, exactly?
* Changed `Migration1620820321AddDefaultDomainForHeadlessSaleschannelTest` to catch `ForeignKeyConstraintViolationException`

### 3. Describe each step to reproduce the issue or behaviour.
- Run the `Unit / PHPUnit for migration,migration-tests`, sometimes the tests will fail at the `testItDoesNotBreakIfNoHeadlessSalesChannelIsPresent` function, because the sales channel can be blocked by other tests (e.g. order tests that refer to the saleschannel) running at the same time

### 4. Please link to the relevant issues (if any).
- /

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by akf-bw** [comment]
@OliverSkroblin I just [forced pushed](https://github.com/shopware/shopware/compare/ed7306db38b406b5519aaa032054065eed5d4e37..1e4af8a4a19b0b1fc21d65f1bcc71be1b2f76535) again to remove the now unused import ^^

**Comment by ghost** [comment]
@OliverSkroblin Is there something holding this PR back from being merged?

**Comment by OliverSkroblin** [comment]
> @OliverSkroblin Is there something holding this PR back from being merged?

Not really, just internal pipelines which are failling right now. Nothing regarding your code change

**Comment by ghost** [comment]
@OliverSkroblin It looks like recent pipeline changes that reorder test execution time unintentionally fixed the bug from the pipeline. However, just to be safe, it would be nice to merge this so we can be sure that the pipeline doesn't fail due to an invalid error.

**Comment by mitelg** [comment]
thanks for your contribution @akf-bw 👍🎉💙

**Pull request closed without merging**
