### PR TITLE
Add missing admin template blocks

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?

Although the twig blocks in the admin vue component are considered private there is a downside of the implementation of twigjs. There is always an extend of the component. So there is not way to change the template of a component, when there is no block. I looked up every component without a block and added at least a single block around it so you can have some sort of impact.

image

### 2. What does this change do, exactly?

Add twig blocks on every file, that has none at all.

### 3. Describe each step to reproduce the issue or behaviour.

* Create custom fields on units
* Open custom fields
* Look for the custom field set renderer showing the custom fields

image

* Accept fate, that the custom field set renderer has not been placed
* No worries, it is easy in use. Just override the component with a new component

https://github.com/shopware/platform/blob/5faa66b6d7379bc5124681fa0fe16323d930cee8/src/Administration/Resources/app/administration/src/module/sw-settings-units/page/sw-settings-units-detail/index.html.twig#L1-L49

* hello_darkness_my_old_friend.wma

This is why I did this so I can do https://github.com/shopware/platform/pull/3117 easier

### 4. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at df6c8ce</samp>

This pull request adds missing twig blocks to various admin components to enable customization and extension of their rendering logic. It also fixes a syntax error in the `sw-category-detail-custom-entity` component and adds a changelog file to document the changes.

### <samp>🤖 Generated by Copilot at df6c8ce</samp>

*  Add new file `2023-06-14-add-missing-admin-component-twig-blocks.md` to document the changes ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-f897cc055eb1b4b8a1deb7980f1c947862a97de0f07331ef40cc77211d89f172R1-R130))
  * `sw-extension-icon` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-d1d1fca1287ac97265fb1b200859897e9fa5620b1c7dea8651bd30d9f0c79911L1-R10))
  * `sw-ai-copilot-badge` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-590fd18d99dc2656ad129f0e7873a0a106723dbb8d6ba77e422b513f99e038c8L1-R30))
  * `sw-ai-copilot-warning` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-b36b74aaff23596a70bfc2637badb1153589819aa4f9fec41543670bdbf55276L1-R13))
  * `sw-app-wrong-app-url-modal` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-0a201bd70945645a77953cf80c0340d2fb87b4e2e012dfeec9b07052427a35faL1-R42))
  * `sw-circle-icon` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-0e239ae6e6e4481976b4fafb669e13f63c5f73f985bd30e39ac5a360a67dcadeL1-R14))
  * `sw-icon` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-215303ba59334bd033602a3d11703798585c7921de69dcfd766d97e34b9e5e33L1-R11))
  * `sw-extension-component-section` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-4f72579dff59b3fcacc6e966e2493ac063175f0a0c901a8fc1b7d64320167237L1-R51))
  * `sw-iframe-renderer` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-df8fc2005a4695417bb97722314130bf2c6aaf7f1f331abf98ff2db82bac9faaL1-R33))
  * `sw-meteor-single-select` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-27ab7a17cb7bd379f0a8ab153c8f46696a5549987eef0e0407c1c422cb4eb0eaL1-R89))
  * `sw-condition-unit-menu` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-e7859280f79b025b5ff89b4626c220bd546a00e9e31384fd6b447259f0a5eab8L1-R65))
  * `sw-hidden-iframes` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-de1f464b8ab6774ed0b5a59aa573009112b6d836a7722bb43472ac50f418c4e4L1-R13))
  * `sw-modals-renderer` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-3c6360cd3370e2e625335cbf6d0d23371afc02f66d8883e36f811e6133d032b9L1-R37))
  * `sw-settings-usage-data-intro` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-0a1c0b25a7b62430ff63333b4b5c4c03c52334649a4ea231df3ebe1cb91a639bL1-R20))
  * `sw-settings-usage-data-modal` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-93e73b3aa09da841c76cf2f84add3de8e91e89dcd7866c5749f721636f06d026L1-R47))
  * `sw-external-link` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-f8d3f17df76949060106238a37223101b3db23c0844af1e4dec2ead91a0550feL1-R31))
  * `sw-license-violation` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-54407514f4042c4a2ae6dcebf8cbe8c8c06814303536648903fdea74389289f7L1-R129))
  * `sw-time-ago` ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-f5f3f80b36ef713d0babad3f84e254ed670e3cb28157342424905a28eaf2c454L1-R8))
*  Add empty block `sw_bulk_edit_product_description` to `sw-bulk-edit-product-description.html.twig` for future use ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-d3c14ecfbeec11478dcd9b1cab9ecf774eb241207bd2645d30005a6a1569ff06R1-R2))
*  Add block `sw_category_detail_custom_entity` and fix missing closing tag in `sw-category-detail-custom-entity.html.twig` to allow extending or overriding the custom entity rendering logic ([link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-3907b54b011197e32a3229e599952086c515e8030f0fc0acf0c2bae2ef08462cL1-R9), [link](https://github.com/shopware/platform/pull/3116/files?diff=unified&w=0#diff-3907b54b011197e32a3229e599952086c515e8030f0fc0acf0c2bae2ef08462cL46-R65))

### CODE REVIEW

**Comment by jleifeld** [comment]
Hey Joshua,

I wanted to express my appreciation for your effort. Thank you!

However, we've made a decision to intentionally remove these blocks. Just adding one big block around the entire component doesn't address the main issue. Let me elaborate with an example: What if two plugins override the component? In such a scenario, we need to ensure that both plugins continue to work seamlessly without any conflicts. Simply enclosing the component in a single block doesn't provide a solution to this issue. The only solution for the shop owner is then uninstalling one of the plugins. And this is not a viable solution if both plugins are needed.

Taking these factors into account, we have decided that it would be best to close this pull request. Your effort is truly appreciated, and we encourage you to continue contributing to our project. If you have any further ideas or suggestions, please feel free to share them with us.

**Comment by JoshuaBehrens** [comment]
@jleifeld thank you for pointing out that decision. I am aware of that decision and I do not like it. Let me explain why:

> we need to ensure that both plugins continue to work seamlessly without any conflicts

No you don't. You can add these entrypoints without making them public API. It would eventually still help me as a project owner to at least alter your component's look and feel.

Getting to the other issue for the custom fields on units: I want to add a custom field set renderer on the unit detail page. This does not work as there is not a single block. As the inheritance forces an extends on the twigjs templates I technically have to remove the admin component and register a new one. I did not find a good way to remove any registered component. So I have to change the point where this unit detail page component is used. It is used as a reference in a route. Ok, now I have to get into the Vue router and replace the route, which is not ezpzly done for someone, that does not know how Shopware admin modules interfere with Vue routes. This raises the bar to simply exchange a components HTML look and feel by so much, that even as a project owner (not community store plugin dev) I am fighting to alter just a little component.

What kind of a framework is this, which I cannot bend it to my needs without core-hacking/monkey-patching? Even without the eco-system around it?

**Comment by jleifeld** [comment]
> I am aware of that decision and I do not like it

I understand that you're aware of the decision and that you're not happy about it. It's important for us to consider different perspectives and understand that while the decision might be valid in some cases, it could potentially lead to other problems in different situations. Let me share an example to illustrate this further: Imagine an agency making alterations to a private component for a customer. Later, when the shop gets updated, it stops working because the changes aren't respected in the override. In such cases, the shop owner often blames Shopware first, assuming that the update broke their shop. This leads to contacting our support team, investigating the issue, realizing it's related to a private override, reporting it back, and then the shop owner needs to contact the agency. As you can see, this whole process incurs additional time and expenses for the shop owner, the agency, and even Shopware itself.

> No you don't. You can add these entrypoints without making them public API. It would eventually still help me as a project owner to at least alter your component's look and feel.

I hear your point, and it's true that adding entry points without making them public API could be beneficial for you as a project owner to customize the look and feel of the component. If there's a need to alter private components and change the private API, one suggestion would be to fork the platform and make your changes there. This way, when an update is released, you can rebase your changes to the latest trunk release and also identify any code conflicts that may arise. But opening the private components in general is not wanted.

> Getting to the other issue for the custom fields on units: I want to add a custom field set renderer on the unit detail page. This does not work as there is not a single block. As the inheritance forces an extends on the twigjs templates I technically have to remove the admin component and register a new one. I did not find a good way to remove any registered component. So I have to change the point where this unit detail page component is used. It is used as a reference in a route. Ok, now I have to get into the Vue router and replace the route, which is not ezpzly done for someone, that does not know how Shopware admin modules interfere with Vue routes. This raises the bar to simply exchange a components HTML look and feel by so much, that even as a project owner (not community store plugin dev) I am fighting to alter just a little component.

I understand your issue with the custom fields in the units module. It's definitely an issue which needs to be fixed. Creating an issue for this or submitting a PR, as you have already done, is the appropriate way to handle such situations. Then every shop owner benefits from it by having the custom field set renderer in the unit modoule.

> What kind of a framework is this, which I cannot bend it to my needs without core-hacking/monkey-patching? Even without the eco-system around it?

We know that some developer want to be able to modify each single area in the product. But we can't allow complete flexibility and modification in every corner of the code because this leads to several other issues. We strive to provide as much extendability and flexibility as possible while maintaining a balance between stability, development speed, and maintainability.

**Comment by JoshuaBehrens** [comment]
@jleifeld  I am confused https://github.com/shopware/shopware/commit/82abff15e679c50c02e114867526a9883d934dca

I thought stuff like this is not happening anymore. The exact reason this PR is blocked off, is the reduce of public API of twig blocks to at least get into a component at all. Now you (as in Shopware AG) add a twig block for plugin vendors where you already have twig blocks and in theory would not need one?!?

**Pull request closed without merging**
