### PR TITLE
feat: set version constraint for flysystem to ^3.10.3

### PR DESCRIPTION
**Pull request by tinect**
### 1. Why is this change necessary?
Currently, flysystem itself is just installed with maximum version of 3.10.4 (<3.11.0), but the adapters are at 3.15.0

### 2. What does this change do, exactly?
Set constraint to `^3.10.3`

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

copilot:summary

copilot:walkthrough

### CODE REVIEW

**Comment by mitelg** [comment]
please also adjust `src/Core/composer.json`

**Comment by ghost** [comment]
Hello,

thank you for creating this pull request.
I have opened an issue on our Issue Tracker for you. See the issue link: https://issues.shopware.com/issues/NEXT-28659

Please use this issue to track the state of your pull request.

**Comment by shyim** [comment]
Thanks!

**Comment by tinect** [comment]
You're welcome 😽

**Pull request closed without merging**
