### PR TITLE
NEXT-0000 Fix skeleton in sw-settings-shipping-detail page

### PR DESCRIPTION
**Pull request by janpetto**
### 1. Why is this change necessary?

In [this commit](https://github.com/shopware/shopware/commit/c77e64448804bd579311159352f1e0321cd866e7#diff-edfe7fa224d7fb67d37b34592094de8bc9ae8ccbf8a355ee0052bf31a69addf4) two `sw-skeleton` components were added to the `sw-settings-shipping-detail` with a `v-else` outside of the twig block that contains the dependent component. When a plugin overwrites the block and removes the contained component, or adds something below, the skeleton will permanently remain on the page.

### 2. What does this change do, exactly?

This change moves the `sw-skeleton` component inside the twig block that contains the dependent component.

### 3. Describe each step to reproduce the issue or behaviour.

Overwrite the `sw-settings-shipping-detail` page and remove the `sw_settings_shipping_detail_tax_cost` block or the `sw_settings_shipping_detail_price_matrices` block. E.g.:

```twig
<!-- sw-settings-shipping-detail-override/sw-settings-shipping-detail.html.twig -->
{% block sw_settings_shipping_detail_tax_cost %}
{% endblock %}

{% block sw_settings_shipping_detail_price_matrices %}
{% endblock %}
```
```js
import template from './sw-settings-shipping-detail.html.twig';

Shopware.Component.override('sw-settings-shipping-detail', {
    template
});
``` 
This will result in two sw-skeleton components that remain indefinetly.

### 4. Please link to the relevant issues (if any).

[Relevant Issue](https://issues.shopware.com/issues/NEXT-28908)
[Relevant Commit](https://github.com/shopware/shopware/commit/c77e64448804bd579311159352f1e0321cd866e7)

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Bird87ZA** [comment]
Hi @janpetto ,

Thanks for the PR.

I don't see the need for moving the block. Moving this block, could lead to render issues in Vue. `sw-skeleton` is also important and should not be removed.

Can you maybe explain why you want to remove the component? Also, why not just do something like this, which will achieve the same result, but doesn't break other plugin overrides.

```vue
{% block sw_settings_shipping_detail_tax_cost %}
    <div v-if="true" style="display: none;"></div>
{% endblock %}
```

**Comment by janpetto** [comment]
Hi @Bird87ZA,
we don't want to move the block but simply hide the contents for some specific custom shipping method. With our usecase, some configuration options from the `sw-settings-shipping-detail` page simply do not make sense semantically, and we want to hide them. The reproduction example from my original message is just a simplified example.

The current implementation leaves a broken sw-skeleton component with a `v-else` that does not belong to any `v-if`. Your proposed solution would only work as long as no other plugin overrides the block and inserts something new. The following example would also break the page and leave the sw-skeleton:

```twig
{% block sw_settings_shipping_detail_tax_cost %}
    {% parent %}
    <div>Some additional HTML by another plugin</div>
{% endblock %}
```

**Comment by jleifeld** [comment]
> The following example would also break the page and leave the sw-skeleton:
> 
> ```
> {% block sw_settings_shipping_detail_tax_cost %}
>     {% parent %}
>     <div>Some additional HTML by another plugin</div>
> {% endblock %}
> ```

This example is a anti-pattern and not possible. The Vue Compiler would throw an error for the skeleton that `v-else` is only possible after a condition.

What other plugins would do is this:
```twig
{% block sw_settings_shipping_detail_tax_cost %}
    {% parent %}
    <div v-else-if="someMethod">Some additional HTML by another plugin</div>
{% endblock %}
```

And then the proposed solution with `<div v-if="false">` will not break the plugin, the core and the Vue compiler can compile the component which is then still semantically correct.

**Comment by janpetto** [comment]
Hi @jleifeld, thanks for your comment.

> This example is a anti-pattern and not possible. The Vue Compiler would throw an error for the skeleton that `v-else` is only possible after a condition.

I thought the same but we only noticed the "left-over" skeleton because of this exact pattern, and the Vue compiler did not throw any error. Maybe this is because of our setup or because the preceeding component also contains a `v-if`. The referenced commit looked like an accidental change to me, where the `<sw-skeleton v-else />` should have been inside the block. If this is the intended behaviour, I understand why my proposed change would break other plugins that have already implemented an overwrite of this block.

**Comment by Bird87ZA** [comment]
Hi @janpetto ,

I'm going to close this PR. Feel free to comment here if you feel the answer provided isn't sufficient.

**Pull request closed without merging**
