### PR TITLE
Add composer name to `plugin:list` output for quicker access

### PR DESCRIPTION
**Pull request by m-waes**
### 1. Why is this change necessary?
For convenience. Often times, I want to `composer remove` a plugin but first I need to check if it is installed or not. And if I'm running `bin/console plugin:refresh`, why not make the composer name copy pastable from there.

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by MelvinAchterhuis** [comment]
I like the idea, however on my Macbook it breaks the layout because the table content is to wide:

image

I've had issues in the past with ridiculously long labels from store plugins, so we just cap the label at max 40 characters:

```
--- /vendor/shopware/core/Framework/Plugin/Command/PluginListCommand.php
+++ /vendor/shopware/core/Framework/Plugin/Command/PluginListCommand.php
@@ -86,7 +86,7 @@
 
             $pluginTable[] = [
                 $plugin->getName(),
-                $plugin->getLabel(),
+                mb_strimwidth($plugin->getLabel(), 0, 40, '...'),
                 $plugin->getVersion(),
                 $pluginUpgradeable,
                 $plugin->getAuthor(),
```

**Comment by m-waes** [comment]
What's your suggestion? I could add your character cap in this PR, if that would be acceptable.
Or do you think think my PR can be closed? For me personally the label is irrelevant, I'd rather have the composer name. If it's a dead end here, I'll likely composer patch this for my projects.

**Comment by shyim** [comment]
the character cap would be nice

**Comment by m-waes** [comment]
Added the character cap 👍

**Comment by shyim** [comment]
Thanks! :)

**Pull request closed without merging**
