### PR TITLE
Add E2E test for manufacturer filter

### PR DESCRIPTION
**Pull request by rogoit**
Co-authored-by: Tobias Struckmeier <tobmaster@users.noreply.github.com>
Co-authored-by: Priyanka Kore <piyukore06@gmail.com>
Co-authored-by: Ramona  Schwering <leichteckig@users.noreply.github.com>

### 1. Why is this change necessary?
Because you need a test for manufacturer

### 2. What does this change do, exactly?
Add a new test

### CODE REVIEW

**Comment by J-Rahe** [comment]
waiting for replacement of demo-data.

**Comment by rogoit** [comment]
Hi @J-Rahe ,

thx for review and passion. Should I get the manufacturer name with a callback and do the assertion values dynamic? So far I do not know how I can help here.

See you
Roland

**Comment by J-Rahe** [comment]
@rogoit, sorry to confuse you. @leichteckig wanted to continue on this, i thought you were informed.

**Comment by rogoit** [comment]
@J-Rahe no problem. I want to do more on this nice project. Maybe you want to join our live coding sessions ;)

**Comment by leichteckig** [comment]
@rogoit Sorry I thought I was clear on the test data issue yesterday. 🙇‍♀️  We don't use the generated demo data in our test suite - we create it for the tests specifically. So there are neither products nor manufacturers in the test by default. 

If you like to catch up yourself, you can do it like this: We use API requests to [create test data](https://developer.shopware.com/docs/guides/plugins/plugins/testing/end-to-end-testing#handling-test-data). In our case, we need to create a product with has an association to that manufacturer. The best case is we only need to use the command `createProductFixture` to get there. For our test, you would use it like that:
```
  beforeEach(() => {
      cy.setToInitialState()
          .then(() => {
              // Takes care on API authorization
              cy.loginViaApi();
          })
          .then(() => {
              // Creates a product with manufacturer
              return cy.createProductFixture();
          })
          .then(() => {
              cy.visit('/');
          });
  });
```
If you need some information on this hook you know how you can reach me best. 🙂  Of course, we might need to adjust the names we assert on based on the default product fixture or create a new [fixture file](https://docs.cypress.io/api/commands/fixture).

**Comment by leichteckig** [comment]
@rogoit Would you like to squash and rebase our MR? 🙂  Plus, we need to add the changelog. More information in this can be found [here](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md).

**Comment by leichteckig** [comment]
Added a changelog now, so we might only need to squash the commits. 🙂

**Comment by rogoit** [comment]
Hi, 

and thx all for your help to get our first PR done. So I do not know where I can answer the questions. I do it here and hope it helps.

Why is this change necessary?
The test will help to get a wider application test coverage for the filter on the product overview page. With this initial test we can go forward to do more validations for the correct working.

What does this change do, exactly?
The tests opens the startpage and click the dropdown of the manufacturer. Here it select "Shopware" and check if there are less products. This will validate the working of the filter. Also the test assert that the manufacturer of the filtered item has the selected brand.

Can I do anything else for you?

See you
Roland

**Comment by J-Rahe** [comment]
Hey @rogoit, your PR was just [merged](https://github.com/shopware/platform/commit/4a5bf59f543fd02e4902d1b0d01b4f868de9753c) : ) Thanks!

**Pull request closed without merging**
