### PR TITLE
Fix silencing flow errors in dispatcher

### PR DESCRIPTION
**Pull request by maximilianruesch**
### 1. Why is this change necessary?

The change from #3398 is seemingly insufficient to uncover flow errors during transactions, thus we need to fix the errors described in the referenced PR on a more general level. This tremendously helps with debugging flow errors inside transactions during e.g. order creation.

> [!NOTE]  
> This fix (or rather the `throw` itself) can also be hidden behind a feature flag for debugging purposes. This PR does not yet implement a feature flag as we believe this error handling should always be active.

### 2. What does this change do, exactly?

Fix the `FlowDispatcher` to not silence errors that happen during flows.

### 3. Describe each step to reproduce the issue or behaviour.

See #3398

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 9a71421</samp>

This pull request fixes a bug that caused flow errors to be silenced in the `FlowDispatcher` class. It adds error handling and reporting logic to the class, a new error code and constructor to the `FlowException` class, and a new test case and changelog entry for the fix.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 9a71421</samp>

*  Add a changelog entry for the fix ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-4f48dbe002c818b455628fae3de0201d35489872f0d5a93d5bad6308250e3902R1-R10))
*  Import `FlowException` class in `FlowDispatcher` ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-de82052c573f9887be73ed5037723d4406f0e968a5ad1596d6c24e864ab965deR9))
*  Initialize arrays to store exceptions and flow names by flow id ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-de82052c573f9887be73ed5037723d4406f0e968a5ad1596d6c24e864ab965deL127-R132))
*  Catch and store different types of exceptions during flow execution ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-de82052c573f9887be73ed5037723d4406f0e968a5ad1596d6c24e864ab965deR145), [link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-de82052c573f9887be73ed5037723d4406f0e968a5ad1596d6c24e864ab965deL149-R160))
*  Throw a `FlowException` with `errorsDuringExecution` method if any exceptions are stored ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-de82052c573f9887be73ed5037723d4406f0e968a5ad1596d6c24e864ab965deL149-R160))
*  Add `ERRORS_DURING_EXECUTION` constant and `errorsDuringExecution` method to `FlowException` class ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-fb7cc26f1a87e6714a992633d3ba3db0586b4fba2aaf8d84bed74beb415509eeR14), [link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-fb7cc26f1a87e6714a992633d3ba3db0586b4fba2aaf8d84bed74beb415509eeR25-R62))
*  Import `ExecuteSequenceException` and `FlowException` classes in `FlowDispatcherTest` ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-369fe45ec3a17e490079718007e02bda98da3b2f8c3946a33e424b54ac747ebcR16-R17))
*  Add a test method to simulate and assert the expected behavior of `FlowDispatcher` when multiple flows fail ([link](https://github.com/shopware/shopware/pull/3458/files?diff=unified&w=0#diff-369fe45ec3a17e490079718007e02bda98da3b2f8c3946a33e424b54ac747ebcR259-R316))

### CODE REVIEW

**Comment by AydinHassan** [comment]
hey @maximilianruesch - thanks for the PR. We had a discussion in the team earlier and we decided that we would prefer not to throw more exceptions here, particularly because flows can be triggered in numerous manners, not necessarily a person interacting with the site. So in its current form it's not something we would likely accept, sorry for that.

If this is solely about debugging we had the idea that the developer experience could be improved by utilising the Symfony Profiler. It would be nice to have a collector for flow events and the errors that might occur within them. These results would then be displayed in a panel in the debug bar.

What do you think? Is it something you would be interested in working on?

[Creating a Data Collector](https://symfony.com/doc/current/profiler.html#creating-a-data-collector)
[Shopware Custom Collector](https://github.com/shopware/shopware/blob/trunk/src/Core/Profiling/Subscriber/ActiveRulesDataCollectorSubscriber.php)

**Comment by maximilianruesch** [comment]
Hey @AydinHassan, thanks for your comment.

The debugging improvement from this PR would in particular benefit production systems. In such environments, running failing flows inside transactions (no matter the trigger of the flows) can cause very opaque error messages (as mentioned in #3398). A flow collector for the profiler would only marginally help in production environments, for two reasons:
1. The profiler itself (with all other symfony tooling) is active, when `APP_ENV` is set to `dev`. In production systems, access to the profiler should not be generally available because of heavy security implications (e.g. access to database credentials). While the profiler can be activated only for certain IPs (with some hacks in the Shop files), this requires access to the FTP server and is harder to facilitate for requests devices make outside of a regular desktop PC.
2. Even if the profiler may be accessed, this is usually out of range / too technical for most shop users. With the error messages described in this PR i think shop users may be able to read out the affected flows quickly, saving time during support requests and maybe even resolving the issue themselves.

I agree that for development environments, a profiler collector would help to debug things a fair way. However, guessing that the original error described in #3398 stems from failing flows is a long shot (i.e. from the test "Transaction marked for rollback only"). So even for development systems and in particular for production systems, this seems insufficient for me.

**Comment by AydinHassan** [comment]
@maximilianruesch forgive I am not totally familiar with this code and haven't dug very deep, but wouldn't the log be your first port of call here in production? Or is that error not descriptive enough ? Is there something we can improve there?

**Comment by maximilianruesch** [comment]
The issue with the error message is not that there is *no* log (because there is), but the issue is that the resulting error message shown when a failing flow is executed *inside* a transaction is not nearly descriptive enough to suggest any relation to the logged error or even failing flows.

It would be great if we could provide any way (even if per toggle, then it helps at least in support) of just throwing the error messages to the outside. This throwing and not silencing them can then result in the correct transactions being rolled back, retried or whatever applies.

I understand the topic might be a bit confusing since the connection to nested transactions might not be immediately clear. I again suggest you get familiar with #3398 or tell me if you have any questions about it.

**Comment by AydinHassan** [comment]
@maximilianruesch just a heads up, we haven't forgotten about this and will be taking a look soon. We want to investigate a little more.

**Comment by AydinHassan** [comment]
hey @maximilianruesch sorry for the delay. We finally got around to investigating the issue and proposed fix. We discussed another possible solution and wondered if you might be interested in working on it? Otherwise we would tackle it in our backlog.

Basically what we thought about was moving the transaction logic up in to `\Shopware\Core\Content\Flow\Dispatching\FlowDispatcher` so that each action does not have to worry about implementing this complicated error handling. 

To further explain, we would introduce a `TransactionalAction` interface that would serve purely as a marker. Actions can implement this interface to signal that they should be run in a transaction.

`\Shopware\Core\Content\Flow\Dispatching\FlowDispatcher` would then handle starting, stopping and rolling back the transaction, if the action implements it. We would also introduce a `RollbackActionException` which the action can throw. The `FlowDispatcher` would catch that specific exception only, do some logging, report the errors and move on.

What do you think? Would it cover your scenario?

**Comment by maximilianruesch** [comment]
Hey @AydinHassan, thanks for working on this!

The changes to unify the transaction handling and move it to the `FlowDispatcher` in general sound great, since this way specific actions are not able to (mis-)implement any of this transaction handling and we have a single point where we could debug and fix stuff in the future.

However, the proposed changes concerning the `RollbackActionException` would not cover our scenario. Consider the following:

1. A transaction is opened somewhere
2. Some code is executed that triggers a flow (e.g. a state transition of an entity)
2.1 The `FlowDispatcher` executes a flow and notices that an action implements the `TransactionalAction` interface
2.2 The `FlowDispatcher` opens an inner transaction
2.3 The `FlowDispatcher` executes the action
2.3.1 The action triggers (e.g. through subscribers) something that opens a third nested transaction
2.3.2 The third nested transaction is rolled back for some unimportant reason and an exception is thrown
2.4 The inner transaction of the `FlowDispatcher` is now marked as rollback only (since the connection does not support real nested transactions) and a `RollbackActionException` is thrown by the action catching the inner exception
2.5 The `FlowDispatcher` catches the `RollbackActionException`, rolls back the transaction, logs the error, and **silently** moves on.
3. The outer transaction is marked as rollback only, ever since the third nested transaction was rolled back
4. Since the `FlowDispatcher` **silently** caught the `RollbackActionException`, the outer transaction does not notice that something failed and tries to commit. The commit fails as the transaction/connection is marked as rollback only. The original error that caused this as well as the `RollbackActionException` are not visible. Since the outer transaction is unaware of any errors, it can not even know that the exception was thrown during flow execution.

The problematic step is 2.5 where the `RollbackActionException` is caught silently. To actually cover our scenario, the `FlowDispatcher` must rethrow the esception in certain situations. We could replace step 2.5 with the following:

2.5'.1 The `FlowDispatcher` catches the `RollbackActionException`, and logs the error and rolls back the transaction
2.5'.2 IF the current connection is marked as rollback only, outer transactions exist, so the outer transactions have to know the original error to rollback themselves. The `FlowDispatcher` rethrows either the `RollbackActionException` or its wrapped exception.
2.5'.3 ELSE the current connection is not marked as rollback only, so no outer transactions exist and thus no outer transactions need to know any errors. The `FlowDispatcher` can silently report the error somewhere and move on.

> [!Note]
> The check in 2.5'.2 for outer transactions via the attribute "rollback only" can alternatively be replaced by checking the current transaction nesting level of the connection. Both implementations are equivalent.

Let me know what you think of this. I might be interested in contributing to this, but in the foreseeable future i wont be able to contribute code to this due to time restrictions. I would however gladly review any changes and verify they fix our scenario.

**Comment by AydinHassan** [comment]
@maximilianruesch thanks for the additional info, your suggestion makes sense and we would incorporate that. I imagine we won't get to this before the Christmas holidays - let's catch up in the new year and see how we want to proceed.

**Comment by AydinHassan** [comment]
@maximilianruesch I'll have a go at it now :)

**Comment by AydinHassan** [comment]
@maximilianruesch just curious because I noticed that nesting transactions without save points is deprecated in [Doctrine](https://github.com/doctrine/dbal/pull/5383). Which database are you using that doesn't support save points or rather why do you enable nested transactions without save points?

**Comment by maximilianruesch** [comment]
> Which database are you using that doesn't support save points or rather why do you enable nested transactions without save points?

No database **I am using** does not support nested transactions with save points. However, Shopware does not by default enable nesting transactions with savepoints, so when setting up a fresh shop we do not have nesting with savepoints enabled. The default behaviour (of Doctrine and Shopware) right now is that they are disabled, as Doctrine and thus Shopware might run on databases not supporting savepoints.

Now Shopware can arbitrarily decide to turn nesting with savepoints on (which happens anyways when upgrading to a Doctrine version that does not support nesting without savepoints anymore). Then all would be fixed and we wouldnt need to worry. This could for example happen with 6.6 major break if wanted.

As I figured that Shopware might want to keep supporting these systems, this PR was created to find a workaround even for systems without savepoints. I acknowledge that the communication on this idea might have been suboptimal.

**Comment by AydinHassan** [comment]
No I don't think it's been sub-optimal and we appreciate your insight and fast responses. In the end we will produce better quality software and that's what matters. I will investigate whether the databases we support can work with save points correctly and what the adverse effects of enabling save points by default might be. I think the ship has sailed for 6.6 so this fix will still be useful imo but it will be good to plan for the future and document our findings :)

**Comment by AydinHassan** [comment]
hey @maximilianruesch I will close this for now, I am still working on the rework, and I will open a PR here and ping you on it when it's ready for review. hope that's okay :)

**Comment by maximilianruesch** [comment]
Hey @AydinHassan thats fine. Do you have a progress report on the rework? In any case, looking forward to your mention.

**Comment by AydinHassan** [comment]
@maximilianruesch yep, it's almost finished, we had to postpone with the 6.6 release but I just picked it up again yesterday and hopefully will have it ready for review in a few days

**Comment by AydinHassan** [comment]
hey @maximilianruesch here is the current state of the proposal: https://github.com/AydinHassan/shopware/commit/ccb6e28ea368aa242750209780ae0414504e96da

It's been through a few rounds of review now and I would also appreciate your feedback :)

**Comment by maximilianruesch** [comment]
Hey @AydinHassan thanks for the diff. I have not yet set up a SW6.6 project, but looked at your diff and the general direction of the changes looks great! Thanks for your effort so far.

I noticed that we might still be missing an error in some cases. Consider the following:

1. The `SetOrderStateAction::transitState` throws some exception other than a `StateMachineException`, which is not handled by the catch block and thus not wrapped in a `TransactionFailedException`.
2. The `FlowExecutor` does not wrap this exception in a `FlowException::transactionCommitFailed` but still wraps it in an `ExecuteSequenceException`
3. The `FlowDispatcher` does not rethrow the exception since it is not wrapped in a `FlowException::transactionCommitFailed`
4. Still bad luck for debugging

In this line of reasoning, one could replace the `SetOrderStateAction` by any other possible action. Since they could also be created by plugin developers, we need to tackle this on another level. One possibility would be that the `FlowExecutor` wraps *every* `Throwable` in a `FlowException::transactionCommitFailed` when rolling back the transaction. This would also ensure that type errors (not that uncommon in production PHP) would be included.

Also: Wen skimming over the changes i noticed that the `$context->removeState(self::FORCE_TRANSITION);` in the `SetOrderStateAction` is not included in a `finally` block anymore. Is this intentional? Imo we should always remove any state that we added (especially if its force-transition), regardless of exceptions / errors thrown.

**Comment by AydinHassan** [comment]
hey @maximilianruesch `transitState` does not throw any other exception though. If it's changed the catch should be updated. I'm not sure that's the direction we want to go in because that can be picked up with static analysis and we want to catch exceptional cases rather than programming bugs. I suppose they are two separate problems though. 
Regarding the last bit, yeah that's a bug. I will have a think about the first bit.

**Comment by maximilianruesch** [comment]
> we want to catch exceptional cases rather than programming bugs
Sadly, programming bugs occur often especially in custom made actions (`transitState` does not explicitly throw other exceptions than `StateMachineException`, but since it uses the `connection`, one can assume it *can* throw other exceptions). You can not rely on everybody using similar static analysis to Shopware and thus cannot rely on every exception that can be thrown being caught.

Imo the cost of encountering such a programming bug and them circumventing all of the enhanced error handling is higher than just handling them too. If such a programming bug were to occur, we would be in the hard-to-debug situation often described above all over again, even if the causing plugin / action was not our own (and thus technically not our responsibility).

**Comment by AydinHassan** [comment]
@maximilianruesch added in https://github.com/AydinHassan/shopware/commit/97af21e9d5472ef25cdd9857324000b18949cc68 :)

**Comment by maximilianruesch** [comment]
@AydinHassan Thanks for implementing this! I think you missed one bit though: In [these lines](https://github.com/shopware/shopware/compare/trunk...AydinHassan:shopware:next-33086-flow-dispatcher-transactions#diff-de82052c573f9887be73ed5037723d4406f0e968a5ad1596d6c24e864ab965deR188-R192) the previous error is only rethrown if it occurred during a commit of a transaction. But since general errors are now wrapped in a "transaction aborted" (see [this](https://github.com/shopware/shopware/compare/trunk...AydinHassan:shopware:next-33086-flow-dispatcher-transactions#diff-bad3242503f09dd8a1923c6db8ad12ec8c80b69edde392af80ff6e0320744dc7R156-R162) and [this](https://github.com/shopware/shopware/compare/trunk...AydinHassan:shopware:next-33086-flow-dispatcher-transactions#diff-fb7cc26f1a87e6714a992633d3ba3db0586b4fba2aaf8d84bed74beb415509eeR32-R51)), they are not rethrown and thus silenced. I think just removing this condition on the previous error being "some type of error" is the best in this case.

I will try to integratively test this with a fresh 6.6 setup soon.

**Comment by AydinHassan** [comment]
@maximilianruesch nice good catch, let me know how it goes with the tests then I can get it merged and write up some documentation :)

**Comment by maximilianruesch** [comment]
@AydinHassan I could test this in the meantime and it seems to be working just fine. My internal test, previously failing with "Transaction commit failed [...] marked as rollback only" now fails with "Flow action transaction was aborted and rolled back. Exception: Transaction failed because an exception occurred."

One minor thing: This exception (or rather its nested exception) actually contains the reason this transaction failed / it was rolled back as the previous exception, but its not contained in the message. Compared to the previous situation, this is already a great step, however it would be great to have this in the regular exception message as well. We can achieve this by modifying the `TransactionFailedException` just like the `FlowException` and just appending the previous message:

image

With this modification, the final exception message comes out to: "Flow action transaction was aborted and rolled back. Exception: Transaction failed because an exception occurred. Exception: The StateMachine named "order_delivery" was not found."

It would really be great if you could fix this! Otherwise, your changes look great as already mentioned and from my side this can be merged! Thank you once again for your ongoing effort in this matter 💙

**Comment by mitelg** [comment]
:grin:

**Comment by maximilianruesch** [comment]
Minor caveat i just noticed: Imagine you are inside a transaction. When a Flow Action without the new interface triggers something that opens a nested transaction (like a DAL subscriber), throws inside it, rolls it back, the new handling for exceptions will not be triggered since the action does not implement the new interface and thus no commit failed.

Imo we can remove the `$e->getPrevious() !== null && $this->isCommitFailedError($e->getPrevious())` from the `FlowDispatcher` and always rethrow, when we are in a nested transaction.

Sorry for the confusion @AydinHassan 😅

**Pull request closed without merging**
