### PR TITLE
feat: forward wishlist instead of removing history in WishlistLocalStoragePlugin

### PR DESCRIPTION
**Pull request by tinect**
### 1. Why is this change necessary?
It hurts UX to not do so :-)

### 2. What does this change do, exactly?
Changed `location.replace` to `location.href` in WishlistLocalStoragePlugin

#### Requirements
- do not allow wishlists cookie
- be not loggedin
#### Steps
- try adding product to wishlist (being forwarded to login)
- you don't want to login, so use history back in browser
- being somewhere, but not at the product
- leave shop annoyed
- perform tableflip

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 9ea4082</samp>

This pull request fixes a bug in the wishlist plugin that removed the browser history when redirecting to the login page. It changes the `local-wishlist.plugin.js` file to use `window.location.href` instead of `window.location.replace` and adds a changelog entry for the change.

### <samp>🤖 Generated by Copilot at 9ea4082</samp>

*  Add a changelog entry for the pull request ([link](https://github.com/shopware/platform/pull/3338/files?diff=unified&w=0#diff-0847cc918aa6def682baa1cab12adb27e6ddc60b5ff114dc9b8049e005634655R1-R11))
*  Change the `add` method of the `WishlistLocalStoragePlugin` to forward the current URL as a parameter to the login page instead of replacing the browser history ([link](https://github.com/shopware/platform/pull/3338/files?diff=unified&w=0#diff-d4343bc757cfaa3f0d078aa2489ad46a395a31fed5e5e85f0a8e685ec6fa2c61L26-R26))

### CODE REVIEW

**Comment by tobiasberge** [comment]
Hi @tinect, thanks for your contribution. 👍 

I can also verify this. When attempting to add to wishlist on the detail page and using browser back I end up in the listing instead of the detail page. Of course I did the table flip. 😆

**Comment by tobiasberge** [comment]
Hi @tinect,

I tested this locally and the fix itself works like expected. I get redirected to the previous page when I am on the login page and use the browser back function.

However, I discovered that the "Add to wishlist" button is in a weird state after using browser back. It is in a state as if the product was added to the wishlist: "Remove from wishlist". Which it isn't because I'm not logged in and haven't accepted the cookie. I also cannot use the button anymore and clicking it does nothing. Only after a manual page reload the state is correct again with "Add to wishlist".

I thought that maybe the product was accidentally added to the storage, but debugging the `AddToWishlistPlugin.initStateClasses` it seems to have the correct state and `this._wishlistStorage.has(this.options.productId)` returns false as expected. And the button should be in the correct state.

Can you also confirm this behaviour? I was wondering if this could be even more confusing, because to the customer it looks like the product was added to the wishlist, while in reality nothing actually happened.

I tested in Chrome and Firefox, also in incognito mode with disabled cache.

**Comment by tinect** [comment]
@tobiasberge Oh, I see :-( yes, I'm able to reproduce it.

Damn, there might be more work to fix it :-( do you have an idea?

**Comment by lacknere** [comment]
The reason for that behavior is that location.href doesn't stop script execution. The return statement inside the add method does indeed stop any execution inside that method but if you have a look at where the add method is called from [(here)](https://github.com/shopware/shopware/blob/5c507419f47d351525e916f0bbb76ef4b59b5f66/src/Storefront/Resources/app/storefront/src/plugin/wishlist/add-to-wishlist.plugin.js#L82) you can see that the button state is changed right after, no matter if the product was successfully added or not. I'd suggest to return true on success and false on failure in both WishlistLocalStoragePlugin and WishlistPersistStoragePlugin add methods. Then use the returned value to conditionally update the button state or stop any further execution with another return statement.

**Comment by ssltg** [comment]
Thank you for your contribution @tinect in the meantime it was fixed by another commit.
https://github.com/shopware/shopware/commit/b300ae344a946a5e7c41024f924bdfa143fb12ff

**Pull request closed without merging**
