### PR TITLE
NEXT-00000 - Improve admin login session

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
- Currently, the `bearerAuth` token is always stored in administration as a session cookie. For this reason, the cookie may expire unpredictably as each browser may handle the lifespan of a session cookie differently
- Even if you use the `Stay signed in` it is only saved as a session cookie, so if the session cookie expires and you visit the site again later you will have to log in again (which is not really what a  `Stay signed in` checkbox should do)
- To fix all this unpredictable mess, this PR changes this behavior by storing the cookie differently depending on whether you used `Stay signed in` or not:
  - If you don't use `Stay signed in`, the cookie is now stored for the lifetime of the token (10 minutes) instead of a session cookie
  - If you use `Stay signed in`, the cookie is now stored for the lifetime of the `RememberMe` action (14 days) instead of a session cookie
- After this behavior change the cookie will be stored predictable for (10 minutes, updated from the lifetime of each refresh token) or (14 days, defined by the `RememberMe` action checkbox)

### 2. What does this change do, exactly?
* Added a unified `setRememberMe` function to `loginService`
* Changed `sw-inactivity-login` to use the unified `loginService.setRememberMe`
* Changed `sw-login-login` to use the unified `loginService.setRememberMe`
* Changed `loginService` to clear the token refresh timeout on logout
* Changed `loginService` to no longer unnecessary recreate the token refresh timeout
* Changed `setBearerAuthentication` in `loginService` to account for `rememberMe` time and switched from session cookie to a set expire time

### 3. Describe each step to reproduce the issue or behaviour.
- Login in to the administration with the `Stay signed in` checkbox
- Visit the site again later / Be unlucky that your session cookie expires

### 4. Please link to the relevant issues (if any).
- /

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by PheysX** [comment]
Any news on this one? 😆

**Comment by seggewiss** [comment]
Sorry for leaving this unatendettended for so long. I'm taking a look right away 🦭 
image

**Comment by seggewiss** [comment]
Sorry @akf-bw, but this gives us massive problems with our E2E setup. Until I figured out why this happens I'm unable to merge this.
I'm on it tho 😅 
CleanShot 2024-07-23 at 07 45 11

**Comment by seggewiss** [comment]
@akf-bw Resolved and merged 👍

**Comment by ghost** [comment]
@seggewiss Perfect, thank you! 💙

**Comment by PheysX** [comment]
Nice one!

**Pull request closed without merging**
