### PR TITLE
NEXT-39319 - fix: prevent current date output in product schema when release date is unset

### PR DESCRIPTION
**Pull request by StefanPilzLtd**
### 1. Why is this change necessary?
This update is necessary to fix a bug in the product schema markup where the current date was always displayed as the release date if no specific "release date" was set for a product. This behavior could mislead users and search engines, affecting the accuracy of the structured data used for indexing.

### 2. What does this change do, exactly?
The fix adds a conditional check to ensure that the "release date" is only displayed in the schema definition if it is explicitly set. If no release date is defined, no date will be output instead of incorrectly defaulting to the current date. This change modifies the buy-widget.html.twig template file and improves the accuracy of schema data.

### 3. Describe each step to reproduce the issue or behaviour.

- Open the Shopware frontend and navigate to a product without a defined "release date."
- Inspect the HTML schema markup on the product page.
- Observe that the current date is displayed as the releaseDate in the schema, despite no release date being set for the product.
- This issue occurs because the template does not check for the existence of a release date before outputting it in the schema data.

### 4. Please link to the relevant issues (if any).
GitHub Issue: [shopware/shopware#5324](https://github.com/shopware/shopware/issues/5324)

### 5. Checklist

- [X ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [X ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by StefanPilzLtd** [comment]
Just a quick note: I ended up with the same commit message twice because I committed the changelog and the modified file separately. This results in two commits with identical messages, but each one focuses on a different part to keep things organized.

**Comment by mitelg** [comment]
hey @StefanPilzLtd 

thanks for your contribution. please sign the CLA. 

the commits of you are squashed during import, so no need to separate them. also it is not really necessary on such small change :wink:

**Comment by StefanPilzLtd** [comment]
@mitelg 

I had already signed the CLA on November 3rd. On November 4th, the status here still showed "Pending — Contributor License Agreement is not signed yet." I tried signing it again, but the status remains "Pending." Before that, I clicked the "recheck" link multiple times, but nothing happened.

Screenshot 2024-11-05 011145

**Comment by mitelg** [comment]
@StefanPilzLtd  it seems that the GitHub user is not connected to the git user, you made the commits with

**Comment by tobiasberge** [comment]
Hi @StefanPilzLtd, your changes were merged to `trunk`: https://github.com/shopware/shopware/commit/5974ca9f57aee162aff865761ba62db7a99f1c02

Thank you for your contribution. 🎉

**Pull request closed without merging**
