### PR TITLE
Fix templates of components that extend components that have overrides 

### PR DESCRIPTION
**Pull request by hanneswernery**
### 1. Why is this change necessary?

Assume there are 3 administration components:

- "original component"
- "override component" that overrides the "original component",
- "extension component" that extends the "original component".

When using the "original component" in the administration, the template is correctly resolved (i.e. the override is applied). When using the "extension component" in the administration, the template is only resolved against the unresolved/raw template of the "original component" (i.e. the override is _not_ applied).
I attached a JS snippet in a `.txt` file which adds these demo components to the administration dashboard.

[extension-override-example.txt](https://github.com/pickware/shopware-platform-private/files/7346758/extension-override-example.txt)

### 2. What does this change do, exactly?

This PR fixes the resolving of the template of components that extend a component that have overrides.

### 3. Describe each step to reproduce the issue or behaviour.

Use the attached JS snippet to add the demo components to the administration dashboard. Open the dashboard in the administration.

#### expected behavior (override is applied in the extension)
Screenshot 2021-10-14 at 15 14 50

#### actual behavior (override is _not_ applied in the extension)
Screenshot 2021-10-14 at 15 30 31

### 4. Please link to the relevant issues (if any).

https://issues.shopware.com/issues/NEXT-17978

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Review by jleifeld — APPROVED** [review]
Looks really good 👍🏻

**Comment by jleifeld** [comment]
Can you have a look at the Jest tests? There are some failing tests. It would be good to have a look why these tests are failing.

**Comment by hanneswernery** [comment]
There was a hidden pass-by-reference/-copy bug left to fix. Should be working now @jleifeld

**Comment by hanneswernery** [comment]
Do you have any news about the state of this PR @jleifeld or @King-of-Babylon ? 🙂

**Comment by jleifeld** [comment]
You modified the existing tests. This will lead to a different behavior in component extending and overriding and could lead to breaks in several plugins. Can you have a look at this? The order of the plugin loading should be irrelevant so that it behaves in a predictable manner.

**Comment by hanneswernery** [comment]
> You modified the existing tests. .. could lead to breaks in several plugins

Yes, because the current tests ensure a wrong behaviour. "Wrong", because currently extensions do not consider overrides. Which is what this PR fixes. Hence, and also looking at the example (screenshots) of the PR description, this PR might cause changes to existing plugins.

> The order of the plugin loading should be irrelevant so that it behaves in a predictable manner.

My changes to the tests do not test or modify multiple plugin registration. So I don't quite understand what you mean by that.

**Comment by jleifeld** [comment]
Looks good. Can you do following two things?
- add major feature flag because the change is breaking
- add tests for different scenarios (changing register order, changing builds)

**Comment by jleifeld** [comment]
It was merged with Commit [8229f16ac7f6f213ba1ed90886fb329880123faf](https://github.com/shopware/platform/commit/8229f16ac7f6f213ba1ed90886fb329880123faf)

**Pull request closed without merging**
