### PR TITLE
Danish as default language in installer

### PR DESCRIPTION
**Pull request by wexotht**
### 1. Why is this change necessary?
The Danish market requires Shopware customers to be able to set the default language for their shop to Danish.

### 2. What does this change do, exactly?
Allows a user to set Danish as the default system language upon install.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-8602

This should also be merged to add the Danish flag: https://github.com/shopware/production/pull/110

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by J-Rahe** [comment]
Hey @wexotht, thanks for the PR : ) we will come back to you next week.

**Comment by wexotht** [comment]
@J-Rahe did you have time to look at this? :) Could we push to have it included in the monday release?

**Comment by mitelg** [comment]
@wexotht the release branch is split off two weeks before the release 😉 so for this PR it is already too late 🙈

**Comment by wexotht** [comment]
@mitelg ohh okay :) Will a review or some test / feedback happen this or next week anyway? If everything is okay we will patch our shops and start the huge migration process to Danish as the default language for all our customers

**Comment by wexotht** [comment]
@jakob-kruse what's the status of this one? :) Is there something that we need to correct or will this be included in the September release?
As far as I can see, the failing tests are not related to our changes

**Comment by jakob-kruse** [comment]
Hello @wexotht

Your contribution will most likely be included in the next release.

Your PR will now be reviewed and tested before being put through our internal extended test suite and review process.
We will keep you informed whether something has to be done by you or when the PR is merged

If you have any further questions, feel free to ask.

**Comment by jakob-kruse** [comment]
Hey, your contribution is now merged, thanks :blue_heart:

**Pull request closed without merging**
