### PR TITLE
Improve performance of CheapestPriceUpdater::update for products with many variants

### PR DESCRIPTION
**Pull request by jkrzefski**
### 1. Why is this change necessary?
I had a product with roughly 42.000 variants. Running `dal:refresh:index` was incredibly slow, so I had to make improvements. The child products were fast, but the parent took about **7.5 minutes** to update.

### 2. What does this change do, exactly?
In the method `\Shopware\Core\Content\Product\DataAbstractionLayer\CheapestPriceUpdater::update` there is this section:

```php
foreach ($container->getVariantIds() as $variantId) {
    $accessorQuery->execute([
        'accessor' => JsonFieldSerializer::encodeJson($this->buildAccessor($container, $variantId)),
        'id' => Uuid::fromHexToBytes($variantId),
        'version' => $versionId,
    ]);
}
```

And there is this line in the method `buildAccessor`:

```php
$rules = $container->getRuleIds();
```

As you can see, the call to `$container->getRuleIds()` is not dependent on the `$variantId` at all. But it is executed for every single variant of the product. The method took about 10 milliseconds on my machine, which adds up to 420 seconds. But it will return the same value for every iteration.

I got a small performance improvement from my refactoring of the method itself by avoiding the use of `array_unique`. That got me from 10 milliseconds per iteration to 7 milliseconds.

The real hero here is the memory cache property. That means, the method will only run once and return the same value for every subsequent iteration. That reduced the execution of `\Shopware\Core\Content\Product\DataAbstractionLayer\CheapestPriceUpdater::update` from roughly 427 seconds down to 6 seconds.

### 3. Describe each step to reproduce the issue or behaviour.

1. Have a product with 42.000 variants. (No advanced prices needed.)
2. Run `dal:refresh:index`.
3. When the process gets to the parent product, it will take a lot of time to progress. (After that, your MySQL server is likely to have gone away.)

### 4. Please link to the relevant issues (if any).

None.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by keulinho** [comment]
@jkrzefski great job figuring out the performance problems there! :blue_heart: :tada: 

Could you add a little changelog entry and describe the changes you did?
Also take a look at the linting error, it seems as there is some whitespace where we don't what it

**Comment by jkrzefski** [comment]
@keulinho Will this changelog be sufficient? Or should I go more into detail?

**Comment by keulinho** [comment]
@jkrzefski works for me. 

For the next time please don't merge the trunk branch into your PR, either rebase onto it or use the stale merge base. 
During importing we will automatically rebase your PR, but sadly our internal tool to import PRs does not handle merges that well :see_no_evil:

**Comment by keulinho** [comment]
Thanks again for your contribution! :blue_heart: 

Your changes were merged with a1f44ce0a996cb198baffdad1a19509ca97a46b6

**Pull request closed without merging**
