### PR TITLE
NEXT-00000 - Support webpack config ts

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
- For Shopware plugins where the storefront is written entirely in TypeScript, the webpack.config.js file is the only file without TypeScript support.
- This commit is a addition to https://github.com/shopware/shopware/commit/3326315c04215d232b1c7f364826260e1c1a110f

### 2. What does this change do, exactly?
- Changed the `getWebpackConfig` method in `BundleConfigGenerator` to also check for `webpack.config.ts` & `webpack.config.cts`

### 3. Describe each step to reproduce the issue or behaviour.
- Create a `webpack.config.ts` in the `app/storefront/build` or `app/administration/build` directory in your plugin

### 4. Please link to the relevant issues (if any).
- Addition to https://github.com/shopware/shopware/commit/3326315c04215d232b1c7f364826260e1c1a110f

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by tobiasberge** [comment]
Hi @akf-bw, thank you for your contribution.

You write webpack configs really in TypeScript? 😆 But if it is helpful too you, I see nothing agains supporting it. 

Have you tested this briefly? Does it work out of the box for you when executing the build/watcher scripts or did you encounter any issues?

**Comment by ghost** [comment]
@tobiasberge 0% JavaScript and 100% TypeScript in the GitHub "Language" section looks wonderful 😁

I tested it in my project and it works as long as you don't include TypeScript syntax. Since [require in webpack.config.js](https://github.com/shopware/shopware/blob/trunk/src/Storefront/Resources/app/storefront/webpack.config.js#L367) cannot compile from TypeScript to JavaScript we can't currently use TypeScript syntax in the file. Maybe we can find a solution for this too.

**Comment by ghost** [comment]
@tobiasberge I now tested to include TypeScript syntax as well.

I added "ts-node" to the storefront package.json and changed:

`"production": "NODE_ENV=production webpack --config webpack.config.js"`
to
`"production": "NODE_OPTIONS=\"-r ts-node/register\" NODE_ENV=production webpack --config webpack.config.js"`

Now it works! I can use TypeScript syntax in the webpack.config.ts in my Plugin.

Would you like me to adjust the PR here and add "ts-node"?

**Comment by tobiasberge** [comment]
@akf-bw, thank you for testing and the update 👍 

> @tobiasberge 0% JavaScript and 100% TypeScript in the GitHub "Language" section looks wonderful 😁

Okaaay 😆 

If this is valuable for you and everything without ".ts" still works as expected, it would be a completely optional thing. On the other hand, now we have an additional dependency (in the storefront) to eventually write webpack configs in TypeScript. To me it all looks a bit overkill. In the end it's "just" a config file. What do you think @seggewiss?

**Comment by seggewiss** [comment]
Sorry but I absolutely agree with @tobiasberge!

Here are a few reasons against this:

- TypeScript webpack configs aren't a thing. Nobody uses them
- Almost no webpack plugins are written in TS
- We have no interest ourselves to write webpack.config.ts files
- This adds additional dependencies to the Storefront we don't need

All and all it's a pretty unnecessary change for us.

**Comment by ghost** [comment]
@seggewiss @tobiasberge totally valid points! I revert the last changes to only include the changes from the BundleConfigGenerator. This would then just add support for the extension, which would already be enough.

**Comment by tobiasberge** [comment]
Hey @akf-bw, we have merged your change for the general .ts support into trunk: https://github.com/shopware/shopware/commit/f0d0d10dd3fb0541b1333c675cedf96c0c8dfeed

**Pull request closed without merging**
