### PR TITLE
fix: Add space between snippet and ordernumber

### PR DESCRIPTION
**Pull request by aragon999**
### 1. Why is this change necessary?
I think there should be a space between the snippet and the ordernumber, such that it is consistent with the mails.

### 2. What does this change do, exactly?
Add an space between the ordernumber snippet and ordernumber on the finish page

### 2a. Open question
The PR is currently not in the final state, since it is unclear to me, in which way it should be fixed, as the snippet for the English version contains the space and an additional `#`:
https://github.com/shopware/platform/blob/539d346a3e8d87ba87af08dde3979c027523b99e/src/Storefront/Resources/snippet/de_DE/storefront.de-DE.json#L399
https://github.com/shopware/platform/blob/539d346a3e8d87ba87af08dde3979c027523b99e/src/Storefront/Resources/snippet/en_GB/storefront.en-GB.json#L399

### 3. Describe each step to reproduce the issue or behaviour.
Create an order:
grafik

### 4. Please link to the relevant issues (if any).
\-

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by keulinho** [comment]
Just checked the other translations, e.g. for spain the space is also missing :thinking: 

https://translate.shopware.com/translate/shopware6/24328/en-es?filter=basic&value=0#q=finishInfoOrdernumber

**Comment by keulinho** [comment]
In theory i would like it best if we could split the order number formatting and the translations :thinking: 

We could do it with some kind of filter on the order number that adds the `#` prefix for english translations

@marcelbrode what do you think here?

**Comment by aragon999** [comment]
I created a suggestion, by introducing a new snippet `finishInfoOrdernumberFormat` which contains the format of the ordernumber, with the ordernumber as a parameter. Let me know what you think, I probably need to add a changelog then :-) if that is a desired solution.

**Comment by marcelbrode** [comment]
I personally don't think that's a good idea. Every snippet split into to multiple ones bears the risk of losing context for people translating on crowdin. These people often are not into coding and they only want to translate everything which is marked as "untranslated" without a running instance of shopware to check. Especially `finishInfoOrdernumberFormat` is just a snippet with a variable, which people are very unlikely to understand.

I guess the perfect solution would be to have a snippet including the label and the order number would be passed as a variable, but this has the problem, that they have to have an up-to-date language pack or otherwise they could see no order number at all.

But I definitly get why this suggestion was made... I think the "best" method would be a filter, looking for the current locale, checking if it starts with "en" since this is an english thing and inserts it (maybe via css' `before` pseudo selector), but that's kinda overkill, hm?

@tobiasberge Do you have an additional opinion? :/

**Comment by aragon999** [comment]
Mh, the question is why there are even two different styles, encoded in snippets. Is it common that for example the English ordernumbers should be prefixed with a `#` and the German ones not?

Maybe a different idea, would be to create a new snippet (with a new name), containing the text and variable together?

Edit: A different fix would be to just add the space to the German snippet, which might be the least breaking change. The problem with this approach might be that this space might get lost in translations easily.

**Comment by marcelbrode** [comment]
After a quick research, it looks like the `#` is only an english thing and is not used in any other european country at least. Therefore adding space is not a german solution, its a "every other of the 30+ languages" solution.

As said before, your suggestion would be great, but that would mean that there can be Combinations of Language Pack + Shopware versions to have no order number output there at all, but despite that fact, I personally like that or the twig filter the most.

**Comment by aragon999** [comment]
Regarding the TWIG filter, I think it might be a good idea, as this would probably yield a common style on all places where the order number is displayed (e.g. also in the sent mails). The disadvantage might be, that it should be somehow configurable, as one might dislike the style, or wants to have a different style.

Edit: When adding a completely new snippet, e.g. `finishOrdernumber`, with the content: `Your order number: #%ordernumber%`, than this snippet could be add to the current translations, and the other snippets are deprecated and not used anymore.

**Pull request closed without merging**
