### PR TITLE
fix: sw-cms-layout-modal search field input v-model

### PR DESCRIPTION
**Pull request by florianliebig**
### 1. Why is this change necessary?

When trying to change the assigned layout of a category the search Input is neither persisting the search term, nor using it for the search process.

2023-10-05 at 15 18

2023-10-05 at 15 18

### 2. What does this change do, exactly?

sw-simple-search-field was refactored to use v-model instead of "search-term" property. So we need to adapt to that:

https://github.com/shopware/platform/blob/38c860749e29a2e5ab31f8c867ffe1ea33186d71/src/Administration/Resources/app/administration/src/app/component/base/sw-simple-search-field/index.js#L40

Most other implementations of sw-simple-search-fields use the v-model correctly

### 3. Describe each step to reproduce the issue or behaviour.

1. Create a category
2. Select layout
3. Input search term into modal

### 4. Please link to the relevant issues (if any).

Didn't find any issue. If I need to create one please ping me

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 45025b1</samp>

This pull request fixes a bug in the `sw-cms-layout-modal` component that prevented the search field from updating correctly. It also adds a changelog entry for the fix in `changelog/_unreleased/2023-10-05-fix-sw-cms-layout-modal-search-field.md`.

### <samp>🤖 Generated by Copilot at 45025b1</samp>

* Fix sw-cms-layout-modal search field bug by using v-model for sw-simple-search-field component ([link](https://github.com/shopware/platform/pull/3345/files?diff=unified&w=0#diff-0087d0ddbace169fd5f2129423a64398b2bc1d40bbf42443dee7ca9d3d2baf90L15-R16))
* Add changelog entry for the fix with title, issue number, author and summary ([link](https://github.com/shopware/platform/pull/3345/files?diff=unified&w=0#diff-7c97bfa56424d3b22e862a257bdd9a38bb72589c05420f081eb7ddc0fb00cd64R1-R11))

### CODE REVIEW

**Comment by AydinHassan** [comment]
@florianliebig can you take a look at the failures please? 🙂

**Comment by florianliebig** [comment]
@AydinHassan I updated my branch with the latest trunk. The admin lint is showing a lot of errors which are not related to my changes.

2023-10-06 at 10 09

Somehow, the trunk is also failing in my repo. I will check if there are any diverging trees

**Comment by florianliebig** [comment]
@AydinHassan  I was not able to fix this by rebasing / updating my branch. I also see most other PRs Pipelines fail. Do I need to change anything in the Github Action settings?

**Comment by celha** [comment]
@florianliebig Thanks for your pull request! 💙  I imported the PR and it's now finally merged. 
Unfortunately, I had to create a new commit because it wasn't possible to rebase the PR. So just in case you're wondering why your changes are merged under my name. Sorry for that!

**Comment by mitelg** [comment]
merged with b4654446fd4f7b9b43f8b71012add6eefd8a9019

**Pull request closed without merging**
