### PR TITLE
[NEXT-33271] adjust text type custom field handling

### PR DESCRIPTION
**Pull request by m-waes**
### 1. Why is this change necessary?

Custom fields typed as `text` should not be type casted

### 2. What does this change do, exactly?

Prevent 1.) from happening

### 3. Describe each step to reproduce the issue or behaviour.

Create a product custom field with type `text`
Create a product
Add the value 5E1561 to this custom field
run `bin/console dal:re:in --only=product.indexer`
The ES indexing part should fail (further details in https://issues.shopware.com/issues/NEXT-33271)

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-33271

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by vienthuong** [comment]
Hi @m-waes
Thank you very much for the contribution 🎉 

The change LGTM, could you add a small UT in 

`\Shopware\Tests\Unit\Elasticsearch\Framework\ElasticsearchFieldMapperTest`?

**Comment by m-waes** [comment]
Sorry to waste your time with this, but what is the workflow to run (specific) tests locally. I wasn't able to find a hint in the docs. Are there any helper scripts to target specific test files? I only found `composer phpunit` which a) runs forever when run for everything b) fails for many tests for some reason and c) at this point I'm unsure how that composer command executes phpunit in general.

Any hint would be appreciated 🙏  

Edit: `php -dpcov.enabled=1 -dpcov.directory=. vendor/bin/phpunit --coverage-html "coverage" --coverage-text --testdox --colors=always --filter=ElasticsearchFieldMapperTest`

seems to work, but that unit test in isolation doesn't cover the class in the first place. I'll add my test case shortly

**Comment by ghost** [comment]
Hello,

thank you for creating this pull request.
I have opened an issue on our Issue Tracker for you. See the issue link: https://issues.shopware.com/issues/NEXT-33271

Please use this issue to track the state of your pull request.

**Comment by aragon999** [comment]
@m-waes you can run specific tests by just passing the path to the test, i.e.
```
php ./vendor/bin/phpunit tests/unit/Elasticsearch/Framework/ElasticsearchFieldMapperTest.php
```

**Comment by marcelbrode** [comment]
Your Pull Request has been merged! :tada:
Thanks for your contribution! :blue_heart:

**Pull request closed without merging**
