### PR TITLE
changed svg assets to be much smaller

### PR DESCRIPTION
**Pull request by tinect**
### 1. Why is this change necessary?
The current SVGs are much too big.

### 2. What does this change do, exactly?
I used svgo to make them much smaller. 2976
Adjusted default-settings for svgo:
- no `cleanupIds` (we need to keep IDs to keep relationship of IDs)
- no `removeViewBox`
- no `convertShapeToPath` (EDIT)
- increased default `precision` from 3 to 4 (3 was too less for icons with long curves)

Compression results:
illustration: -43,97%
icon_default: -43,17%
icon_solid: -37,83%

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Review by philipreinken — CHANGES_REQUESTED** [review]
Hi @tinect , thank you for this PR 🙂 We'd rather have a solution based on our webpack build process, since updates to the icons would now require another `svgo` execution. There are several packages for integrating svgo with webpack. In case you can't invest the time, that's fine. Just let us know so we can create an issue ticket to tackle this.

**Comment by tinect** [comment]
Hey @philipgatzka 

I cannot see a reason for the need to require svgo in the project with this change?

The icons are static and served dynamically. Therefore, webpack would also have to update the repository, wouldn't it?

**Comment by philipreinken** [comment]
> Hey @philipgatzka
> 
> I cannot see a reason for the need to require svgo in the project with this change?
> 
> The icons are static and served dynamically. Therefore, webpack would also have to update the repository, wouldn't it?

You're right, the current structure does not really allow for that. We'll evaluate that solution in [a separate issue](https://issues.shopware.com/issues/NEXT-14329). Until that's done, your change is of course a big improvement already so we'll go forward and test/integrate it, thank you for putting in the time 🙂

**Comment by J-Rahe** [comment]
Hey @tinect, thanks for the contribution, we just merged it : )

**Comment by J-Rahe** [comment]
Hey @tinect, just an quick info that we will be reverting this PR for the moment. 
The storefront renders the svg's differently from local image-viewers, causing e.g. the placeholder image for products to be broken. I will leave the corresponding ticket open until we had time to see what happens there.

**Comment by tinect** [comment]
Hey @J-Rahe 

Thank you for the info. Sorry, didn't notice this behaviour of the icon. Maybe we could recreate this icon? 🤔 
Any other icons you noticed being weird?

Edit: It looks like the option `convertShapeToPath` of svgo should be unchecked, too.
Edit 2: https://github.com/tinect/platform/commit/c7a4ae6a161e69fdf6cf2b4a6c4d05d4c0a5a46c this fixed it :-)

**Comment by J-Rahe** [comment]
Hey @tinect, no problem, we also didn't notice this during testing (used demo-data which has images...) and the comparison looked fine (run imagemagick compare for everything). Thanks for fixing this that fast. I put the revert MR on hold so maybe we can just add the fix : )

**Comment by J-Rahe** [comment]
@tinect https://github.com/shopware/platform/commit/b7fc087265b3f792be8a699f597daf49ced83e68 : )

**Comment by tinect** [comment]
Thank you :-) @J-Rahe

**Comment by J-Rahe** [comment]
Thank you for the PR and the quick fix : )

**Pull request closed without merging**
