### PR TITLE
Fixed OpenAPI3 schema generation for entity extensions

### PR DESCRIPTION
**Pull request by florianliebig**
### 1. Why is this change necessary?

As described on stackoverflow (https://stackoverflow.com/questions/73957198/shopware-6-admin-cms-mapping-field-missing-possible-fields-from-entity-extension) I didn't find my Entity Extension in the OpenAPI schema (/api/_info/open-api-schema.json). I found the handling of Entity Extensions in the OpenApiDefinitionBuilder but that data didn't make it into the api response / JSON schema.

image

### 2. What does this change do, exactly?

The OpenApi3Generator.php uses $schema->toJson() to convert the Object to JSON for the api response. Unfortunately this mixed an non-assoc php array with an assoc element ('extensions'), so the 'extensions' array element was dropped when using json_encode. I replaced the assoc array element by a temporary array and just extended the array in a non-assoc way.

### 3. Describe each step to reproduce the issue or behaviour.

Create an entity extension (https://developer.shopware.com/docs/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities), check the element in the schema definiton (/api/_info/open-api-schema.json).

After the fix, any entity in schema with entity extension should contain 'extensions' as property:

2022-10-06 at 16 16

### 4. Please link to the relevant issues (if any).

https://stackoverflow.com/questions/73957198/shopware-6-admin-cms-mapping-field-missing-possible-fields-from-entity-extension

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

<a href="https://gitpod.io/#https://github.com/shopware/platform/pull/2735"></a>

### CODE REVIEW

**Comment by keulinho** [comment]
@florianliebig why did you close your PR? It is still pending internally, but we would like to proceed and merge it.

Anything against that?

**Comment by florianliebig** [comment]
@keulinho I used the trunk in my fork repo for this. I renamed the trunk to create a fresh copy of my trunk. I think you can reopen and continue - sorry.

**Comment by keulinho** [comment]
thanks for the clarification, as the original branch is not there anymore, i can't reopen this PR, but we will continue with merging your changes internally.

**Comment by cyl3x** [comment]
Your commit has been merged, thank you for your contribution :tada: :purple_heart:

**Pull request closed without merging**
