### PR TITLE
Fix session persistent sw-imitating-user-id

### LINKED ISSUE #5297: `imitatingUserId` not cleaned correctly
*PHP Version:* 8.2   | *Shopware Version:* 6.6.6.1  | *Affected area / extension:* Platform(Default) 

 ----

*_Expected behaviour:_*

When "Logged in as customer" the field imitatingUserId contains the user id of the logged in admin user. When the customer logs out of their account, our "impersonating" session also gets logged out due to the token being rotated.

The `imitatingUserId` in our context should now be empty, as we are not logged in anymore.

*_Actual behaviour:_*

When "Logged in as customer" the field imitatingUserId contains the user id of the logged in admin user. When the customer logs out of their account, our "impersonating" session also gets logged out due to the token being rotated.

However our Context still contains the 'imitatingUserId'. Even when logging in as any other user, the imitatingUserId is not cleared.

*_How to reproduce:_*

1) Login as customer via Admin
2) Check the `imitatingUserId` field (for example by dumping it somewhere)
3) Log in as this customer, using the password, in another browser or incognito
4) Log out the new browser
5) The original session will also be logged out, but still have the `imitatingUserId` field.

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
- See #5297 

### 2. What does this change do, exactly?
* Changed `Framework/Routing/SalesChannelRequestContextResolver` to clear the `sw-imitating-user-id` from the session & context, if there is no customer

### 3. Describe each step to reproduce the issue or behaviour.
- See #5297 

### 4. Please link to the relevant issues (if any).
- Fixes #5297 

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by keulinho** [comment]
Hey @akf-bw, 
thanks for your contribution! 🎉 

Can we cover this behavior with a test e.g. in `\Shopware\Tests\Integration\Core\Framework\Routing\SalesChannelRequestContextResolverTest`?

@runelaenen as you reported the issue, any chance you can verify the fix as well?

**Comment by ghost** [comment]
Hey @keulinho, no problem. I added a additional test for this.

**Comment by runelaenen** [comment]
This fix seems to work in our case 💪💙

**Comment by keulinho** [comment]
> Hey @keulinho, no problem. I added a additional test for this.

thanks for quick resolution, just to be sure could you also add a case that the id is not deleted accidentally, so that it keeps the id if the user is logged in?

**Comment by ghost** [comment]
> thanks for quick resolution, just to be sure could you also add a case that the id is not deleted accidentally, so that it keeps the id if the user is logged in?

@keulinho I now added this test too

**Comment by mitelg** [comment]
thanks for your contribution @akf-bw 👍🎉💙

**Pull request closed without merging**
