### PR TITLE
NEXT-31894 - Add form validation to address editor modal

### PR DESCRIPTION
**Pull request by pietrzakadrian**
### 1. Why is this change necessary?

Failure to validate data in the form may result in incorrect data being sent to the controller.

### 2. What does this change do, exactly?

Activates form validation in a modal using the FormValidation plugin

### 3. Describe each step to reproduce the issue or behaviour.

Log in to your account and go to /account. Then edit or add a new shipping or billing address.

### 4. Please link to the relevant issues (if any).

https://github.com/shopware/platform/issues/2941

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

<a href="https://gitpod.io/#https://github.com/shopware/platform/pull/2942"></a>

### CODE REVIEW

**Comment by ThuVo241** [comment]
Hi @pietrzakadrian , The rest are good for me. Could you rebase this branch and fix commit message follow the convention.

**Comment by silverDuy** [comment]
Hi @pietrzakadrian, Thank you so much for your contribution. We will take care of it from here.

**Comment by pietrzakadrian** [comment]
Hi, the branch has been updated.

**Comment by silverDuy** [comment]
Hi @pietrzakadrian, thank you so much; we are in the process. Once again, thank you for your effort.

**Comment by silverDuy** [comment]
Hi @pietrzakadrian , Your changes were merged to trunk: https://github.com/shopware/shopware/commit/000f1087e6208dc7e6a3871c5afea0b5732353b0

**Pull request closed without merging**
