### PR TITLE
Dispatch events after default is successfully set

### PR DESCRIPTION
**Pull request by quisse**
### 1. Why is this change necessary?
To be able to trigger actions based on default addresses successes

### 2. What does this change do, exactly?
Add some events

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/shopware/issues/3439

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mstegmeyer** [comment]
Could you change the names of these events? We try to avoid `Set` due to it being close of "a set of things" / a collection.
Maybe do `Switched` just like the Route or `Changed`?

Also: just a code style choice: instead of that rather large `switch`, maybe do a match? Something like this:

```php
$event = match($type) {
    self::BILLING => new BillingEvent(),
    default => new ShippingEvent(),
};
$this->eventDispatcher->dispatch($event);
```

**Comment by mstegmeyer** [comment]
@quisse small ping here, are you still working on this?

**Comment by quisse** [comment]
Not really able to program atm. Will look into this in the next month or 2.

**Comment by mstegmeyer** [comment]
@quisse Just pinging here again, are you going to implement the changes soon? Otherwise we can do it, so we can close this PR 😉

**Comment by quisse** [comment]
Haven't had time yet, you can pick it up 👍

**Comment by mstegmeyer** [comment]
Hey @quisse this now went into internal discussions and we realized, that we would add a customer to the event, that is not the current DB state anymore. At the same time, reloading the context and the customer requires a lot more time & resource for such a simple request and there is already an event, that is emitted right before the actual change (the address should already exist at this time).

I'm sorry to inform you (especially this late), that we will therefore not merge this PR and recommend you to decorate the route, if you want to do something immediately after the DB update.

**Pull request closed without merging**
