### PR TITLE
Norwegian installer

### PR DESCRIPTION
**Pull request by kurtinge**
### 1. Why is this change necessary?
To be able to choose norwegian as the default language during installation.

### 2. What does this change do, exactly?
Add norwegian translations to the installer and norwegian as an option to choose as default language during installation of a new store

### 3. Describe each step to reproduce the issue or behaviour.
Start the installer, see that you cannot choose norwegian as default language.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by keulinho** [comment]
Hey @kurtinge, thank you very much for your contribution! :blue_heart: :tada: 

Sadly we are internally currently working on rewriting the installer to a clean symfony base, that also changes the whole translation loading etc. Therefore i would like to put this PR on hold until the new installer is merged. Your changes should then be pretty easy to adapt to the new structure.

**Comment by keulinho** [comment]
The new installer just landed in the core with commit https://github.com/shopware/platform/commit/67b3bac9b2aae79094db51859cfe9ab887144103.

The translations are now under `src/Core/Installer/Resources/translations/translations` and are now in yaml format. Please move the new translations in the according structure at the correct place. The message keys for the translation were not changed, therefore the refactoring should be straight-forward.

You also need to add `nb` to the list of the supported languages in the `shopware.installer.supportedLanguages` parameter in `src/Core/Installer/DependencyInjection/services.xml`.

**Comment by kurtinge** [comment]
Hey @keulinho 

I've now moved the translations into yaml files for the new installer

**Comment by keulinho** [comment]
thanks again for your contribution! :blue_heart: 
Your changes were merged with 8573d6b071bf69e903f297b241a7e80bf263b471

**Pull request closed without merging**
