### PR TITLE
NEXT-18964/fix endless reload on admin login

### PR DESCRIPTION
**Pull request by juripetersen**
### 1. Why is this change necessary?
 When Shopware is installed two times on overlapping subdomains (staging.example.org and example.org) the cookie named "bearerAuth" from example.org is processed on the administration of staging.example.org and leads to an endless redirect-loop there, because it is no valid authentication there.

### 2. What does this change do, exactly?
After receiving HTTP 401 on the login page, the logout method is called. This method has tried to remove the present cookie via npm package `cookie-storage`. However, in the used approach without these changes, this will never remove the bearerAuth cookie from a higher level domain. 
I changed the logout method to check if the call to `cookieStorage.removeItem('bearerAuth')` was successfull.
If not, a new function called `clearAuthCookieForAllDomains` is used to remove the cookie on all levels of the domain.

Of course, this change would remove every cookie on the domain that is called 'bearerAuth'. This side-effect might not be desired, but can probably only be avoided by using a different package/class to set and retreive cookies.
### 3. Describe each step to reproduce the issue or behaviour.
Steps to reproduce: See section 1.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-18964

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by MalteJanz** [comment]
Hi @juripetersen , thank you very much for this PR. Unfortunately we had some discussions about the implementation in our internal code review. We think it would be better to approach this issue at the root cause (the cookie creation and to which (sub-)domain it belongs).

The side effect of a logout at `dev.shopware.com` also leads to a logout on `shopware.com` with your solution which isn't  expected because one (sub-)domain should not influence the other. This is better than preventing to login on one domain because of endless reloads but still not how things should work.

It would be nice if you could take a look at other ways to fix the problem of endless reloads 🙂 .

@jleifeld suggestet:
Then we should scope the cookies with the correct domain and path: https://github.com/bouzuya/cookie-storage#usage Currently our domain and path is evaluated like this:
```
if (typeof window === 'object') {
    domain = window.location.hostname;
} else {
    // eslint-disable-next-line no-restricted-globals
    const url = new URL(self.location.origin);
    domain = url.hostname;
}

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
const path = context.basePath! + context.pathInfo!;
```

This would fix the source of the problem.

One other minor point: you checked that you have written tests in your PR description which is not exactly true. Maybe add at least a unit test for changed / added functions (I know this one is hard to test as a whole because you need two instances of Shopware at different sub domains) 🙈 .

**Comment by juripetersen** [comment]
@MalteJanz the outcome of your discussion is what I expected and very reasonable. 
I think the approach suggested by @jleifeld is good, but I think it can't be done without using a different package to set and retreive cookies in general. 
The cookie-storage package sets cookies with a prefix of a dot. 
Thats why this bug appears in the first place.

Should I apply a change that uses a completely different approach on how cookies should be handled on the lowest abstraction?

**Comment by juripetersen** [comment]
@MalteJanz I found a quick fix for this with the current npm package. 
Will implement it asap and let you know.

**Comment by MalteJanz** [comment]
@juripetersen that's nice to hear. I'm excited about it 👍.

**Comment by juripetersen** [comment]
@MalteJanz how would you approach testing this?

**Comment by MalteJanz** [comment]
@juripetersen you could add a simple unit test for the function `cookieStorageFactory` inside of `login.service.spec.js` and test there that the `CookieStorage` is created in the right way and maybe that it works as expected. I think we don't have a specific test for that function yet.
I also think that it's very hard to write a test about the initial problem, maybe it can be done if some parts on the window / document object get mocked to simulate different domains but I'm not sure about that and how the cookie library works internally. So I'm fine with a basic unit test 🙂.

**Comment by juripetersen** [comment]
@MalteJanz I added a simple test for the structure of the output and its functions.
The general functionality is tested in other tests that have already been in place.
However there are E2E tests that are failing but I dont suspect the changes from this PR to be the cause.

**Comment by juripetersen** [comment]
@MalteJanz I added a simple test for the structure of the output and its functions.
The general functionality is tested in other tests that have already been in place.
However there are E2E tests that are failing because of reasons that are not caused by the changes in this PR.

**Comment by juripetersen** [comment]
@MalteJanz I added a simple test for the structure of the output and its functions.
The general functionality is tested in other tests that have already been in place.
However there are E2E tests that are failing because of reasons that are not caused by the changes in this PR.

**Comment by MalteJanz** [comment]
@juripetersen Wow, I finally tried your new solution and it works very nicely, awesome job 🎉 👍.

I also did some small tests if this change reintroduces a regression for older bug fixes like https://issues.shopware.com/issues/NEXT-8459 but that doesn't seem to be the case.

It hopefully passes our internal code review this time as it is a much cleaner solution without some nasty side effects. I will keep you updated 🙂.

One last question from my side: you have some changes inside the `administration/package-lock.json`. Why is that the case? Maybe you can remove them from the PR🤔?

**Comment by juripetersen** [comment]
The changes were caused by a local run of `npm install`. I removed these changes from the pr.

**Comment by MalteJanz** [comment]
Hi @juripetersen ,

I am really sorry to say this, but this implementation still can't be merged on our side. The first problem occurred during testing when updating Shopware to this change and running into endless reload problems (again, but this time much more dramatic for all existing users who have updated).

I already provided a fix for that internally in `login.service.ts` line 285 (after the call to `.removeItem(storageKey)`). Feel free to also add this to your implementation:
```ts
            // CookieStorage may not remove the cookie value, because the cookie domain may have changed slightly in the
            // ticket NEXT-20220 / NEXT-18964 .
            // This will make sure that old cookie values with the old domain are removed correctly.
            if (cookieStorage.getItem(storageKey)) {
                // build the CookieStorage the old way as it was done before NEXT-20220
                let domain;

                if (typeof window === 'object') {
                    domain = window.location.hostname;
                } else {
                    // eslint-disable-next-line no-restricted-globals
                    const url = new URL(self.location.origin);
                    domain = url.hostname;
                }

                // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
                const path = context.basePath! + context.pathInfo!;

                // Set default cookie values
                const oldStorage = new CookieStorage(
                    {
                        path: path,
                        domain: domain,
                        secure: false, // only allow HTTPs
                        sameSite: 'Strict', // Should be Strict
                    },
                );

                // remove the item on the old way CookieStorage
                oldStorage.removeItem(storageKey);
            }
```

The real problem revealed itself when we run our complete internal e2e pipeline which runs into many errors. Somehow different user actions inside the administration cause a sudden logout which is not expected behaviour.

To provide an example (which I already reproduced locally):
1. clear all browser data for shopware + cookies
2. login into the administration
3. navigate to marketing -> promotions and create + save one
4. every time you switch to the "discounts" tab and click on "Add discount" you are suddenly logged out.
5. If you log in again after this it somehow works. To reproduce it again make a hard reload (with cache clear) before logging in again.

We already tried to investigate this issue in limited amount of time and here are some findings we got for the example above:
- It is somehow related to the `sw-promotion-discount-component` and the `createdComponent` method. More precisely the `Shopware.Service('syncService')` does not work as expected (it returns a bearer token with `false` on a call to `this.syncService.getBasicHeaders()`)
- One surprising fix for this is to load the service via the `inject` property inside the vue component instead. Then it somehow works as expected, but this would require many changes across the administration and shouldn't be a problem in the first place.
- It looks like the call to `Shopware.Service('syncService')` somehow creates a new cookie `__ob__` with value `[object, object]` and that alone can cause the following requests to fail and causes a logout.

It would be nice if you could have a closer look and resolve this issue, as we can't merge this implementation without fixing these problems first 🙈 .

**Comment by MalteJanz** [comment]
Hi @juripetersen 

Unfortunately I will close this PR for now, thanks again for your effort 👍. We will have a closer look into this issue internally with our normal workflow and it can be tracked here:
https://issues.shopware.com/issues/NEXT-18964

**Comment by MalteJanz** [comment]
@juripetersen FYI: The final solution if finally found and merged 🎉 : https://github.com/shopware/platform/commit/c681726a227841807170b4e31106197cc9bfee68

**Pull request closed without merging**
