### PR TITLE
Form preserver iterates through wrong elements

### PR DESCRIPTION
**Pull request by wannevancamp**
### 1. Why is this change necessary?
See ticket  #2227

### 2. What does this change do, exactly?
See ticket #2227 and title

### 3. Describe each step to reproduce the issue or behaviour.
See ticket  #2227

### 4. Please link to the relevant issues (if any).
/

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by keulinho** [comment]
Hey @wannevancamp thanks for your contribution! :tada: :blue_heart: 

Please ensure to sign the [Contributor License Agreement](https://cla-assistant.io/shopware/platform?pullRequest=2228). Also note you used a different GitHub user when committing your changes, from the GitHub user you used to open the PR. I have to admit that i'm not quite sure for which account you have to sign the CLA.

**Comment by wannevancamp** [comment]
@keulinho , meanwhile I signed the CLA with my Github user.

**Comment by keulinho** [comment]
@wannevancamp the CLA bot still says the signing is pending/missing.

**Comment by shyim** [comment]
Hey,

I will close this as it is inactive. Feel free to create a new PR when you have added the incomplete parts

**Pull request closed without merging**
