### PR TITLE
NEXT-00000 - add active from to tax rule

### PR DESCRIPTION
**Pull request by CodeproSpace**
### 1. Why is this change necessary?

We currently have no way to manage the tax activity date. We cannot schedule a specific day for tax implementation. Sometimes the tax rate changes. In addition, such a date will allow us to "recalculate" the tax backwards (if a tax change was introduced and we did not know about it). This change is useful for large stores selling in multiple countries, so they need more tax management.

### 2. What does this change do, exactly?

My change adds a new date time field to the tax rule. We can set the date of its activation. It is stored in UTC format. The admin can set this date in the panel when creating a tax rule. In SalesChannelContext, the latest tax activity date is always selected from all the rules that meet the criteria.

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 256b18a</samp>

This pull request adds a new feature to the tax system that allows defining tax rules that are only valid from a certain date onwards. It introduces a new `activeFrom` property to the `TaxRuleEntity` and `TaxRuleDefinition` classes, and a new `active_from` column to the `tax_rule` table. It also modifies the tax rule matching logic in the `SalesChannelContextFactory` and the tax rule type filters to check the activation date of the tax rules. Additionally, it updates the administration UI and the unit tests to support the new feature.

### <samp>🤖 Generated by Copilot at 256b18a</samp>

*  Add the `activeFrom` property to the `TaxRuleEntity` class and the `tax_rule` table to store the activation date of each tax rule ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-2ae7f19f238e89bf16fad51ac02b3722c0848fd38e1521ba8656e2e758e6ef3cR6),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-2ae7f19f238e89bf16fad51ac02b3722c0848fd38e1521ba8656e2e758e6ef3cR66),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-eb4d19eb50cd71decc5d2bed7761000878e7150dcd8f7807827660e9075b96e4R57-R61),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-eb4d19eb50cd71decc5d2bed7761000878e7150dcd8f7807827660e9075b96e4R144-R153),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-2a0604e327822be0674f91b72768fa1435f05b0c3f279262551e8d8cb5881e01R1-R28),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-b29cfac1b9c35d784dd7efbf3b5c7631cf865c61031694fae8eb41d02ba0dfefR1-R82))
*  Add the `isTaxActive` method to the `AbstractTaxRuleTypeFilter` class to check if a tax rule is active based on the current date and the `activeFrom` property ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-b5ae77baa27247904d0965be10a433d2d71e1c610465960129beb686da33794bR19-R33),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-b4bd1e51f09a46ed83232b0ad4645c7ee48b3cb6b6425b6ae774e51b89e02251R1-R17))
*  Modify the `match` methods of the `EntireCountryRuleTypeFilter`, `IndividualStatesRuleTypeFilter`, `ZipCodeRangeRuleTypeFilter`, and `ZipCodeRuleTypeFilter` classes to use the `isTaxActive` method if the `activeFrom` property is not null ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-1b2db26d9e65fdcd7dcac5dcfa8ba556b1f175d3735ef8a4cf04c65a068bc9ffL11-R11),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-1b2db26d9e65fdcd7dcac5dcfa8ba556b1f175d3735ef8a4cf04c65a068bc9ffR23-R26),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-32db726c08f416d8010e1cfd120097d15acb27994ba617cda189d12da08d9556L11-R11),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-32db726c08f416d8010e1cfd120097d15acb27994ba617cda189d12da08d9556R30-R33),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-cb0a161d4525d7f27bf6e800d7d81028de425bfc260072b7102efe13250f9284L11-R11),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-cb0a161d4525d7f27bf6e800d7d81028de425bfc260072b7102efe13250f9284R32-R35),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-b7a7830823aacf568e664026fc09b88ddcb354582a70603df417f4b7f24e045dL11-R11),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-b7a7830823aacf568e664026fc09b88ddcb354582a70603df417f4b7f24e045dR31-R34))
*  Modify the `getTaxRules` method of the `SalesChannelContextFactory` class to filter the tax rules by the highest type position and the latest activation date ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-d9909deceaf8a3de1970aac9bfebd418097905939bd2dc6bc9d52a3315c25b09L155-R167))
*  Modify the `testGetTaxRuleCollectionCustomerShippingCountry` and `testGetTaxRuleCollectionCustomerShippingTypeZipCodeRangeOverridesIndividualStates` methods of the `SalesChannelContextTest` class to create and assert tax rules with different `activeFrom` dates ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-ef556f549f29c81e6d0e37aa8922c1e114407e48e6a25bbf0d12fad5e719ed44L72-R85),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-ef556f549f29c81e6d0e37aa8922c1e114407e48e6a25bbf0d12fad5e719ed44L80-R93),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-ef556f549f29c81e6d0e37aa8922c1e114407e48e6a25bbf0d12fad5e719ed44R195),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-ef556f549f29c81e6d0e37aa8922c1e114407e48e6a25bbf0d12fad5e719ed44R205))
*  Add the `sw-datepicker` component to the `sw-settings-tax-rule-modal` template and the `sw-settings-tax-rule-modal` unit test to allow the user to select a date and time for the `activeFrom` property ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-bc9bbaf290e624eb53ebfe107d6dc65c8ab83b1f995c8d9496495259730be2b8R75-R84),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-d3bd54a50c7798049cd619724bae090cbdb546ef39e292c79c14c2e23a7916eaR23))
*  Add the `activeFrom` property to the list of mapped errors and columns for the `sw-settings-tax-rule-modal` and `sw-tax-rule-card` components to display validation errors and activation dates for the tax rules ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-71ae65257264edc36f2ab416e9cb4b67167fff0e409184f4a31b602dc7c0488cL64-R64),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-38479b5d15ad4c4c1b3b6d233e9f27569580c9e2766c59009e04931bb58c3da8R100-R103))
*  Add the `sw_settings_tax_rule_grid_column_tax_rule_active_from` block to the `sw-tax-rule-card` template to format the `activeFrom` property as a date string in the grid column ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-7853c4690bd50f42ec6222507dadfeec547e60a2244e70b839ac4cb58b356e2aR107-R119))
*  Add the `labelActiveFrom` snippet to the `de-DE.json` and `en-GB.json` files for the `sw-settings-tax` module to provide the German and English translations for the label of the `activeFrom` property ([link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-694a0ca2de5869e2ea3cbb90c0b1783e7be2c533e3234405e5d9e2edcb6a0fc9L81-R82),[link](https://github.com/shopware/platform/pull/3214/files?diff=unified&w=0#diff-ab119f53a6bc297becf801346baa113113d420c812457193944d29b9581462d9L71-R72))

### CODE REVIEW

**Comment by CodeproSpace** [comment]
Something's wrong with "Lint Admin" because it's getting errors in files I haven't changed....

**Comment by CodeproSpace** [comment]
> Something's wrong with "Lint Admin" because it's getting errors in files I haven't changed....

@shyim Can you check that job?

**Comment by lernhart** [comment]
Hey @CodeproSpace, thank you for your contribution.
We've imported the PR to our internal gitlab instance, to be able to show this to our designers and other non-developer team members.

They want to have a good look to it, before we can merge this. 

I'll keep you updated.

**Comment by CodeproSpace** [comment]
@lernhart Great news. If you need anything let me know.

**Comment by lernhart** [comment]
Hey @CodeproSpace, sorry for the delay in this. We did not forget you, no worries. 

We've had a lot in the pipeline in the past few weeks. 

I will ensure, that somebody from quality assurance will have a look at this in the next days. Form a dev perspective, your PR looks got to me.

**Comment by lernhart** [comment]
The PR was just merged on our side and will be part of the next release.

Thank you for your contribution :+1:  @CodeproSpace :tada: :tada: :tada:

**Pull request closed without merging**
