### PR TITLE
Add `shopware.messenger.skip_enforce_size_messages` config option

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
- The new `shopware.messenger.enforce_message_size` config option (which will be enabled by default from Shopware version 6.7.0.0) will prevent all messages from entering the message queue, if they are bigger than 256 kB.
- This will also block sending emails with a body larger than 256 kB via the message queue.
- This PR adds a new config option `shopware.messenger.skip_enforce_size_messages` which includes the message `Symfony\Component\Mailer\Messenger\SendEmailMessage` and allows further entries if they cannot always be smaller than 256 kB (which should be the goal).

### 2. What does this change do, exactly?
* Added the `shopware.messenger.skip_enforce_size_messages` array config option which contains the `Symfony\Component\Mailer\Messenger\SendEmailMessage` message by the shopware config
* Changed `src/Core/Framework/MessageQueue/Subscriber/MessageQueueSizeRestrictListener.php` to skip over messages included in the `shopware.messenger.skip_enforce_size_messages` config option

### 3. Describe each step to reproduce the issue or behaviour.
- Enable the `shopware.messenger.enforce_message_size` config option
- Try sending an email over the message queue with a body larger than 256 kB

### 4. Please link to the relevant issues (if any).
- /

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @akf-bw 

I am afraid we need to find another solution for the mail message :thinking: 
We are using this in our SaaS environment https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/quotas-messages.html
Even if we would skip messages, it will still fail, because it has this hard cap. 

@shyim what do you think?

**Comment by ghost** [comment]
@mitelg I already talked about this topic with @shyim.

My first attempt to fix this problem was this commit: https://github.com/akf-bw/platform/commit/accbf74cdfcf583c42aa9696ecd910b403e34e5e to only throw exceptions if the target transport is a sqs transport. @shyim mentioned that this would not make anyone want to reduce the size of the messages he is sending, if they were going to be processed anyway if the transport was not SQS.

> Even if we would skip messages, it will still fail, because it has this hard cap.

Not if you use another transport like Redis which does not have such limitations as SQS.

**Comment by tinect** [comment]
What about making just this "256 kB" configurable?

**Comment by mitelg** [comment]
yes, it is not about the used transport system, more about teaching the people to keep the message size at a sane level. Sending whole objects is just not right, for example :slightly_smiling_face: 

I recently adjusted the product and category indexer to split up the IDs in better chunks.
Imo, the question is, why is the `SendEmailMessage` so big? :thinking:

**Comment by shyim** [comment]
email attachments are part of mail, attach invoice you are already over the limit. The right way would be to make SendMailAction in flow builder async using a flag and remove the hint to use asynchrous mailing

**Comment by shyim** [comment]
I think we should also add an config to completely disable this feature or enforce this only in dev mode. 
grafik

**Comment by ghost** [comment]
Replaced by #5482

We will simply move the check of the config option for now and remove the `deprecated` status.
@shyim will discuss internally a solution for the large email messages.
My first proposal for a solution would be this commit, which moves the email data out of the message queue:
https://github.com/akf-bw/platform/commit/95f22469f2cccdf0ddf44109256ee42de8c560ad

**Pull request closed without merging**
