### PR TITLE
fix: Naming of changelog

### PR DESCRIPTION
**Pull request by aragon999**
### 1. Why is this change necessary?
For the Windows users

### 2. What does this change do, exactly?
Remove illegal character from the filename

### 3. Describe each step to reproduce the issue or behaviour.
¯\_(ツ)_/¯

### 4. Please link to the relevant issues (if any).
\-

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

<a href="https://gitpod.io/#https://github.com/shopware/platform/pull/2763"></a>

### CODE REVIEW

**Comment by mitelg** [comment]
@keulinho we need a automatic test for this

**Comment by keulinho** [comment]
@mitelg here you go: https://issues.shopware.com/issues/NEXT-23662

**Comment by aragon999** [comment]
@mitelg @keulinho when I was creating this PR, I also wanted to integrate this into danger, but than I realized that this is [actually already tested in the pipeline](https://github.com/shopware/platform/actions/runs/3238257324/jobs/5306279033) . So it might be more reasonable to include a similar job into your gitlab pipeline?

**Comment by keulinho** [comment]
@aragon999 i already did so right now

**Comment by flkasper** [comment]
After I had discovered the error in the pipeline, i actually made a corresponding fix commit in my PR. But this was not taken over when merging the PR. (Maybe a missing pull before merge?).

I just don't remember if I created the changelog file via the phpstorm toolbox plugin or via the SW-internal command, but both should be adjusted accordingly.

**Comment by aragon999** [comment]
@fk-bitsandlikes the changelog create command should create the file with only valid characters:
https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Changelog/Processor/ChangelogGenerator.php#L36-L39

**Comment by flkasper** [comment]
Then it was with the shopware toolbox plugin, created a corresponding issue shopwareLabs/shopware6-phpstorm-plugin/issues/91.

**Comment by keulinho** [comment]
Hey @aragon999 thanks again for your contribution, your changes are merged! :tada: :blue_heart:

**Comment by keulinho** [comment]
FYI @aragon999 and @fk-bitsandlikes now we check for special chars in the file name and throw an error in the CI: https://github.com/shopware/platform/commit/a10633a369c3d35dbc39309e78d5226cf237b63f

**Comment by flkasper** [comment]
@keulinho 
Won't the test-changelog file also cause problems when checking out under Windows because of the colon in the name?
https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Test/Changelog/_fixture/template/command-invalid-name/changelog/_unreleased/1977-12-10-a:full-change.md

**Comment by aragon999** [comment]
It does: https://github.com/shopware/platform/actions/runs/3265002847/jobs/5366524953#step:3:460 :-)

Maybe it would be more reasonable to perform a similar check as it is done on Github, as the invalid characters can also be in other files (like text fixtures, as in this case :-D).

**Comment by keulinho** [comment]
you are completely correct :facepalm:

**Comment by JoshuaBehrens** [comment]
F

**Comment by keulinho** [comment]
Should be fixed by now, and the filename check is now also executed for every file in the repo with a danger rule:
https://github.com/shopware/platform/commit/735ffc3808790c4ddc7d784a41781f461e41549d

**Pull request closed without merging**
