### PR TITLE
NEXT-3743: Fix inadequate entity definition resolving in Elasticsearch filter parsing that show when filtering for a translated field of a related entity is executed

### PR DESCRIPTION
**Pull request by SpiGAndromeda**
### 1. Why is this change necessary?

If a filter is applied on an Elasticsearch query that uses a translated field of an entity that is related to the product entity, a `RuntimeException` is thrown in the `getTranslatedField`method of the `EntityDefinitionQueryHelper`.

The filter parsing uses the `getField` method of the `EntityDefinitionQueryHelper` to get the field even if the field name contains relations. The same is not done for the definition itself. As the root definition is passed to the value parsing this would mostly lead to a null return of the `getField` method, which is unexpected behavoir. However, if the field is `TranslatedField, the `getTranslatedField` method is called. This method only searches for the field in the fields of the passed translation (without deeper resolving). The field won't be found an an execption is thrown indicating that the property is missing.

### 2. What does this change do, exactly?

This change introduces a private `getDefinition` method in the `CriteriaParser` to resolve the definition over it's relations to a definition that actually contains the field. This method is called in the `parseEqualsAnyFilter` method, the `parseEqualsFilter` method and the `parseRangeFilter` method. The original definition will still be used for the query creation. If the field does not exist in the resolved entity, an exception is still thrown.

### 3. Describe each step to reproduce the issue or behaviour.

The bug only occurs on translated fields of entities that are related to the product entity. One example is the `shortCode` field in the unit entity. The exception will be thrown if a filter (equals, equals any or range) is applied to this field.

### 4. Please link to the relevant issues (if any).

https://github.com/shopware/shopware/issues/3743

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### 6. Related PR

There already is an open PR for this issue in SW 6.5. Because the code changed, I firstly created a branch and PR for 6.5. However, this is for SW 6.6. Fix was the same (I just improved it a little). Fix can be backported to SW 6.5 easily.

### CODE REVIEW

**Comment by vienthuong** [comment]
Hi @SpiGAndromeda 
Thanks for your contribution 👍🏽 
The change looks good to me, however did you check `\Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper::getAssociatedDefinition`? it's seems to have the same functionality without private `getDefinition` method

**Comment by SpiGAndromeda** [comment]
> however did you check `\Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper::getAssociatedDefinition`? it's seems to have the same functionality without private `getDefinition` method

You're absolutly right. I didn't know this method exists. I added to commit replacing my implementation with the existing one.
You'll sqash the commits on merging right?

**Comment by SpiGAndromeda** [comment]
Should I do the backport to 6.5? And if yes, how? Just a new branch? Are there any special requirements?

**Comment by vienthuong** [comment]
Hi @SpiGAndromeda 

I'd be great if you can also create another PR for `6.5.x` I guess the change is minimal, but the helper method is not exists on 6.5.x so you need to add it, and you probably need to manual tests (and unit tests) for with/without flag `6.6.0.0`?

Other than that, there's no other requirement

**Comment by SpiGAndromeda** [comment]
@vienthuong what about the issue in the changelog file. Should I use `NEXT-37804` as well?

**Comment by vienthuong** [comment]
@SpiGAndromeda correct! and I minor note is it should be # Core instead of # Elasticsearch

**Comment by SpiGAndromeda** [comment]
@vienthuong created the new PR and linked this one there.

**Pull request closed without merging**
