### PR TITLE
phpstan.neon.dist: remove references to non-existant exclude-files

### PR DESCRIPTION
**Pull request by staabm**
### 1. Why is this change necessary?

latest PHPStan release errors on non-existant exclude-files

### 2. What does this change do, exactly?

fixes the phpstan config

### 3. Describe each step to reproduce the issue or behaviour.

run phptan [1.11.9](https://github.com/phpstan/phpstan/releases/tag/1.11.9) on the codebase

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by staabm** [comment]
should the changelog contain tooling config only changes?

**Comment by shyim** [comment]
nope thats fine to not have a changelog

**Comment by shyim** [comment]
thanks for the PR. We will merge it soon

**Comment by staabm** [comment]
btw: phpstan also reported 

> Path /home/runner/work/phpstan-src/phpstan-src/e2e/integration/repo/src/WebInstaller/vendor is neither a directory, nor a file path, nor a fnmatch pattern.

I was not sure, whether its a wrong path in the config or the `vendor/` dir will be created in a build process or similar

**Comment by mitelg** [comment]
thanks for your contribution @staabm 👍🎉💙

`src/WebInstaller/vendor` could be there during development of the installer

**Pull request closed without merging**
