### PR TITLE
Improve admin last activity storage & remember me behavior

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
Last activity storage behavior changes:
- If you are currently working with the watch-administration script, which is located on a different base path than the normal administration (e.g. '/' and '/admin'), the `lastActivity` cookie will be set on a different path for both environments (e.g. '/' & '/admin')
- When the normal administration accesses the current cookie state, it looks for the `lastActivity` value of the path from the watch administration script, not for the state of the current path, because the "document.cookie" value doesn't save the path in it. It can't update it either because the current path is different.
- This eventually leads us to a state where you cannot login anymore because you always get logged out directly from administration. The only workaround is to delete all cookies of the entire domain.
- These PR changes move the `lastActivity` value from the cookieStorage to the site's localStorage, which is accessible by both the watch-administration script and normal administration. This fixes the access issue and it is also no longer possible to have a duplicate key.
- This move away from cookieStorage also brings performance improvements, as access is significantly faster on the localStorage. Since the `lastActivity` value can sometimes be written extremely often (every mousemove or keyup event on the page), access to the underlying storage should be quite fast.

Remember me behavior changes:
- Currently the "Remember Me" feature has a hardcoded value of 14 days, which also affects the bearer authentication object time only once at the first login. From that day on, the maximum duration the user can stay logged in is up to the "Remember Me" timestamp that was set on the first login (+14 days).
- This PR changes the behavior by changing the "Remember Me" value from the last timestamp to a true/false value.
- Every time the bearer authentication object is now written, the expiration time will be updated to the correct timestamp.
- We now also use the correct, non-hardcoded refresh token duration to determine when the token should finally expire (if it is not refreshed in the meantime).
- This change also now allows the user to be truly remembered by the administration and stay logged in as long as the user comes back within the refresh token lifetime (default 7 days).

Miscellaneous:
- The `refresh-after-logout` value is only used on logout / login actions and can be saved to the `sessionStorage` because it's not needed in the cookies

### 2. What does this change do, exactly?
* Changed `updateLastUserActivity` in `service/user-activity.service.ts` to use the global `localStorage` instead of the `cookieStorage`
* Changed `setBearerAuthentication` in `service/login.service.ts` to correctly update the expire time with the remember me feature
* Changed `loginByUsername` in `service/login.service.ts` to use the `userActivityService` to call `updateLastUserActivity`
* Changed `lastActivityOverThreshold` in `service/login.service.ts` to use the `userActivityService` to call `getLastUserActivity`
* Changed `forwardLogout` in `service/login.service.ts` to use the global `sessionStorage` instead of the `cookieStorage`
* Changed `setRememberMe` in `service/login.service.ts` to change the `rememberMe` value from a timestamp to true/false
* Changed `shouldConsiderUserActivity` in `service/login.service.ts` to check for the bool state of the `rememberMe` value
* Changed `addGlobalNavigationGuard` in `factory/router.factory.js` to use the `userActivityService` to call `updateLastUserActivity`
* Changed `beforeMount` in `sw-login/page/index/index.js` to correctly check the `refresh-after-logout` sessionStorage key
* Changed `setLastActivity` in `shop-configuration.html.twig` to correctly update the `lastActivity` localStorage key

### 3. Describe each step to reproduce the issue or behaviour.
- Run the watch-administration command/script
- Login to the administration on the watch-administration page
- Close the watch-administration page and revisit the normal administration page later
- Try to login again

### 4. Please link to the relevant issues (if any).
- https://github.com/shopware/shopware/pull/5020

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by ghost** [comment]
@seggewiss Could you please take a look at this PR and https://github.com/shopware/shopware/pull/5020.
There are many improments to the admin login, session & token behaviors, that finally allow a real "remember me" feature and better performance. 💙

**Comment by akf-bw** [comment]
I've now added even more tests for the remember me & user activity feature.

**Comment by seggewiss** [comment]
Hey @akf-bw 👋 

I'm currently experiencing issues with our e2e pipeline that's why it's still not merged. I'll try to resolve them and check if the failures are valid.

**Comment by seggewiss** [comment]
Morning @akf-bw 👋 

Problems are resolved I expect it to be merged today 💙

**Pull request closed without merging**
