### PR TITLE
NEXT-00000 - Fix admin customer sales channel & acl checks

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?

- The customer detail page loads the `salesChannel` association even though it is unsed
- The customer detail page only loads the `boundSalesChannel` and it's domains with the `customer.editor` permission however, this data is always required on the customer detail page and must therefore be loaded without the permission check
- With the latest changes we need to `sales_channel_domain:read` permission on the customer detail page, but currently it's only loaded for editors, even though it's always required to get loaded
- The `sw-customer-card` doesn't check the `api_proxy_imitate-customer` correctly, but the `customer.editor` permission. If a user only has the `customer.viewer` &  `api_proxy_imitate-customer` permissions he currently can't use the feature
- The customer list page uses the `salesChannel` association even though only the `boundSalesChannel` data is used. Currently, this loads unused data if the customer does not have a `boundSalesChannel`.

### 2. What does this change do, exactly?
* Changed `sw-customer/acl/index` by moving `sales_channel_domain:read` from `editor` to `viewer` to prevent missing permission messages
* Changed `sw-customer/component/sw-customer-card/index` to inject `contextStoreService` correctly, use `State` instead of `Store` and fix `api_proxy_imitate-customer` acl check
* Changed `sw-customer/component/sw-customer-card/sw-customer-card.html.twig` to fix acl check
* Changed `sw-customer/page/sw-customer-detail/index` by moving `boundSalesChannel.domains` to default criteria to prevent missing template data
* Changed `sw-customer/page/sw-customer-list/index` to only load the `boundSalesChannel` instead of `salesChannel` to only load needed data
* Changed `sw-customer/page/sw-customer-list/sw-customer-list.html.twig` to correctly access `boundSalesChannel` instead of `salesChannel`

### 3. Describe each step to reproduce the issue or behaviour.
- Open the admin customer detail page
- See, that the `boundSalesChannel` data is not loaded correctly
- Also if you have the `api_proxy_imitate-customer` but not `customer.editor` permission you still can't use the feature

### 4. Please link to the relevant issues (if any).
- /

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by ghost** [comment]
@cyl3x There are a few issues with your follow-up changes to my PR. This PR here should fix all of the issues. Please take a look at this so that we can merge this fix soon, so that the customer impersonation feature is not shipped with bugs in 6.6.5.0.

**Comment by cyl3x** [comment]
@akf-bw we have intentionally moved `api_proxy_imitate-customer` and `sales_channel_domain:read` to `customer.editor`. If a user with `customer.viewer` + `api_proxy_imitate-customer` is allowed to log in as a customer, he will be able to change all customer details, just like a `customer.editor` would be able to do. So we don't want to allow a viewer to impersonate a customer.

**Comment by ghost** [comment]
@cyl3x The administrator needs to grant the user the `api_proxy_imitate-customer` permission for this to work, so the administrator is aware of this. With the current implementation, the permission `api_proxy_imitate-customer` has no effect at all and could be removed.
Also the `sales_channel_domain:read` is needed because the `sw-customer-card` checks the domains of the boundSalesChannel now, also for viewers to display the button as disabled correctly

**Comment by cyl3x** [comment]
@akf-bw fine, I'm convinced. Is this PR ready then?

**Comment by akf-bw** [comment]
Should I remove the `api_proxy_imitate-customer` and replace the checks with `customer.editor`? But I think we should use the flexibility of the permission system and have this additional permission.

**Comment by akf-bw** [comment]
Yes, ready to merge

**Comment by akf-bw** [comment]
Yes, ready to merge (I just removed the duplicate permissions check)

**Comment by cyl3x** [comment]
@akf-bw just realised: you cannot delete the sales channel association from `sw-customer-list` as this is a breaking change. I leave it up to you to remove this fix or deprecate it properly.

**Comment by ghost** [comment]
@cyl3x I deprecated `salesChannel` with the 6.7 feature flag

**Comment by ghost** [comment]
image
@cyl3x If you add this association this way the domains of "boundSalesChannel" will not get loaded if it has the same salesChannelId. You would have to use ".addAssociation('salesChannel.domains')" like i did before.
Maybe also add it behind a 6.7 deprecated feature flag.

Will you fix this or should I create a new PR?

**Comment by cyl3x** [comment]
@akf-bw Oh boy, you're right. That's my oversight, I'll fix that

**Comment by mitelg** [comment]
however thanks for your contribution @akf-bw :wink: 👍🎉💙

**Pull request closed without merging**
