### PR TITLE
NEXT-31475 - Added new block to account order history

### PR DESCRIPTION
**Pull request by PheysX**
### 1. Why is this change necessary?
Unify the account welcome block structures.

### 2. What does this change do, exactly?
Added a new block `page_account_orders_welcome_intro` in the order-history `/src/Storefront/Resources/views/storefront/page/account/order-history/index.html.twig` and moved the <p> tag into it.

This new structure now fits with  the following account files:
`src/Storefront/Resources/views/storefront/page/account/profile/index.html.twig`
`src/Storefront/Resources/views/storefront/page/account/payment/index.html.twig`
`src/Storefront/Resources/views/storefront/page/account/addressbook/index.html.twig`

Reformat code style.

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at d837d81</samp>

This pull request adds a new twig block `page_account_orders_welcome_intro` to the order history page of the storefront, which enables more flexibility for customization. It also improves the code style in the address book page of the storefront, by removing unnecessary whitespace and indentation.

### <samp>🤖 Generated by Copilot at d837d81</samp>

*  Add a new twig block to the order history page to enable customization of the introduction text ([link](https://github.com/shopware/shopware/pull/3399/files?diff=unified&w=0#diff-25798deb16dcca64e707f80749830c84761acb55319c372fe93406e9f417fc63R10-R12), [link](https://github.com/shopware/shopware/pull/3399/files?diff=unified&w=0#diff-677f4d67733422f5c30f4efb8c6ca3aa8e59fa1347bc4b55b601b0cd1fbe32d9R1-R12))
*  Reformat the code style in the address book page to remove extra line breaks and indentation ([link](https://github.com/shopware/shopware/pull/3399/files?diff=unified&w=0#diff-d2395533ac24cd138ccb1cee958f9044fa490e389e23d99b262fcceb7ac860d6L8-R11), [link](https://github.com/shopware/shopware/pull/3399/files?diff=unified&w=0#diff-677f4d67733422f5c30f4efb8c6ca3aa8e59fa1347bc4b55b601b0cd1fbe32d9R1-R12))

### CODE REVIEW

**Review by tobiasberge — APPROVED** [review]
Hi @PheysX,

thank you for your contribution. 🎉 LGTM. Now it's also more aligned now with the "addressbook" template.

**Comment by tobiasberge** [comment]
@PheysX Your changes were merged to `trunk`: https://github.com/shopware/shopware/commit/a0ac3db8643f9a623aff0786a025bb8278fbb62d

**Comment by PheysX** [comment]
Can i get a hacktoberfest label :D its not recognized because u closed it. @tobiasberge

**Comment by tobiasberge** [comment]
I'm innocent the Bot 🤖 closed it 😆

But I forgot to set the `hacktoberfest` label, thx @mitelg

**Pull request closed without merging**
