### PR TITLE
Fix exception in ElasticsearchIndexer

### PR DESCRIPTION
**Pull request by tyurderi**
### 1. Why is this change necessary?
When updating the **same** `order_line_item` in the **same** request **multiple** times, it throws the following exception:

image (9)

The root cause is that the method `\Shopware\Core\Content\Product\Stock\OrderStockSubscriber::beforeWriteOrderItems` will not find any changeset for the second update of the entity, which is not yet catched in the ElasticsearchIndexer class.

### 2. What does this change do, exactly?
It adds a condition that checks if the array `$documents` is empty and stops further handling of the indexing message to prevent creating an empty request body, which results in the exception at a later point.

### 3. Describe each step to reproduce the issue or behaviour.
At first, you need to have your Shopware instance set up with elasticsearch. We encounted the problem within our plugin NetiNextEasyCoupon but there is some code that reproduces the issue. It is only an example to reproduce the behavior, we are not updating the same order_line_item with the same data twice.

```php
$changes = [
    'id' => '019325bed02073519c5232a942d3b106',
    'referencedId' => '019169ccaf517030ae85a115ccee1444',
    'productId' => '019169ccaf517030ae85a115ccee1444',
    'payload' => [
        'productNumber' => 'SW10005',
    ]
];

$this->orderLineItemRepository->update([ $changes ], $context);
$this->orderLineItemRepository->update([ $changes ], $context);
```

Make sure to replace the IDs in the payload with valid values of an order_line_item row.

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by AydinHassan** [comment]
@tyurderi maybe also `ProductStockAlteredEvent` should not be dispatched if there are no changes ?

**Comment by mitelg** [comment]
thanks @tyurderi 

would be nice, if you could put your code snippet for the reproduction into a test :wink:

**Comment by tyurderi** [comment]
@mitelg unfortunately we are currently very limited in time, do you have a hint how the test should be implemented?

**Comment by h1k3r** [comment]
Hey @tyurderi ,

thank you for your contribution 🎉 

I am importing you mr, so no need to add test.

I will get back with updates in the comments later.

**Comment by h1k3r** [comment]
Hi @tyurderi ,

thanks again for your contribution!

After short discussion in the team, we've decided to replace [return in your change](https://github.com/shopware/shopware/pull/5467/files#diff-b3a1309b729eff5a91a31b2e8d7ba0c574a1c72930eb7db37ca6dfc621ea2284R294) with throwing a domain exception, so we would not silence occurrences of dispatching index messages with empty ids list. You PR with this adjustment should be merged soon.

The issue itself should be solved with this StockStorage change https://github.com/shopware/shopware/commit/78a29cbba8b3c43e6bec7a9f2e58a96cbf4768bf 
Could you confirm, or do you experience other cases of invalid indexing messages?

Would be happy to hear your feedback!

**Comment by tyurderi** [comment]
@h1k3r yes, we will take a look at the mentioned fix today if it solves our problem, too. I'll come back later to this

**Comment by tyurderi** [comment]
Hi @h1k3r, the commit https://github.com/shopware/shopware/commit/78a29cbba8b3c43e6bec7a9f2e58a96cbf4768bf fixes the issue for us! Can we expect that the bug fix will be released with the upcoming SW 6.6.x.x version?

**Comment by mitelg** [comment]
@tyurderi the fix will be part of the upcoming 6.6.9.0

**Comment by h1k3r** [comment]
Hey @tyurderi ,

your PR was merged!

Thank you for your work! 💙

**Pull request closed without merging**
