### PR TITLE
NEXT-33739 - Improve profiler repository tracer

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
Sometimes it can be difficult to understand which parts of the code are not sufficiently optimized.
There is the wonderful shopware profiler for this, which perfectly shows where the code is slow.
However for repository calls, this currently only works for the "search" method from the EntityRepository class, but not for "aggregate" & "searchIds" methods or the 3 "search", "aggregate" & "searchIds" methods of the SalesChannelRepository class.
As a result, important information about possible optimization areas is currently being lost.

Before:
image
After:
image

### 2. What does this change do, exactly?
- Changed the `searchIds` method in `EntityRepository` to use the profiler, if a criteria title is given
- Changed the `aggregate` method in `EntityRepository` to use the profiler, if a criteria title is given
- Changed the `search` method in `SalesChannelRepository` to use the profiler, if a criteria title is given
- Changed the `aggregate` method in `SalesChannelRepository` to use the profiler, if a criteria title is given
- Changed the `searchIds` method in `SalesChannelRepository` to use the profiler, if a criteria title is given

### 3. Describe each step to reproduce the issue or behaviour.
- Open a storefront page with the profiler enabled

### 4. Please link to the relevant issues (if any).
/

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Nice one, we can delete than the custom logic inside https://github.com/shopware/opentelemetry/blob/main/src/Instrumentation/DALInstrumentation.php 👍

**Comment by shyim** [comment]
Thanks!

**Comment by ghost** [comment]
@shyim can we remove the suffixes ("::search", "::aggregate", "::searchIds") which you added with the merge to trunk?
Before the suffixes you could just copy the full name from the performance tab and search for it in the code. Now you must remove the suffix, otherwise you can't find the criteria.
It also doesn't feel right that these criteria get an automatic suffix, since a criteria needs to have a special title set anyway for it to appear in the list.
As the criteria is already in the 'repository' or 'saleschannel-repository' area we already know what it is in the profiler.

**Comment by shyim** [comment]
I changed it back should be merged soon

**Pull request closed without merging**
