### PR TITLE
NEXT-00000 - Improve file validation service

### PR DESCRIPTION
**Pull request by lacknere**
### 1. Why is this change necessary?

1. The file validation service does not allow uploads of files with filenames containing dots.
2. Some mime types are missing in the default mime type mapping.
3. The file validation service is not decoratable. There is no easy way to override/extend the mime type map and the check functions.

### 2. What does this change do, exactly?

1. Fix extension check for filenames containing dots.
2. Add missing mime types.
3. Add file validation service provider.

### 3. Describe each step to reproduce the issue or behaviour.

1. Upload a file to a digital product containing dots in the filename (e.g. SwagPlugin-1.0.0.zip) > error occurs
2. Upload a `.wma` file to a digital product > error occurs with `wma` listed in supported file extensions
3. No issue, just an improvement

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at d33a956</samp>

This pull request improves the file validation service in the administration app by adding missing mime types, fixing a bug, adding tests and a changelog entry. The file validation service can be used to check the validity of uploaded files by extension or mime type. The changes affect the files `main.ts`, `main.spec.js`, `file-validation.service.ts`, `file-validation.service.spec.js`, `global.types.ts` and the changelog.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at d33a956</samp>

*  Add a file validation service to the administration app, which checks if a file has a valid extension based on the accept string ([link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7b09f23983f00d5f9e7d1408c39822af96c3a5a091b1bd728b120edfcbbc7a97R1-R11), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7201b4a5ccf48d0520a33ea4e9e81d491360355afcad50001e936741bfc0a673R49), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7201b4a5ccf48d0520a33ea4e9e81d491360355afcad50001e936741bfc0a673R216-R218), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR31), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eL43-R54), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR60), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR67), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR73), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eL98-R108), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR162-R163), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7771e93fc6bb6f791782d447b4c86e0bf88c6bcd11a2d2979914709a1e081dbeR86), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7771e93fc6bb6f791782d447b4c86e0bf88c6bcd11a2d2979914709a1e081dbeR212))
*  Fix a bug in the `checkByExtension` function of the file validation service, which used the second part of the filename as the extension instead of the last part ([link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eL98-R108))
*  Add missing mime types for various file formats to the `extensionByType` map of the file validation service, which maps mime types to file extensions ([link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR31), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eL43-R54), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR60), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR67), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-ca8d68b7d2c8d0ef8ec55ddbb202722ef72d2dfb5b1b9bd0c861ec9a6ba3ba3eR73))
*  Add tests for the file validation service, verifying the behavior of the `checkByExtension` function and the service provider factory ([link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7904db6c31402e9b4fcfcdfbb14c2c2f93cadeb5b74ddd8cd19b780c61b17f20R40), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7904db6c31402e9b4fcfcdfbb14c2c2f93cadeb5b74ddd8cd19b780c61b17f20R170-R172), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7904db6c31402e9b4fcfcdfbb14c2c2f93cadeb5b74ddd8cd19b780c61b17f20R271), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-7904db6c31402e9b4fcfcdfbb14c2c2f93cadeb5b74ddd8cd19b780c61b17f20R401-R404), [link](https://github.com/shopware/shopware/pull/3452/files?diff=unified&w=0#diff-136a5b5f38f6b1c06a547c306e4b630f518434a22b0d024db59127a67a0f37c9R66-R77))

### CODE REVIEW

**Review by jleifeld — APPROVED** [review]
Thanks for your contribution 🎉 

It looks good. I will prepare the internal merge 👍

**Comment by lacknere** [comment]
@jleifeld After reviewing my changes I've found out that I forgot to change the implementation of the file validation service in the `sw-media-upload-v2` component to service injection which was the initial intention. I've added that with my last commit.

**Comment by lacknere** [comment]
@jleifeld I don't know if you've seen my last [comment](https://github.com/shopware/shopware/pull/3452#issuecomment-1837614217) because the latest commit is missing in the merge. Should I create a new PR for that [change](https://github.com/shopware/shopware/pull/3452/commits/af77c34fa606a95368bfc5bf13fac9b4ee0c1d8a)?

**Comment by mitelg** [comment]
hey @lacknere 
it was already merged with https://github.com/shopware/shopware/commit/dbb81edff3d58a292802801207d05997f662ee8c
if something is missing a new PR would be nice :ok_hand: 
anyway thanks for your contribution 👍🎉💙

**Pull request closed without merging**
