### PR TITLE
Fix inadequate entity definition resolving in Elasticsearch filter parsing that show when filtering for a translated field of a related entity is executed

### PR DESCRIPTION
**Pull request by SpiGAndromeda**
### 1. Why is this change necessary?

If a filter is applied on an Elasticsearch query that uses a translated field of an entity that is related to the product entity, a `RuntimeException` is thrown in the `getTranslatedField`method of the `EntityDefinitionQueryHelper`.

The filter parsing uses the `getField` method of the `EntityDefinitionQueryHelper` to get the field even if the field name contains relations. The same is not done for the definition itself. As the root definition is passed to the value parsing this would mostly lead to a null return of the `getField` method, which is unexpected behavoir. However, if the field is `TranslatedField, the `getTranslatedField` method is called. This method only searches for the field in the fields of the passed translation (without deeper resolving). The field won't be found an an execption is thrown indicating that the property is missing.

### 2. What does this change do, exactly?

This change introduces a private `getDefinition` method in the `CriteriaParser` to resolve the definition over it's relations to a definition that actually contains the field. This method is called in the `parseEqualsAnyFilter` method, the `parseEqualsFilter` method and the `parseRangeFilter` method. The original definition will still be used for the query creation. If the field does not exist in the resolved entity, an exception is still thrown.

### 3. Describe each step to reproduce the issue or behaviour.

The bug only occurs on translated fields of entities that are related to the product entity. One example is the `shortCode` field in the unit entity. The exception will be thrown if a filter (equals, equals any or range) is applied to this field.

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @SpiGAndromeda 

thanks for you contribution :+1: 

is there a reason, why you targeted the 6.5 branch instead of the current development "trunk" branch? 
It might be, that the problem is already solved in more recent versions. If that would be the case, we can probably backport the fix to 6.5

**Comment by SpiGAndromeda** [comment]
> is there a reason, why you targeted the 6.5 branch instead of the current development "trunk" branch? It might be, that the problem is already solved in more recent versions. If that would be the case, we can probably backport the fix to 6.5

There is an issue for 6.6 (trunk) as well: https://github.com/shopware/shopware/issues/3743
But some implementation details changed between 6.5 and 6.6. If it's accepted for 6.5, I would implement it in 6.6 as well, but this might look different.

**Comment by mitelg** [comment]
we need to go the other way around :slightly_smiling_face: First implementing it on trunk, and then we can backport the solution. 

I will handover to the respective team

**Comment by SpiGAndromeda** [comment]
> I will handover to the respective team

I can do that as well. I'll create a new Branch and new PR.

**Comment by SpiGAndromeda** [comment]
> we need to go the other way around 🙂 First implementing it on trunk, and then we can backport the solution.
> 
> I will handover to the respective team

Created a new branch (with improvided bugfix) and a new PR. Referenced this one there.
https://github.com/shopware/shopware/pull/5739

**Comment by mitelg** [comment]
thanks, I will close this one

**Pull request closed without merging**
