### PR TITLE
Add heading elements for account login page to improve accessibility & SEO

### PR DESCRIPTION
**Pull request by jesperingels**
### 1. Why is this change necessary?
This change is necessary to enhance the accessibility of the account login page. Proper use of heading tags is a key principle of accessible web design as outlined by the Web Content Accessibility Guidelines (WCAG). Not only do they help screen reader users understand the structure and navigate the content more effectively, but they also provide semantic meaning to the document for assistive technologies. Additionally, although SEO is not a primary concern for a login/signup page, having a well-structured document is a good practice and ensures consistency across the platform.

### 2. What does this change do, exactly?
The change introduces h2 heading tags to the login-card and register-card sections of the account login page. Ideally you would also want an h1 element on the page, but this currently doesn't exist and I'd say the login-card and register-card are equal to each other in importance.

### 3. Describe each step to reproduce the issue or behaviour.
- Go to the account login page e.g. https://shopware.bluebirdday.io/account/login 
- Inspect the login-card & register-card title
- They are not wrapped in a heading element

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mstegmeyer** [comment]
Hey @jesperingels, this kind of messes up the design and makes the headings much larger. I can understand, why we should have the h2 tags, but maybe we should add some CSS to make the headings smaller again. @tobiasberge, what do you think?

**Before**
before

**After**
after

**Comment by tobiasberge** [comment]
Hey @jesperingels @mstegmeyer, in general I think it's a good idea to change it to a heading. But the design should not change in this way with this huge texts.

Couldn't we use the h2 directly as the `card-title`? This is also how Bootstrap recommends it in their docs: https://getbootstrap.com/docs/5.3/components/card/

```html
<h2 class="card-title">Card title</h2>
```

Probably this also solves the styling issue. If not I am also happy to have some small additional styling to keep the text size.

**Comment by jesperingels** [comment]
Hi @tobiasberge @mstegmeyer, I pushed some new changes like Tobias suggested. The styling of the heading element is now the same as before

**Comment by tobiasberge** [comment]
Thanks @jesperingels, looks good to me. 👍

**Comment by mstegmeyer** [comment]
Your PR has been merged. Thank you for your contribution 💙 🎉 
Fixed in 2b955ef

**Pull request closed without merging**
