### PR TITLE
[Bugfix] Fix minification for storefront themes

### PR DESCRIPTION
**Pull request by mynameisbogdan**
### 1. Why is this change necessary?
Currently theme minification doesn't work in non-debug env like `prod` due to `Autoprefixer::compile` using default argument `$prettyOutput = true`.

### 2. What does this change do, exactly?
Updates `scssphp/scssphp` to 1.6.0 to use `OutputStyle::COMPRESSED` and pass `$this->debug` to `Autoprefixer::compile`.

### 3. Describe each step to reproduce the issue or behaviour.
`bin/console theme:compile --env=prod` and check any of `public/theme/*/css/all.css`

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by J-Rahe** [comment]
Hey : )
We've just set your PR to “Scheduled”.
This means our initial screening is passed.
Your PR will now be reviewed and tested before being put trough our internal extended testsuite and review process.
We will keep you informed wether something has to be done by you or when the PR is merged : )
If you have any questions feel free to ask.

**Comment by mynameisbogdan** [comment]
Hello, any updates on this PR?

**Comment by NiklasLimberg** [comment]
Hi,
sorry that it took  so long  to import this. Now it's really imported and in internal code review

**Comment by NiklasLimberg** [comment]
Hi,
we can't realy use your changes you made after we had imported this PR. I rebased this myself and the review is almost trough so yeah I'm sorry to tell u wasted your time rebasing this. But on the bright side this is almost merged

**Comment by mynameisbogdan** [comment]
Hi,

Ok. sorry to hear that. At least the minification would be fixed in prod, as intended.

Thank you.

**Comment by NiklasLimberg** [comment]
Well I have more bad news for you we probably won't merge this before the next mayor version. We tested the newer versions of `scssphp` with a few themes/plugins and it seems that it handles media queries differently then before. It wasn't anything mayor, but we are still hesitant to bring this in a minor version and potentially break things.

In short we haven't forgotten this PR, but it just has to wait.

**Comment by mynameisbogdan** [comment]
hi @NiklasLimberg,

At least pass `$this->debug` to `Autoprefixer::compile` since by default `$prettyOutput` is set to `true`. Currently the minification is disabled in production (non-debug) and many shops are receiving a bad score on pagespeed due to this.

**Comment by NiklasLimberg** [comment]
Sure pls make another PR with just those changes. I will then fast track it and it will then probably be included in the minor version.

**Comment by mynameisbogdan** [comment]
It seems to be fixed 10 days ago in 44c7e523eb4aadc43031252035a8422d236cb271.

So this PR is no longer of use.

**Comment by NiklasLimberg** [comment]
Well the update of `phpscss` will be your commit later this year

**Pull request closed without merging**
