### PR TITLE
[NEXT-26062] add missing paid transaction state

### PR DESCRIPTION
**Pull request by stepan-twnty**
### 1. Why is this change necessary?
Need fix bug which open here:
https://issues.shopware.com/issues/NEXT-24586
https://issues.shopware.com/issues/NEXT-26062

Also here is conversation with Shopware developer https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1681413118802549

### 2. What does this change do, exactly?
Just add additional paid status Failed in order to not break loop

### 3. Describe each step to reproduce the issue or behaviour.
Need fix bug which open here:
https://issues.shopware.com/issues/NEXT-24586
https://issues.shopware.com/issues/NEXT-26062

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-24586
https://issues.shopware.com/issues/NEXT-26062

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

copilot:summary

copilot:walkthrough

### CODE REVIEW

**Comment by stepan-twnty** [comment]
this is my first PR
if smth wrong let me know

**Comment by keulinho** [comment]
Hey @stepan-twnty,

thank you very much for your contribution! :tada: :blue_heart: 

Can you please also add a small testcase to verify your change to this class: `\Shopware\Tests\Unit\Core\Checkout\Cart\Order\OrderConverterTest`

And please also add a little changelog entry according to [this guide](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md). (You can leave out the ticket number, we'll add that later as your PR will get it's own ticket number)

**Comment by stepan-twnty** [comment]
> Hey @stepan-twnty,
> 
> thank you very much for your contribution! 🎉 💙
> 
> Can you please also add a small testcase to verify your change to this class: `\Shopware\Tests\Unit\Core\Checkout\Cart\Order\OrderConverterTest`
> 
> And please also add a little changelog entry according to [this guide](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md). (You can leave out the ticket number, we'll add that later as your PR will get it's own ticket number)

Hi :)
Thx for answering. 

You are right I should add test case and changelog BUT not sure if this pull request is still relevant cuz on Slack I've gotten message: 
image

Looks like problem is complex :)

What do u think should we close it?

**Comment by stepan-twnty** [comment]
looks like @nguyenky fixed it and merge it to the Trunk.
So it can be closed.

**Pull request closed without merging**
