### PR TITLE
Do not alter distPath for symlinked themes

### PR DESCRIPTION
**Pull request by discordier**
### 1. Why is this change necessary?

When plugins are installed via path repository and therefore symlinked, they will not get detected as being installed in `/vendor` due to usage of `realpath()` when the base path is determined.

### 2. What does this change do, exactly?

This corrects the behaviour to only change the path
from `plugin-base/src/Resources`
to   `plugin-base/src/<TechnicalName>/Resources`
when the first one does not exist.

### 3. Describe each step to reproduce the issue or behaviour.

1. Create a theme plugin in `custom/static-plugins/dummy-theme` and populate `composer.json` like ususal (technical name ` DummyTheme`).
2. Create some assets and compile them to have the `dist` directory populated.
3. Install it via composer and the default path repository in `composer.json` - you should now have a symlink `vendor/dummy-vendor/dummy-theme => custom/static-plugins/dummy-plugin`.
4. Compile the theme `bin/console theme:compile`, you should see warnings that dist files could not be found at ` custom/static-plugins/src/DummyTheme/Resources/...`.

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by discordier** [comment]
Is there anything I can do from my side to assist?

**Comment by ssltg** [comment]
@discordier sorry, no. I just missed this one. Thought I already imported it. 👍

**Comment by discordier** [comment]
I'm a little lost how to proceed here... the Bot created an issue for this PR which got moved back due to tracker migration to here in a new issue.

Yet nobody seems to check this PR.
Shall I continually rebase?
Is anything needed from me?

**Comment by ssltg** [comment]
@discordier sorry for the delay.
you need nothing to do. The PR was stuck in our internal pipeline and will bee merged next week. The issue inception is because of our move to github issues. This PR and the issues will be closed as soon as we merged your changes.
thank again for your contribution,

**Comment by ssltg** [comment]
Hi @discordier ,

sorry for the delay again. The ThemeCompiler was changed multiple times since this PR and is currently in a not mergable and not rebaseable state. Would you mind to check again if the problem still exists, and update your change to the current version?

Kind Regards

**Comment by ssltg** [comment]
Hi @discordier ,

as mentioned above this commit is outdated and not mergable right now. We will close this PR for now. Fell free to reopen it when you updated the change (if it is still applicable).

Regards.

**Pull request closed without merging**
