### PR TITLE
To get the [request object] in the [cart hook] and to be able to call the cart hook [with parameters]...

### PR DESCRIPTION
**Pull request by codixio**
... the request object is needed. E.g. to manipulate the line items in the cart. In a custom hook I do not have the services.cart object available.

### 1. Why is this change necessary?

Extends the cart hook with the possibility to read the request object to pass parameters to the cart hook.

### 2. What does this change do, exactly?

Adds RequestFacadeFactory::class in the getServiceIds array.

### 3. Describe each step to reproduce the issue or behaviour.

services.request.query is not available before, but it is with this addition now

{% if services.request.query.foo === 'bar' %}
    {# clear the cart #}
{% endif %}

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 5704944</samp>

Added `RequestFacadeFactory` dependency to `CartHook` class to simplify request handling. This is part of a pull request to improve cart performance.

### <samp>🤖 Generated by Copilot at 5704944</samp>

*  Add `RequestFacadeFactory` as a dependency for `CartHook` ([link](https://github.com/shopware/platform/pull/3263/files?diff=unified&w=0#diff-de8814704d5ecaaa336e408316b665e5588b29b954ad22dc61362be2bd54217eR51))

### CODE REVIEW

**Comment by OliverSkroblin** [comment]
Hi @codixio,

first, thanks for the contribution. But I would recommend implementing it the other way around. Instead of giving access to the request in the cart hook (which can be any request), I would recommend releasing the cart service in the /store-api/script/{hook} endpoint to pass data and operations to the cart.

**Comment by codixio** [comment]
> I would recommend releasing the cart service in the /store-api/script/{hook} endpoint to pass data and operations to the cart.

Thank you. That means I need to change the PHP script "src\Storefront\Framework\Script\Api\StorefrontHook.php" like this?

    public static function getServiceIds(): array
    {
        return [
            RepositoryFacadeHookFactory::class,
            SystemConfigFacadeHookFactory::class,
            SalesChannelRepositoryFacadeHookFactory::class,
            RepositoryWriterFacadeHookFactory::class,
            ScriptResponseFactoryFacadeHookFactory::class,
            RequestFacadeFactory::class,
            CartFacadeHookFactory::class,
            PriceFactoryFactory::class,
        ];
    }

**Comment by codixio** [comment]
> I would recommend releasing the cart service in the /store-api/script/{hook} endpoint to pass data and operations to the cart.

Daniel Neustadt mendioned on stackoverflow:

"There's also the [storefront-{hook}](https://developer.shopware.com/docs/resources/references/app-reference/script-reference/script-hooks-reference#storefront-hook) which does provide the request data, but not the cart service. And furthermore that hook is dispatched after the cart hook, so you also can't use the request data in one script and pass along data to another script, say as an added state to the Context." (Source https://stackoverflow.com/questions/76870317/shopware6-5-app-how-to-get-form-post-request-or-set-variable-for-a-twig-scripts)

What do you think about it?

**Comment by shyim** [comment]
@codixio yes and StoreAPIHook

**Comment by codixio** [comment]
> StoreAPIHook as well

src\Core\Framework\Script\Api\StoreApiResponseHook.php :

    public static function getServiceIds(): array
    {
        return [
            RepositoryFacadeHookFactory::class,
            SystemConfigFacadeHookFactory::class,
            SalesChannelRepositoryFacadeHookFactory::class,
            RepositoryWriterFacadeHookFactory::class,
            ScriptResponseFactoryFacadeHookFactory::class,
            RequestFacadeFactory::class,
            CartFacadeHookFactory::class,
            PriceFactoryFactory::class,
        ];
    }

**Comment by codixio** [comment]
> What do you think about it?

I think with a page redirect in the case of a given Post parameter, this should work, when the cart facade is available in these two Api hook scripts.

```
{% do hook.setResponse(
    services.response.render('frontend.checkout.cart.page')
) %}
```

**Pull request closed without merging**
