### PR TITLE
Set variables within block if needed

### PR DESCRIPTION
**Pull request by DanieliMi**
### 1. Why is this change necessary?
To be able to overwrite the block `buy_widget_data` and still use `buy_widget_reviews`.

### 2. What does this change do, exactly?
It moves the two variables that are only used within the block into the scope of the block.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create yourPluginsrc/Resources/views/storefront/component/buy-widget/buy-widget.html.twig
2. Extend the parent template `{% sw_extends '@Storefront/storefront/component/buy-widget/buy-widget.html.twig' %}`
3. Overwrite `block buy_widget_data` to only contain `buy_widget_reviews`:
```twig
{% block buy_widget_data %}
    {% block buy_widget_reviews %}
        {{ parent() }}
    {% endblock %}
{% endblock %}
```
4. Open a product with reviews
5. Click the reviews link

**Expected behavior:** The link still works and scrolls to the reviews tab.

**Actual behavior:** Nothing happens
### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by keulinho** [comment]
Hey @DanieliMi, 

moving twig variables into a new block is a breaking change, therefore we can't merge your changes.
As a workaround you could copy & paste the variable declarations into your template override.

To fix this in the platform you can't remove the variables in the original block, but you have to deprecate them there for the 6.5.0 version, and wrap the variable declaration in the new block in a `{% if var is not defined %}` to not override the declaration in the parent block if it was already declared there.

**Comment by DanieliMi** [comment]
Hi @keulinho,  
I have changed the PR accordingly. Will I have to do anything for the 6.5 release or will they be removed automatically due to the deprecation?

**Comment by keulinho** [comment]
LGTM! :blue_heart: 

No nothing to do from your side. We will remove all places that are marked as deprecated when we are starting the work for the 6.5 release.

**Comment by NiklasLimberg** [comment]
Thanks for your contribution 🎉

**Pull request closed without merging**
