### PR TITLE
NEXT-32086 - Improve storefront accessibility

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
In order to provide the best user experience when interacting with forms, it is necessary for the browser's autocomplete feature to help the user as much as possible.
Some autocomplete attributes are currently missing from the storefront. The changes provided will add any missing autocomplete attributes.
The changes also add the theme-color meta attribute to provide the site's theme for the browser window. The sw-background-color value from the theme is used for this.

### 2. What does this change do, exactly?
- Add missing autocomplete attributes to the login & address forms
- Fix type of phone number input. text -> tel
- Add missing theme-color meta attribute with sw-background-color value

### 3. Describe each step to reproduce the issue or behaviour.
- Create a new Shopware 6.5 project (with the production template)
- Open the storefront and check the pages

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 58596fd</samp>

This pull request improves the storefront accessibility and user experience by adding or modifying the `autocomplete` and `type` attributes of various input fields in the login, address and address personal company components. It also adds the `theme-color` meta attribute to the layout meta component based on the sw-background-color theme configuration. Additionally, it updates the changelog with a file describing the changes.

### <samp>🤖 Generated by Copilot at 58596fd</samp>

*  Add a changelog entry for improving storefront accessibility ([link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-5d205ba268370bfbaa7c0e2e25be2cf3b1b16da2a269c76985aa80b44eb947bbL1-R9))
*  Add autocomplete attributes to the input fields for email and password in the login form ([link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-3a6d48e55e5dfd3791c1532088cc4d8d2b6499f75d650b6333b2568fd0fa93ecR69), [link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-3a6d48e55e5dfd3791c1532088cc4d8d2b6499f75d650b6333b2568fd0fa93ecR89))
*  Add autocomplete attributes to the input fields for company name, street name, zip code, city name, additional address line, third address line and phone number in the address form. The autocomplete values depend on whether the address is for shipping or billing purposes ([link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-bec516e908622f4a6c0862196e64e5a62997373658b915cd3153f73fd04253ffR38), [link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-bec516e908622f4a6c0862196e64e5a62997373658b915cd3153f73fd04253ffR124), [link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-bec516e908622f4a6c0862196e64e5a62997373658b915cd3153f73fd04253ffR163), [link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-bec516e908622f4a6c0862196e64e5a62997373658b915cd3153f73fd04253ffR199), [link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-bec516e908622f4a6c0862196e64e5a62997373658b915cd3153f73fd04253ffR255), [link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-bec516e908622f4a6c0862196e64e5a62997373658b915cd3153f73fd04253ffR290), [link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-bec516e908622f4a6c0862196e64e5a62997373658b915cd3153f73fd04253ffL411-R419))
*  Add autocomplete attribute to the input field for company name in the address personal company component ([link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-ce5166b9e2507f727de393ff529dd9c76671e54515ff0c3f5b7bc46f2e239c5aR28))
*  Add a block for the theme-color meta attribute with the value of the sw-background-color theme configuration in the `meta.html.twig` file. The theme-color meta attribute is only added if the sw-background-color theme configuration is set ([link](https://github.com/shopware/platform/pull/3206/files?diff=unified&w=0#diff-2e796fc5ee063153d3d9c90d03647b9e0a9cf6cea089a8133aaf386c1777e6b9R70-R76))

### CODE REVIEW

**Comment by tobiasberge** [comment]
Hi @akf-bw, thank your for your contribution 🎉 and apologies for the long delay. We will now import and process your PR.

**Comment by ghost** [comment]
@tobiasberge I rebased my changes to the latest trunk commit. I also changed the autocomplete from the login email form to "username webauthn", which is generally better supported and should be used even if it's an email input.

**Comment by tobiasberge** [comment]
Hi @akf-bw thank you for your effort. I tested it locally with a saved address in Google Chrome autofill feature and it works fine for me in general 👍 

In login/register the form is auto filled correctly. Also when fields are added (via admin) which are not yet covered by autofill. I'm not sure about birthday for example, in chrome there is no field for it in the autofill addresses feature.

The distinction between billing/shipping doesn't quite work for me when using the "Shipping and billing address do not match." checkbox that shows more fields. When autofilling this form not all fields are filled and some of the other form are filled as well. I think it is because they already belong to each other because of the scoping via `autocomplete="section-personal given-name"`.

### Default:
autofill_1

### Extra fields:
autofill_2

### Billing/Shipping:
autofill_3

**Comment by tobiasberge** [comment]
Hi @akf-bw, if the "Shipping billing do not match" case is too much effort for now I'm also happy to take the change as it is. I tested again and the "Shipping billing do not match" did also not work well with autocomplete before this change. And adding the autocomplete to more fields is still an improvement over the current implementation. I was just wondering if it was supposed to work with billing/shipping in this PR or not.

**Comment by ghost** [comment]
Hey @tobiasberge,

you can merge the current PR as it is.

**Comment by tobiasberge** [comment]
Hi @akf-bw, your changes have been merged to trunk: 🎉 https://github.com/shopware/shopware/commit/adc7c18e02cb60ab0e8271a37e2195a8bda02c59

Thank you for your effort.

**Pull request closed without merging**
