### PR TITLE
NEXT-29293 - Fix Inter variable font files apache incompatibility

### PR DESCRIPTION
**Pull request by lacknere**
### 1. Why is this change necessary?
Apache negotiation module treats `Inter-*.var.woff2` files as type maps because of the `.var` in their filename (https://httpd.apache.org/docs/2.2/content-negotiation.html). Therefore any request of the font file leads to a 500 internal server error and the fallback font is used.

### 2. What does this change do, exactly?
~~Renaming all variable font files from `Inter-*.var.woff2` to `Inter-*.variable.woff2`.~~
Renaming all Inter font files to match the pattern `Inter-[FontWeight]-[FontStyle]-[FontSubset]`.

### 3. Describe each step to reproduce the issue or behaviour.
Use any browser supporting `font-variation-settings: normal` and go to any Storefront page of a Apache Shopware 6.5 setup > font request in network tab of debugging tools results in 500 internal server error and fallback font is used.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-29293

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 1de7f7a</samp>

Fix apache incompatibility with Inter variable font files. Replace the `.woff2` files with the `.woff` versions and update the `inter.scss` file accordingly.

### <samp>🤖 Generated by Copilot at 1de7f7a</samp>

*  Fix the issue of Inter variable font files not being served correctly by apache servers by adding a .htaccess file to the web/fonts folder that sets the correct content-type header for the .woff2 files ([link](https://github.com/shopware/shopware/pull/3400/files?diff=unified&w=0#diff-10b0fc07b087b5b9414f96883043283381fc7902ca9ec010bf573aee689e198bR1-R9), )

### CODE REVIEW

**Comment by shyim** [comment]
Maybe use `-` instead of dot, so we just have woff2 as extension

**Comment by lacknere** [comment]
@shyim I thought about that as well. In the end I couldn't decide where to put the `-var`. Possibilities were after the font name (`Inter-roman-var.latin.woff2`) or after the subset version name (`Inter-roman.latin-var.woff2`). So using the dot version with `variable` seemed cleaner to me because the subset version is separated with a dot as well. What are your thoughts on that?

Edit: additionally we could replace the subset version dots with `-`. That would also be clean in my opinion 😃

**Comment by shyim** [comment]
I would replace with with `-` to just have one extension to make it even clearer 😅

**Comment by lacknere** [comment]
Since there were generally different naming conventions for the font files, I have now decided to name all files according to the same pattern `Inter-[FontWeight]-[FontStyle]-[FontSubset]`.

**Comment by tobiasberge** [comment]
Hi @lacknere, thank you for your contribution. We have merged your changes into `trunk`: https://github.com/shopware/shopware/commit/ca861b4777c44d5b7610875c5866b409217b4de9 🎉

**Pull request closed without merging**
