### PR TITLE
NEXT-32039 Fix UrlEncodingTwigFilterTest

### PR DESCRIPTION
**Pull request by raffaelecarelle**
I've fixed the UrlEncodingTwigFilterTest tests.

- The change is necessary for keep the test green.

- I've added the path to media entity. It is mandatory for generate the url params from media.

### CODE REVIEW

**Comment by keulinho** [comment]
Hey thanks for your contribution! :blue_heart: :+1: 

Can you please sign the [Contributor License Agreement](https://cla-assistant.io/shopware/shopware?pullRequest=3450)? Otherwise we can't accept your PR. It seems like the email address you used to commit the changes is not associated with you github user account, so if you already have accepted the CLA, either add the email address you used for committing to your github account or create a new PR where you use an email address associated with your github account as the author email.

**Comment by raffaelecarelle** [comment]
Hello @keulinho, thank you for reply. I changed my email and accepted the CLA.

Regards.

**Comment by keulinho** [comment]
Thanks for the quick response and follow up, sadly it is still a bit messed up:
image

How i see it seems that the author email is recognized by github, but it does match the author email :thinking:

**Comment by raffaelecarelle** [comment]
I've added the second email to github. 

Now it seems to be ok.

**Comment by SilasHachmann** [comment]
Thanks for your contribution @raffaelecarelle . It's merged! :partying_face:

**Pull request closed without merging**
