### PR TITLE
Rename PluginListCommandTest::testCommand.txt to PluginListCommandTest-testCommand.txt so it is possible to checkout repository on Windows.

### PR DESCRIPTION
**Pull request by xrogers**
### 1. Why is this change necessary?
So it is possible to checkout platform repo on Windows.

### 2. What does this change do, exactly?
Remove the special characters from the test file.

### 3. Describe each step to reproduce the issue or behaviour.
Try to checkout current trunk of platform on Windows.

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Do you know there is something to detect this in CI?

**Comment by xrogers** [comment]
On github probably simple workflow which clones the repository on windows VM, like:
```
name: Windows clone check

on:
    push:
      branches:
          - trunk
    pull_request:

jobs:
  build:
    runs-on: windows-latest
    name: "Windows check"

    steps:
    - name: Clone platform
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
```

**Comment by xrogers** [comment]
Just added workflow, but it wasn't tested

**Comment by shyim** [comment]
Thanks for your Contribution! 💙

**Pull request closed without merging**
