### PR TITLE
NEXT-25538 - Replace to any media

### PR DESCRIPTION
**Pull request by DrUlysses**
### 1. Why is this change necessary?
Default value of the uploader is currently image only. Since it is base for all types of uploads it is better to have default value universal as well.

### 2. What does this change do, exactly?
Sets default value of fileAccept in sw-media-upload-v2 to */* from image/*

### 3. Describe each step to reproduce the issue or behaviour.
Upload any type of media as admin
Choose replace this media
Popup will allow to choose images only
Even if you will choose all files instead of images and will try to upload it - the shopware will flash an error

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-25538

### 5. Checklist

- [ + ] I have rebased my changes to remove merge conflicts
- [ - ] I have written tests and verified that they fail without my change
- [ + ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ - ] I have written or adjusted the documentation according to my changes
- [ + ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ + ] I have read the contribution requirements and fulfil them.

### <samp>🤖 Generated by Copilot at 5337a89</samp>

This pull request allows any file type to be uploaded with the `sw-media-upload-v2` component in the administration. It changes the default value of the fileAccept prop and adds a changelog entry for the change.

### <samp>🤖 Generated by Copilot at 5337a89</samp>

* Allow any file type to be uploaded by the `sw-media-upload-v2` component ([link](https://github.com/shopware/platform/pull/3175/files?diff=unified&w=0#diff-3ae13b89083149052cfa98ffe91d15d545cc5ad8cedbe1da5b7fa42dd9bc7adcL114-R114))
* Add a changelog entry for the pull request ([link](https://github.com/shopware/platform/pull/3175/files?diff=unified&w=0#diff-9cb5f876d0735903786fb8b8850dc9ef179f49de7403e403f8e4b4265dec0850R1-R9))

### CODE REVIEW

**Comment by DrUlysses** [comment]
Should I adjust someting or just wait?

**Comment by celha** [comment]
@DrUlysses, thanks for your contribution :) I just saw that you have merge conflicts. Can you be so kind to rebase your branch so that we can merge it afterward? Thank you!

**Comment by DrUlysses** [comment]
@celha Like this? Excuse me, if I'm doing its wrong

**Comment by bschulzebaek** [comment]
@DrUlysses Hey 👋🏻 Now this changeset doesn't look quite right - this PR should only contain your own changes and your own commits, after rebasing it onto the latest commit of the trunk branch. 

So instead of merging trunk into your own branch, you'd use `git rebase trunk` while having your own branch checked out. I recommend fixing the history on your branch first (i.e. reverting the trunk merge), that'll make the rebase much more convenient 🙂

**Comment by DrUlysses** [comment]
@bschulzebaek Thanks a lot for your advice! Hopefully it looks better now

**Comment by bschulzebaek** [comment]
Hey @DrUlysses, to me it looks like the changeset contains more files than intended - can you double-check? From the changelog and your description I'd only expect the change in the .js file, nothing more. 

Also the commit history is still wrong, but we can take care of that later internally 👍🏻

**Comment by DrUlysses** [comment]
Yo, @bschulzebaek, thank you for notice! 
I have removed excess changes, looks like I have caused them upon rebase.

**Comment by bschulzebaek** [comment]
We just merged your changes with fa1eecdeec20dab87d6fbfdf9ce9d4abbcdc6921 , thanks for the contribution @DrUlysses 💙

**Pull request closed without merging**
