### PR TITLE
Add zebra pattern for detailed permission

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?

Not all ACL permissions are grouped well. So there are times where you have to manually assign them. And it is a lot of work, when you have to activate permissions for each entity. This can get tedious and you get lost in that huge grid. Why not have a zebra pattern to have some visual guidance.

### 2. What does this change do, exactly?

Add zebra pattern to permission grid.

image

### 3. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by flkasper** [comment]
@JoshuaBehrens The zebtra pattern increases the overview in  the visual guidance.
What do you think about the idea of adding a hover that highlights the current line e.g. by using a darker background color and/or making the name bold on the left?

**Comment by JoshuaBehrens** [comment]
@fk-bitsandlikes I already thought about it, yes. One might think that these few lines don't have a lot of thoughts in that 😅 

I ditched the idea as it is only useful for mouse users. As this is very limited to the input device and in combination with the zebra pattern just going darker means that the text readability suffers. So one could work with tinting the row but this is super new as a style feature and needs to be approved by someone like @Weltraumakustik . The more people involved the slower the PR will get merged :( so I rather keep it simple to have it improved in some way.

**Comment by mstegmeyer** [comment]
And the last one for today: Your PR has been merged. Thank you so much for your contribution 💙 🎉

**Comment by JoshuaBehrens** [comment]
Thank you very much for checking and merging all these pull requests :) 🎉

**Pull request closed without merging**
