### PR TITLE
NEXT-00000 - Update OpenApi schema lint

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
- Currently the OpenAPI schema runs everytime something is pushed, we can limit this to only schema changes
- The `State` property of `CartDelivery` is currently wrong

### 2. What does this change do, exactly?
* Changed `01-lint-openapi` to only run on changed schema files & update structure
* Changed `CartDelivery` StoreAPI Schema to correctly use `CountryState` instead of `State`

### 3. Describe each step to reproduce the issue or behaviour.
- Run the `01-lint-openapi` github action

### 4. Please link to the relevant issues (if any).
- /

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
I think it's solved with this one right? https://github.com/shopware/shopware/commit/b2d3142d2a2af9b8288244a018a5ba10f72383af

**Comment by ghost** [comment]
> I think it's solved with this one right? [b2d3142](https://github.com/shopware/shopware/commit/b2d3142d2a2af9b8288244a018a5ba10f72383af)

Ah yes, that's largely the same 😅
But I think https://github.com/shopware/shopware/commit/48f1489bc2b70f5bf12760ae8d57feec7dca14c5#diff-1ed86b61eab11a720d73bb2ab81b6cc9964c8a565042b9b148bb9856910e1126L38 is wrong. This should be a CountryState like in https://github.com/shopware/shopware/blob/trunk/src/Core/Checkout/Cart/Delivery/Struct/ShippingLocation.php#L31

I'll adjust this PR to exclude the already merged changes.

**Comment by akf-bw** [comment]
@shyim, what do you think about the “paths” changes in the workflow file?

**Comment by mitelg** [comment]
thanks for your contribution @akf-bw  👍🎉💙

**Pull request closed without merging**
