### PR TITLE
NEXT-36528 - Add intra community delivery label tax relevant documents

### PR DESCRIPTION
**Pull request by magraina**
### 1. Why is this change necessary?

Tax consultants often require to have the information about intra-community label on all tax relevant documents (i.e. cancellation invoice).

### 2. What does this change do, exactly?

Adding a new option for intra-community delivery to the cancellation invoice and credit notes document settings page and adding a new method, like the one used in the invoice document file generator. This method checks, if the config is enabled and that all the necessary information is provided to show the label.
It adds a new `is_eu` field to the `country` entity to check if the customer is from the EU and a additional setting to adjust this in the countries settings page.
Removes the country selection list for the intra-community label option in the settings page of the documents.

### 3. Describe each step to reproduce the issue or behaviour.

1. Go to Settings -> Documents -> cancellation invoice
2. Activate the intra-community option.
3. Go to orders overview and create or select a order with a shipping address outside of the EU (e.g. United Kingdom).
4. Create a cancellation invoice under documents to this order.
5. An intra-community label should be displayed on the created document.

### 4. Please link to the relevant issues (if any).
[https://issues.shopware.com/issues/NEXT-36528](https://issues.shopware.com/issues/NEXT-36528)

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Bird87ZA** [comment]
Hi @magraina,

Thanks for your MR. Can you please fix the issues mentioned [here](https://github.com/shopware/shopware/pull/3752#issuecomment-2152846890)?

**Comment by magraina** [comment]
@Bird87ZA Sure - Done!

**Comment by Bird87ZA** [comment]
Morning @magraina ,

We had some internal discussion yesterday and would like to understand the reasoning behind adding the EU states to the document config. We foresee a problem doing this where if the EU States change, the config will be outdated. And updating it, would affect all documents, even if they were from a valid EU state before the change. We realise that this functionality already exists in `InvoiceRenderer` so maybe it can be fixed in both places.

I would suggest adding a field to the `document` table that defaults to `false`. Then, when a document is created, a constant list of states is checked against the `country` and that field is then updated to `true`. In this instance, changing of EU States will be done in one place, and will only affect new documents that are created from that point on.

I'd like to hear if you have any other suggestion? Also, would you be willing to update this PR?

**Comment by magraina** [comment]
Hi @Bird87ZA,

I like that suggestion! Especially that this would not affect existing documents in case of a change.
I would suggest to add something like a `is_eu` field to the `country` table, which could then be checked for such functionalities. It could then also be changed independent from the software version when needed.

Sure, I'm willing to update this PR.

**Comment by Bird87ZA** [comment]
Good afternoon @magraina ,

During our internal review process, a question was raised about which documents should have this label. The consensus was that all tax-relevant documents (i.e. invoices, credit notes, cancellation invoices) and also quotation confirmations and delivery bills should have it.

Just thought I'd extend the opportunity to add this to you, as you've already started with this implementation. :)

**Comment by magraina** [comment]
Good afternoon @Bird87ZA,

I will keep that in mind for the implementation.
That might then be a small addition to get that for other documents as well.

**Comment by magraina** [comment]
Good afternoon @Bird87ZA,

I've updated the MR :)

**Comment by Bird87ZA** [comment]
@magraina apologies for only getting back to you now.

A few of the checks and linters are failing. Can you please have a look at it?

Other than that it looks good, and when these issues are fixed, we will merge it :)

**Comment by magraina** [comment]
@Bird87ZA sure!

I couldn't run them locally last week because my setup failed after merging the latest trunk.
So I was hoping for the CI

**Comment by magraina** [comment]
Good afternoon @Bird87ZA,

I've updated the MR :)
Can you run the CI again?

**Comment by Bird87ZA** [comment]
Your PR has been merged! Thanks for your contribution 💙

**Comment by sjerdo** [comment]
@Bird87ZA  Does this migration need a backport to Shopware 6.5? We upgraded some of our SW 6.5.8.13 environments to 6.6.8.2 and experienced the following error:

```
 
  // Warming up the cache for the acc environment with debug false               
 
 
 In ExceptionConverter.php line 67:
                                                                                
   An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'country.is_eu' in 'field list'                   
 
 In Exception.php line 28:
                                                                                
   SQLSTATE[42S22]: Column not found: 1054 Unknown column 'country.is_eu' in 'field list'                                                                  
                                                                                
 
 In Statement.php line 130:
                                                                                
   SQLSTATE[42S22]: Column not found: 1054 Unknown column 'country.is_eu' in 'field list'                                                                  


cache:warmup [--no-optional-warmers]

```

**Comment by magraina** [comment]
@sjerdo This looks to me like if you already have a certain change that requires the whole change from this PR.
The migration itself would solve the initial problem, but you will also need the other changes (e.g. on the UI) for this to work.

**Pull request closed without merging**
