### PR TITLE
Fix disabled theme manager fields

### PR DESCRIPTION
**Pull request by tc-innovations**
## Parameter "editable" in theme.json doesn't work consistently
Thank you very much for helping us with solving our issues regarding the "editable=false" parameter in the theme.json. We appreciate it very much! Unfortunately, both fixes doesn't work consistently.

current
fixed

### 1. Why is this change necessary?
Currently some configuration fields are hidden but leave a blank space in the theme configuration, other theme configuration fields are beeing disabled. Since theme configuration fields cannot be removed without residue, it would be great if this can be aligned.

### 2. What does this change do, exactly?
The adjustment doesn't hide some "editable=false" configuration fields anymore instead it disables all theme configuration fields with the parameter "editable=false".

### 3. Describe each step to reproduce the issue or behaviour.
Add different config fields and set the parameter 'editable' to 'false'. There are some fields available so we've tested the filed types: text, number, color, media, url, textarea, custom, datetime. Some theme configuration fields will be hidden, some will be disabled the url type isn't affected at all.

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-13834
https://issues.shopware.com/issues/NEXT-14550

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by J-Rahe** [comment]
Hey @tc-innovations, we will have to check with our design on how to proceed, i will come back to you once i got an answer.

**Comment by J-Rahe** [comment]
Hey @tc-innovations, thanks for opening the PR. I just talked to a few people and our preferred way to handle this would be to hide fields that are not editable completely. Do you think you could change your PR to that?

If you have any questions or ideas regarding this just ping me : )

**Comment by tc-innovations** [comment]
Hi @J-Rahe, thank you for the review and your feedback. I can try to hide the fields, but this will create "gaps" as shown in the screenshot above.

Wouldn't it be better to make the fields "non-editable" as suggested by us and additionally create a possibility to delete fields without leaving a gap if necessary (see https://issues.shopware.com/issues/NEXT-10994)?
This would allow custom themes to disable fields in the first step and then remove them in the second step.

Looking forward to your reply.

**Comment by J-Rahe** [comment]
Hey @tc-innovations,
Changing the current behaviour of the editable setting is problematic as that would mean everyone using this would have to react and change this if they don’t want to use it in the new way.
I would prefer adding a new option to grey out the fields and have the old option stay as is.
This should also be tested.
(And when you continue working on this, please don’t forget to sign the CLA.)

**Comment by tc-innovations** [comment]
Hi @J-Rahe, well, changes are part of the prozess, just like all templates had to be revised regarding shopware.theme["..."] to theme_config('..'). :-) I will check if I can hide the fields instead of disabling them.

(We've signed the CLA many times, don't know why it is not recorgnized.)

**Comment by J-Rahe** [comment]
@tc-innovations you are using @tc-innovations here but @domenikTC for the commit, did you sign it with the latter one?

**Comment by domenikTC** [comment]
@J-Rahe Thanks for the tip, CLA is now working.

**Comment by J-Rahe** [comment]
Hey  @tc-innovations, 
"I will check if I can hide the fields instead of disabling them." any news on that?

**Comment by tc-innovations** [comment]
@J-Rahe As we are currently extremely busy with development work and support for our products with the changes in Shopware 6.4, we haven't had a chance to look at the Theme Manager yet. We will have another look on it at the end of the week and check if we can hide the corresponding fields.

**Comment by J-Rahe** [comment]
Just wanted to know that you are still on it : )

**Comment by J-Rahe** [comment]
Hey @tc-innovations, has been a bit more than a week : )(and then the 2 weeks after which we normally close incomplete PRs).
I'm closing this for now.
If you manage to get back to this just open a new PR.

**Pull request closed without merging**
