### PR TITLE
NEXT-00000 - Fix / update github pipelines

### PR DESCRIPTION
**Pull request by ghost**
### 1. Why is this change necessary?
- The admin Lint pipeline do not include the generation of admin “entity-schema-types” and therefore the pipeline may fail with errors that are not actually errors
- Some of the pipelines use outdated action releases
- The ECS config does not correctly specify the line ending of the php files
- The `.npmrc` filein the administration is not necessary because the version check is already done by webpack

### 2. What does this change do, exactly?
* Changed `01-lint-admin` github action to build the missing `entity-schema-types` before the code check
* Changed `01-lint-storefront` github action to use the latest action releases
* Changed `01-php-lint` github action to use the latest action releases
* Changed `02-acceptance` github action to not run on pull requests
* Changed `02-unit` github action to use the latest action releases
* Changed `03-redis` github action to use the latest action releases
* Changed `ecs` config to include the lineEnding
* Changed `Migration1620820321AddDefaultDomainForHeadlessSaleschannelTest` to use `RunClassInSeparateProcess`
* Removed the `.npmrc` file, because the node version is already validated by webpack

### 3. Describe each step to reproduce the issue or behaviour.
- Use the actions/workflows described above

### 4. Please link to the relevant issues (if any).
- /

### 5. Checklist

- [X] I have rebased my changes to remove merge conflicts
- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by ghost** [comment]
@shyim, maybe we can also fix the `Unit/PHPUnit for migration,migration-tests` and `Playwright Tests/Docker` pipelines to get all pipelines working again as they are currently always fail due to one error. Could you take a look at them?

**Comment by shyim** [comment]
@akf-bw migrations are flaky. 

I would rewrite the whole playwright workflow; pushing into the docker registry is bad for cross repository PR's 😅 . I would skip if the event is pull_request for now

**Comment by ghost** [comment]
@shyim I fixed it. Now all tests work again for pull requests 🚀

**Comment by shyim** [comment]
Thanks!

**Pull request closed without merging**
