### PR TITLE
Compile theme only for active sales channels

### PR DESCRIPTION
**Pull request by larsbo**
### 1. Why is this change necessary?

If you have lots of sales channels for some reason like testing, design work, etc. the execution of the theme:compile command takes lots of (useless) time:
Bildschirmfoto 2022-11-29 um 12 38 30

### 2. What does this change do, exactly?
Compile themes only for active sales channels.

### 3. Describe each step to reproduce the issue or behaviour.
- Execute `theme:compile` command
- wait
- wait
- more wait
- still waiting...
- grap some mug of coffee
- wait
- and more waiting here
- maybe I should do some more productive stuff now?
- wait
- go outside, got shopping, plant a tree, build a house, oh wait, there was some process running on my computer...
- it's still running -.-
- and waiting
- ...
- process maybe finished someday maybe not - who knows? 😺 

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/NEXT-21505

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

<a href="https://gitpod.io/#https://github.com/shopware/platform/pull/2867"></a>

### CODE REVIEW

**Comment by SebastianFranze** [comment]
Hello @larsbo and thank you for your contribution :)

Could you please apply a test for the changed behaviour?

What about sales channels that are activated later on? Does the shop owner have to run `theme:compile` for this sales channel manually? Is there a potential risk that the reactivated sales channel is not running correctly?

**Comment by larsbo** [comment]
@SebastianFranze 
Ok, I will add a test.

Reactivated sales channels will behave like a new created sales channel: The shop owner can compile the theme afterwards inside the administration in the sales channel details or he can execute `theme:compile` inside the console to compile for all (active) channels at once. Without recompile a reactivated sales channel the storefront might be outdated in some way but it still should work. But I'm not familiar with the details of handling compiled assets in shopware platform I must admit.

Do you think there should be trigger after reactivating a sales channel that forces a re-compile? But maybe this is not always intended?

**Comment by SebastianFranze** [comment]
Hello @larsbo 

I think I got it wrong. We can also have outdated themes right now if the shop owner does not compile themes manually. Sorry for the confusion... :see_no_evil: 

So your implementation is fine but the missing test.

Best regards,  
Sebastian

**Comment by keulinho** [comment]
Thanks again for your contribution! Your PR was finally merged :tada: :blue_heart:

**Pull request closed without merging**
