### PR TITLE
do not assume address exists

### PR DESCRIPTION
**Pull request by Guite**
### 1. Why is this change necessary?
During our tests exceptions occured during login because the `SalesChannelContextRestorer` couldn't properly resolve the address again.

### 2. What does this change do, exactly?
This change checks if an address really exists before trying to set it to the customer. Therewith it makes the whole process a bit more resilient.

### 3. Describe each step to reproduce the issue or behaviour.
Unfortunately I couldn't reproduce it for myself. Instead I activated the debug mode and asked my client to retry so he could send me the stack trace:

image

I can't rule out the possibility that a plugin is involved in the problem, but I thought it wouldn't hurt to check for the existence of the objects before passing them to a setter that expects a non-nullable argument.

### 4. Please link to the relevant issues (if any).
no issue found

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Both fields are required. So I would say more your test data are invalid. https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Customer/CustomerDefinition.php#L86-L87

**Comment by Guite** [comment]
Thanks @shyim for the quick reaction.
Looking at the customer and his addresses in the admin area works like a charm.
In the database I noticed at least on of the addresses does not have any `country_state_id` assigned. Could this be a problem because of `$criteria->addAssociation('countryState');`?

**Comment by shyim** [comment]
The associations are joined with an left join. They don't affect the row count :)

**Comment by Guite** [comment]
Thank you. Closing this one.

**Pull request closed without merging**
