### PR TITLE
NEXT-00000 Update SalesChannelApiTestBehaviour.php

### PR DESCRIPTION
**Pull request by amenk**
This makes a subtle change to the create methods to be able to use them in a broader way, for example by creating saleschannels with more than one domain.

### 5. Checklist

- [ ] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 8b0fe67</samp>

Enhance `SalesChannelApiTestBehaviour` to allow more customization of test entities. Use `array_merge_recursive` to merge the default and custom attributes of sales channel and customer entities in `createSalesChannelContext` and `createCustomerAndLogin` functions.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 8b0fe67</samp>

* Replace `array_merge` with `array_merge_recursive` in two functions to allow merging nested arrays in parameters ([link](https://github.com/shopware/shopware/pull/3469/files?diff=unified&w=0#diff-79966aefc83ccd217a5748651449bf180081445228de90daf648d7f71da67871L185-R185), [link](https://github.com/shopware/shopware/pull/3469/files?diff=unified&w=0#diff-79966aefc83ccd217a5748651449bf180081445228de90daf648d7f71da67871L229-R229))

### CODE REVIEW

**Comment by AydinHassan** [comment]
@amenk unfortunately looks like some tests are broken, could you take a look maybe?

**Comment by AydinHassan** [comment]
@amenk can you try for your use case `array_replace_recursive` ? it passes our test suite at least, so that could be the solution.

**Comment by amenk** [comment]
@AydinHassan that would work, shall I update it? Shall I write a changelog? (not really needed for such a small change from my side...)

**Comment by AydinHassan** [comment]
@amenk I will take care :)

**Comment by AydinHassan** [comment]
@amenk it's merged, thanks for your contribution 🎉

**Pull request closed without merging**
