### PR TITLE
Fix API Documentation for `_action/order/{orderId}/document/{documentTypeName}` method

### PR DESCRIPTION
**Pull request by l3l0**
### 1. Why is this change necessary?

Method https://shopware.stoplight.io/docs/admin-api/b3A6MTI2MjUzOTM-create-a-document-for-an-order has not valid documentation

### 2. What does this change do, exactly?

Just change OpenApi annotation to present request body correctly in the documentation of api

### 3. Describe each step to reproduce the issue or behaviour.

Just send a document create request via the API using the config nested into an array, as documented

Please check https://github.com/shopware/platform/issues/2584

### 4. Please link to the relevant issues (if any).

https://github.com/shopware/platform/issues/2584

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/workflow/2020-08-03-implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Christian-Rades** [comment]
Hi @l3l0, thank you for your contribution. unfortunately, we just merged a big PR to move away from annotations to explicit files. (That's the merge conflict :sweat_smile: )  
We still like your change, though. If you resolve the conflict by making your change to `src/Core/Framework/Api/ApiDefinition/Generator/Schema/AdminApi/paths/order.json`, we can merge your PR.

**Comment by l3l0** [comment]
@Christian-Rades ok I will try to update that today :) Thank you for the info.

**Comment by l3l0** [comment]
@Christian-Rades ok updated

**Comment by Christian-Rades** [comment]
Hello,

thank you for creating this pull request.
I have opened an issue on our Issue Tracker for you. See the issue link: https://issues.shopware.com/issues/NEXT-22765

Please use this issue to track the state of your pull request.

**Comment by Christian-Rades** [comment]
Thanks for your contribution :tada:

**Pull request closed without merging**
