### PR TITLE
Fix block order sw-property-option-list

### PR DESCRIPTION
**Pull request by MelvinAchterhuis**
### 1. Why is this change necessary?

Currently the block is closed to early and makes extending the file a little harder

### 2. What does this change do, exactly?

Closes the block at the correct position

### 3. Describe each step to reproduce the issue or behaviour.

N/A

### 4. Please link to the relevant issues (if any).

N/A

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by dfrancos-hub** [comment]
Hi @MelvinAchterhuis, you are right its a bit hard to extend, but unfortunately this would be potentially a breaking change and could only be done in a major. Thanks in any case for your support.

**Comment by MelvinAchterhuis** [comment]
@dfrancos-hub , then this still should be labeled as "Scheduled" as it can be merged with 6.5.0.0, correct?

**Comment by dfrancos-hub** [comment]
hi @MelvinAchterhuis, in that case, in order to include it in the 6.5.0.0 we need to include the deprecation information as described here https://developer.shopware.com/docs/resources/guidelines/code/backward-compatibility . Thanks again in advance.

**Comment by dfrancos-hub** [comment]
Hi @MelvinAchterhuis, we need to close PRs that are inactive for a while, including this one. Please open a new PR when you could continue. Thanks

**Pull request closed without merging**
