### PR TITLE
fix: Order of the ZIP code and city field

### PR DESCRIPTION
**Pull request by aragon999**
### 1. Why is this change necessary?
See https://github.com/shopware/shopware/pull/3663 and https://github.com/shopware/shopware/issues/3927

### 2. What does this change do, exactly?
Fix the issue of ordering and introduce a admin setting component to configure the setting.

### 3. Describe each step to reproduce the issue or behaviour.
\-

### 4. Please link to the relevant issues (if any).
\-

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by mstegmeyer** [comment]
Hey @aragon999, thanks for your contribution. Since we have the advanced address formatting per country since about a year, this toggle would not be valid for address renderings, only for the form. Therefore, I would suggest to move this into the `loginRegistration.xml` and not recreate the `address.xml` file. What do you think?

And only god knows, why that weird `sw-settings-address.html.twig` still exists, feel free to delete it, since there is no component associated with it.

**Comment by aragon999** [comment]
@mstegmeyer you are right. My thought was, that if in the past someone has configured something in this setting, the backwards compatibility would still be given. But maybe I can rename the setting using a migration?

**Comment by aragon999** [comment]
@mstegmeyer I updated the PR accordingly :-)

Edit: The migration test fails, as the newly added migration is already executed in the setup, if I am not mistaken. How should that in general be handled/tested?

**Comment by mstegmeyer** [comment]
Hey, first of all: thanks for implementing the changes. Looks good now!

Regarding the Migration Test: You need to create mock values in the system config for the migration to update again for testing. There is no other way unfortunately.

**Comment by aragon999** [comment]
Okay perfect, I "reverted" the migration itself in the migration test.

**Comment by mstegmeyer** [comment]
From one Max to another: Thank you for your contribution 💙 we've just merged your improvement 🎉

**Comment by aragon999** [comment]
@mstegmeyer thanks a lot :-)

**Pull request closed without merging**
